/**
 * BloggerBear public frontend -- plain static single-page app, no build step,
 * no framework, no npm. Hash-based client-side routing:
 *   #/                 -> home / topic list
 *   #/topic/{id}       -> published article list for a topic
 *   #/article/{id}     -> full article view
 *   #/terms            -> Terms of Service (static content, no API call)
 *   #/privacy          -> Privacy Policy (static content, no API call)
 *
 * Talks to the public API at window.PUBLIC_API_URL (e.g.
 * "https://xxxx.execute-api.ap-southeast-2.amazonaws.com"), set by
 * config.js (generated by Terraform at deploy time, not by this file).
 *
 * Rendering uses plain DOM APIs (createElement / textContent) rather than
 * innerHTML with interpolated content, so that article titles/bodies (data
 * from our own backend, but ultimately Bedrock-generated free text) can
 * never be interpreted as markup.
 */

(function () {
  "use strict";

  var navEl = document.getElementById("nav");
  var contentEl = document.getElementById("content");

  function apiUrl(path) {
    return window.PUBLIC_API_URL + path;
  }

  function clearChildren(el) {
    while (el.firstChild) {
      el.removeChild(el.firstChild);
    }
  }

  function el(tag, opts) {
    var node = document.createElement(tag);
    opts = opts || {};
    if (opts.text !== undefined) {
      node.textContent = opts.text;
    }
    if (opts.className) {
      node.className = opts.className;
    }
    if (opts.href !== undefined) {
      node.setAttribute("href", opts.href);
    }
    // Generic escape hatch for anything not worth its own named option
    // above -- primarily aria-*/role/tabindex/type, used throughout the
    // accessibility-focused elements below.
    if (opts.attrs) {
      for (var attrName in opts.attrs) {
        if (Object.prototype.hasOwnProperty.call(opts.attrs, attrName)) {
          node.setAttribute(attrName, opts.attrs[attrName]);
        }
      }
    }
    return node;
  }

  function showMessage(text) {
    clearChildren(contentEl);
    contentEl.appendChild(el("p", { text: text }));
  }

  function fetchJson(url) {
    return fetch(url).then(function (response) {
      if (!response.ok) {
        throw new Error("request failed: " + response.status);
      }
      return response.json();
    });
  }

  // --- Nav ------------------------------------------------------------

  // Phase 8: the cross-topic "trending everywhere" digest isn't a real
  // Topic (no adapter, no cadence -- see trending_digest_handler.py), so
  // it never comes back from GET /topics and needs its own static nav
  // entry rather than the dynamic ones below. It links to the exact same
  // #/topic/{id} route every other topic uses (topic_id "digest"), which
  // already renders correctly with zero routing changes -- including the
  // "No published articles yet." empty state, before the first digest
  // has run.
  var DIGEST_TOPIC_ID = "digest";

  // BloggerBear's musings feed -- not a topic at all (no article_count/
  // researching fields, nothing to rank), so it's a second static nav
  // entry alongside Trending Everywhere, always visible regardless of how
  // many real topics get capped out of selectNavTopics below.
  var MUSINGS_ROUTE_HASH = "#/musings";

  // Public cost/token statistics page -- same category as Musings/Trending
  // Everywhere: not a topic, always visible in the nav.
  var STATS_ROUTE_HASH = "#/stats";

  // Keeps the compact header nav usable regardless of how many topics
  // exist: at most this many real topics ever show there, ranked by
  // actual publishing activity rather than declaration order, so a
  // 10-topic account doesn't turn the header into a wall of links. The
  // full, uncapped list still lives on the home page (renderHome).
  var NAV_TOPIC_LIMIT = 3;

  function selectNavTopics(topics) {
    var withArticles = topics
      .filter(function (t) {
        return t.article_count > 0;
      })
      .sort(function (a, b) {
        return (b.latest_published_at || "").localeCompare(a.latest_published_at || "");
      });

    var remaining = NAV_TOPIC_LIMIT - withArticles.length;
    var researchingOnly = [];
    if (remaining > 0) {
      researchingOnly = topics
        .filter(function (t) {
          return t.article_count === 0 && t.researching;
        })
        .sort(function (a, b) {
          return a.name.localeCompare(b.name);
        })
        .slice(0, remaining);
    }

    return withArticles.slice(0, NAV_TOPIC_LIMIT).concat(researchingOnly);
  }

  function renderNav(topics) {
    clearChildren(navEl);
    var digestLink = el("a", {
      text: "Trending Everywhere",
      href: "#/topic/" + DIGEST_TOPIC_ID,
      className: "digest-link",
    });
    navEl.appendChild(digestLink);
    var musingsLink = el("a", {
      text: "Musings",
      href: MUSINGS_ROUTE_HASH,
      className: "musings-link",
    });
    navEl.appendChild(musingsLink);
    navEl.appendChild(el("a", { text: "Stats", href: STATS_ROUTE_HASH, className: "stats-link" }));
    selectNavTopics(topics).forEach(function (topic) {
      var link = el("a", { text: topic.name, href: "#/topic/" + encodeURIComponent(topic.topic_id) });
      navEl.appendChild(link);
    });
  }

  function loadNav() {
    fetchJson(apiUrl("/topics"))
      .then(function (data) {
        renderNav(data.topics || []);
      })
      .catch(function () {
        // Nav failing to load shouldn't block the rest of the page.
        clearChildren(navEl);
      });
  }

  // --- Home -------------------------------------------------------------

  // One h1 per page is the rule this whole app follows (renderArticle,
  // renderArticleList, renderLegalPage each have exactly one) -- on the
  // home route specifically, the hero tagline below is that h1, so the
  // topic list heading right after it is an h2, not a second h1.
  var HOME_TAGLINE =
    "BloggerBear researches its own stories, drafts them, and publishes " +
    "them — with almost no human in the loop.";

  function renderHome(topics) {
    clearChildren(contentEl);

    var hero = el("section", { className: "hero" });
    hero.appendChild(el("h1", { text: "BloggerBear" }));
    hero.appendChild(el("p", { className: "tagline", text: HOME_TAGLINE }));
    hero.appendChild(
      el("a", {
        text: "Find out more",
        href: "about.html",
        className: "find-out-more",
        attrs: { "aria-label": "Find out more about how BloggerBear works" },
      })
    );
    contentEl.appendChild(hero);

    contentEl.appendChild(el("h2", { text: "Topics", className: "section-heading" }));

    if (topics.length === 0) {
      contentEl.appendChild(el("p", { text: "No topics yet." }));
      return;
    }

    var list = el("ul", { className: "topic-list" });
    topics.forEach(function (topic) {
      var item = el("li");
      var link = el("a", { text: topic.name, href: "#/topic/" + encodeURIComponent(topic.topic_id) });
      item.appendChild(link);
      item.appendChild(document.createTextNode(" "));
      item.appendChild(el("span", { className: "topic-article-count", text: topicCountLabel(topic) }));
      list.appendChild(item);
    });
    contentEl.appendChild(list);
  }

  function topicCountLabel(topic) {
    if (topic.article_count > 0) {
      return topic.article_count === 1 ? "(1 article)" : "(" + topic.article_count + " articles)";
    }
    return topic.researching ? "(researching)" : "(no articles yet)";
  }

  function loadHome() {
    showMessage("Loading topics...");
    fetchJson(apiUrl("/topics"))
      .then(function (data) {
        renderHome(data.topics || []);
      })
      .catch(function () {
        showMessage("Could not load topics right now.");
      });
  }

  // --- Topic article list -------------------------------------------------

  function formatDate(isoString) {
    if (!isoString) {
      return "";
    }
    var date = new Date(isoString);
    if (isNaN(date.getTime())) {
      return isoString;
    }
    return date.toLocaleDateString();
  }

  // --- AI lineage display (docs/project-plan.md §11) ------------------------
  //
  // Mirrors lambdas/common/static_pages.py's server-side rendering of the
  // same data (that one is baked into the static article pages at publish
  // time; this is the client-rendered equivalent for the SPA's own views) --
  // keep the wording/format of the two in sync. Any article published
  // before lineage tracking existed comes back with lineage/published_by
  // as explicit nulls, and every helper below renders that as a plainly
  // worded "No data" rather than a blank gap that would look like a bug.

  var PUBLISHED_BY_LABELS = {
    ai_only: "AI only",
    humans: "Humans",
    humans_and_ai: "Humans & AI",
  };

  function formatCount(value) {
    return Number(value || 0).toLocaleString("en-US");
  }

  function publishedByLabel(publishedBy) {
    if (publishedBy === null || publishedBy === undefined) {
      return "No data";
    }
    return PUBLISHED_BY_LABELS[publishedBy] || String(publishedBy);
  }

  // A model's readable name (recorded in the lineage when it was built), else its id.
  function modelName(labels, modelId) {
    return (labels && labels[modelId]) || modelId;
  }

  function modelNames(modelsUsed, labels) {
    return (modelsUsed || []).map(function (modelId) {
      return modelName(labels, modelId);
    });
  }

  // "12 finding(s): X in / Y out" -- the research the article's findings cost.
  function researchText(research) {
    var tracked = Number(research.tracked_findings || 0);
    var untracked = Number(research.untracked_findings || 0);
    if (!tracked) {
      return untracked ? "Not tracked (" + untracked + " finding(s) predate research tracking)" : "No research calls";
    }
    var text = tracked + " finding(s): " + formatCount(research.input_tokens) + " in / " + formatCount(research.output_tokens) + " out";
    if (untracked) {
      text += " (+" + untracked + " earlier finding(s) not tracked)";
    }
    return text;
  }

  function costLabel(costAud, costNote) {
    if (typeof costAud === "number") {
      return "~$" + costAud.toFixed(2) + " AUD";
    }
    return costNote || "No data";
  }

  // "model: X in / Y out" per model actually used, summed across every call
  // that used it (an article can span more than one model, e.g. a fallback
  // kicking in partway through).
  function perModelTokenText(lineage) {
    var totals = {};
    var order = [];
    ((lineage && lineage.calls) || []).forEach(function (call) {
      var modelId = call.model_id || "";
      if (!Object.prototype.hasOwnProperty.call(totals, modelId)) {
        totals[modelId] = { input: 0, output: 0 };
        order.push(modelId);
      }
      totals[modelId].input += Number(call.input_tokens || 0);
      totals[modelId].output += Number(call.output_tokens || 0);
    });
    if (order.length === 0) {
      return "No data";
    }
    return order
      .map(function (modelId) {
        return modelName(lineage.model_labels, modelId) + ": " + formatCount(totals[modelId].input) + " in / " + formatCount(totals[modelId].output) + " out";
      })
      .join(", ");
  }

  // Compact one-line summary. The article page has the full lineage.calls
  // detail (per-model tokens); the topic listing only gets a slim projection
  // (totals, not per-call -- see public_api_handler.py's _list_articles), so
  // `tokensText` is passed in by whichever caller has the right level of
  // detail rather than computed here.
  function lineageSummaryText(modelsUsed, tokensText, publishedBy, costAud, costNote, hasLineage, modelLabels) {
    if (!hasLineage && (publishedBy === null || publishedBy === undefined)) {
      return "No data";
    }
    var models = modelsUsed && modelsUsed.length > 0 ? modelNames(modelsUsed, modelLabels).join(", ") : "no data";
    return (
      "models [" + models + "] · tokens [" + tokensText + "] · approved by " +
      publishedByLabel(publishedBy) + " · " + (hasLineage ? costLabel(costAud, costNote) : "No data")
    );
  }

  function articleDetailSummaryText(article) {
    var lineage = article.lineage;
    var hasLineage = lineage !== null && lineage !== undefined;
    return lineageSummaryText(
      hasLineage ? lineage.models_used : null,
      hasLineage ? perModelTokenText(lineage) : "no data",
      article.published_by,
      hasLineage ? lineage.cost_aud : null,
      hasLineage ? lineage.cost_note : null,
      hasLineage,
      hasLineage ? lineage.model_labels : null
    );
  }

  function articleListSummaryText(article) {
    var hasLineage = article.models_used !== null && article.models_used !== undefined;
    var tokensText = "no data";
    if (hasLineage && article.total_input_tokens !== null && article.total_input_tokens !== undefined) {
      tokensText = formatCount(article.total_input_tokens) + " in / " + formatCount(article.total_output_tokens) + " out";
    }
    return lineageSummaryText(
      article.models_used,
      tokensText,
      article.published_by,
      article.cost_aud,
      article.cost_note,
      hasLineage,
      article.model_labels
    );
  }

  // The fuller footer block, same shape as the static page's
  // <footer class="lineage-footer"> -- always rendered, even when empty.
  function renderLineageFooter(lineage, publishedBy) {
    var hasLineage = lineage !== null && lineage !== undefined;
    var models = hasLineage && lineage.models_used && lineage.models_used.length > 0
      ? modelNames(lineage.models_used, lineage.model_labels).join(", ")
      : "No data";

    var footer = el("footer", { className: "lineage-footer", attrs: { "aria-label": "Article lineage" } });
    footer.appendChild(el("h2", { text: "Lineage" }));

    var list = el("dl");
    [
      ["Models", models],
      ["Tokens", hasLineage ? perModelTokenText(lineage) : "No data"],
      ["Approved by", publishedByLabel(publishedBy)],
      ["Approx. cost", hasLineage ? costLabel(lineage.cost_aud, lineage.cost_note) : "No data"],
    ].concat(
      // The research the article's findings cost, tallied hourly and bundled in
      // when the article was written; absent on an article made before that.
      hasLineage && lineage.research
        ? [
            ["Research tokens", researchText(lineage.research)],
            ["Research cost", costLabel(lineage.research.cost_aud, lineage.research.cost_note)],
            ["Total cost", costLabel(lineage.total_cost_aud, null)],
          ]
        : []
    ).forEach(function (row) {
      list.appendChild(el("dt", { text: row[0] }));
      list.appendChild(el("dd", { text: row[1] }));
    });
    footer.appendChild(list);
    return footer;
  }

  // --- Articles in the Pipeline --------------------------------------
  //
  var PENDING_REVIEW_LABEL = "Pending review";
  var RESEARCHING_LABEL = "Researching";

  function pipelineItemsFor(activity) {
    if (activity && Array.isArray(activity.pipeline_items) && activity.pipeline_items.length > 0) {
      return activity.pipeline_items.map(function (item) {
        return {
          label: item.label || (item.status === "pending_review" ? PENDING_REVIEW_LABEL : RESEARCHING_LABEL),
          title: item.title || "",
        };
      });
    }

    var items = [];
    var pendingCount = Number(activity && activity.pending_review_count) || 0;
    for (var i = 0; i < pendingCount; i++) {
      items.push({ label: PENDING_REVIEW_LABEL, title: "" });
    }
    if (activity && activity.researching) {
      items.push({ label: RESEARCHING_LABEL, title: "" });
    }
    return items;
  }

  function renderPipelineSection(items) {
    var box = el("section", { className: "pipeline-box", attrs: { "aria-label": "Articles in the pipeline" } });

    var titleBar = el("div", { className: "pipeline-titlebar" });
    // Decorative spinner -- aria-hidden so a screen reader doesn't
    // announce it at all; the meaningful content is the title bar text
    // and the list items themselves, both left as plain accessible text.
    titleBar.appendChild(el("span", { className: "pipeline-spinner", attrs: { "aria-hidden": "true" } }));
    titleBar.appendChild(el("span", { className: "pipeline-bear", text: "🐻", attrs: { "aria-hidden": "true" } }));
    titleBar.appendChild(el("span", { className: "pipeline-title", text: "Articles in the Pipeline" }));
    box.appendChild(titleBar);

    var list = el("ul", { className: "pipeline-list" });
    items.forEach(function (item) {
      var row = el("li");
      row.appendChild(el("span", { className: "pipeline-status", text: item.label }));
      if (item.title) {
        row.appendChild(el("span", { className: "pipeline-item-title", text: item.title }));
      }
      list.appendChild(row);
    });
    box.appendChild(list);

    return box;
  }

  function renderArticleList(topicId, articles, activity) {
    clearChildren(contentEl);
    var heading = topicId === DIGEST_TOPIC_ID ? "Trending Everywhere" : topicId;
    contentEl.appendChild(el("h1", { text: heading }));

    var pipelineItems = pipelineItemsFor(activity);
    if (pipelineItems.length > 0) {
      contentEl.appendChild(renderPipelineSection(pipelineItems));
    }

    if (articles.length === 0) {
      // "researching" (docs/project-plan.md §11) distinguishes "nothing
      // published yet, but BloggerBear has started gathering findings for
      // this topic" from a topic with no activity at all -- see
      // GET /topics/{topic_id}/activity in public_api_handler.py. Skip
      // this text entirely when the pipeline box above already conveyed
      // "something's coming" -- showing both would just be redundant.
      if (pipelineItems.length === 0) {
        contentEl.appendChild(el("p", { text: "No published articles yet." }));
      }
      return;
    }

    var list = el("ul", { className: "article-list" });
    articles.forEach(function (article) {
      var item = el("li");
      var link = el("a", {
        text: article.title,
        href: "#/article/" + encodeURIComponent(article.article_id),
      });
      item.appendChild(link);
      item.appendChild(el("span", { className: "article-date", text: " " + formatDate(article.published_at) }));
      item.appendChild(el("div", { className: "lineage-summary", text: articleListSummaryText(article) }));
      list.appendChild(item);
    });
    contentEl.appendChild(list);
  }

  function loadTopicArticles(topicId) {
    showMessage("Loading articles...");
    fetchJson(apiUrl("/articles?topic_id=" + encodeURIComponent(topicId)))
      .then(function (data) {
        var articles = data.articles || [];
        // Always fetch activity now, not just when articles is empty --
        // "Articles in the Pipeline" can appear alongside already-
        // published articles too (e.g. 3 published + 1 pending review is
        // a perfectly normal state), unlike the old researching-only
        // placeholder which only ever mattered on an empty list.
        fetchJson(apiUrl("/topics/" + encodeURIComponent(topicId) + "/activity"))
          .then(function (activity) {
            renderArticleList(topicId, articles, activity);
          })
          .catch(function () {
            renderArticleList(topicId, articles, null);
          });
      })
      .catch(function () {
        showMessage("Could not load articles right now.");
      });
  }

  // --- Musings --------------------------------------------------------

  function renderMusings(musings) {
    clearChildren(contentEl);
    contentEl.appendChild(el("h1", { text: "Musings" }));

    if (musings.length === 0) {
      contentEl.appendChild(el("p", { text: "No musings yet -- check back after the next article." }));
      return;
    }

    var list = el("ul", { className: "musings-list" });
    musings.forEach(function (musing) {
      var item = el("li", { className: "musing-item" });
      item.appendChild(el("p", { className: "musing-text", text: musing.text }));

      var meta = el("p", { className: "musing-meta" });
      meta.appendChild(el("span", { text: formatDate(musing.created_at) }));
      if (musing.article_id) {
        meta.appendChild(document.createTextNode(" · "));
        meta.appendChild(
          el("a", { text: "read the article", href: "#/article/" + encodeURIComponent(musing.article_id) })
        );
      }
      item.appendChild(meta);

      list.appendChild(item);
    });
    contentEl.appendChild(list);
  }

  function loadMusings() {
    showMessage("Loading musings...");
    fetchJson(apiUrl("/musings"))
      .then(function (data) {
        renderMusings(data.musings || []);
      })
      .catch(function () {
        showMessage("Could not load musings right now.");
      });
  }

  // --- Stats ------------------------------------------------------------------
  //
  // Public cost/token statistics (docs/project-plan.md §11, PR 5 of 5), from
  // GET /stats -- aggregates only, never article content. One chart: spend
  // per day, the one thing here whose job is "change over time". Everything
  // else is a stat tile or a table -- a table IS the right form for the
  // by-model / by-topic breakdowns (comparison of exact values), and it is
  // also the accessible alternative to the chart, so the chart has a "View
  // as table" twin rather than being the only way to reach its numbers.
  //
  // The chart is built with SVG *presentation attributes* (x/y/width plus
  // classes), never `style` attributes -- the CloudFront CSP is
  // `style-src 'self'` with no 'unsafe-inline' (see infra/modules/static-
  // site), which blocks inline style attributes. Colors come from
  // styles.css classes using the site's own custom properties, so light/
  // dark mode is inherited rather than re-implemented here.

  var SVG_NS = "http://www.w3.org/2000/svg";

  function svgEl(tag, attrs) {
    var node = document.createElementNS(SVG_NS, tag);
    for (var name in attrs || {}) {
      if (Object.prototype.hasOwnProperty.call(attrs, name)) {
        node.setAttribute(name, attrs[name]);
      }
    }
    return node;
  }

  function formatAud(value) {
    if (value === null || value === undefined) {
      return "unpriced";
    }
    if (value === 0) {
      return "$0";
    }
    return "$" + Number(value).toFixed(Math.abs(value) >= 1 ? 2 : 3);
  }

  // Y-axis ticks: like formatAud but without the noisy trailing zero on
  // the 3-decimal small-value form ($0.200 -> $0.20).
  function formatAxisAud(value) {
    if (value === 0) {
      return "$0";
    }
    return "$" + Number(value).toFixed(3).replace(/0$/, "");
  }

  function formatShortDate(isoDate) {
    var date = new Date(isoDate + "T00:00:00Z");
    if (isNaN(date.getTime())) {
      return isoDate;
    }
    return date.toLocaleDateString(undefined, { month: "short", day: "numeric", timeZone: "UTC" });
  }

  // Round a value up to a clean 1/2/5 x 10^n ceiling, for a readable y-axis.
  function niceCeil(value) {
    if (!(value > 0)) {
      return 1;
    }
    var exponent = Math.pow(10, Math.floor(Math.log(value) / Math.LN10));
    var fraction = value / exponent;
    var nice = fraction <= 1 ? 1 : fraction <= 2 ? 2 : fraction <= 5 ? 5 : 10;
    return nice * exponent;
  }

  // A column with a 4px rounded data-end (top) and a square baseline.
  function columnPath(x, y, width, height) {
    var radius = Math.min(4, width / 2, height);
    return (
      "M" + x + "," + (y + height) +
      " V" + (y + radius) +
      " Q" + x + "," + y + " " + (x + radius) + "," + y +
      " H" + (x + width - radius) +
      " Q" + (x + width) + "," + y + " " + (x + width) + "," + (y + radius) +
      " V" + (y + height) + " Z"
    );
  }

  function statTile(label, value, sub) {
    var tile = el("div", { className: "stat-tile" });
    tile.appendChild(el("span", { className: "stat-label", text: label }));
    tile.appendChild(el("span", { className: "stat-value", text: value }));
    if (sub) {
      tile.appendChild(el("span", { className: "stat-sub", text: sub }));
    }
    return tile;
  }

  // rows: arrays of strings, first column left-aligned, the rest numeric.
  function statsTable(headers, rows) {
    var wrap = el("div", { className: "stats-table-wrap" });
    var table = el("table", { className: "stats-table" });
    var headRow = el("tr");
    headers.forEach(function (header, index) {
      headRow.appendChild(
        el("th", { text: header, className: index === 0 ? "" : "num", attrs: { scope: "col" } })
      );
    });
    table.appendChild(el("thead")).appendChild(headRow);
    var body = el("tbody");
    rows.forEach(function (row) {
      var tr = el("tr");
      row.forEach(function (cell, index) {
        tr.appendChild(el("td", { text: cell, className: index === 0 ? "" : "num" }));
      });
      body.appendChild(tr);
    });
    table.appendChild(body);
    wrap.appendChild(table);
    return wrap;
  }

  function articleCountText(count) {
    return count === 1 ? "1 article" : count + " articles";
  }

  function renderSpendChart(daily) {
    // viewBox width follows the container (1 SVG unit = 1 CSS px), so axis
    // text stays a readable 11px instead of scaling down with the chart on
    // a phone; columns get thinner instead. Sized once per render.
    var width = Math.max(320, Math.min(720, contentEl.clientWidth || 640));
    var height = 220;
    var left = 52;
    var right = 8;
    var top = 10;
    var bottom = 26;
    var plotWidth = width - left - right;
    var plotHeight = height - top - bottom;

    var maxCost = 0;
    daily.forEach(function (day) {
      maxCost = Math.max(maxCost, day.cost_aud);
    });
    var ceiling = niceCeil(maxCost);
    var slot = plotWidth / daily.length;
    var barWidth = Math.min(24, slot - 2);

    var wrap = el("div", { className: "stats-chart" });
    var tooltip = el("div", { className: "chart-tooltip", attrs: { role: "status" } });
    tooltip.hidden = true;
    wrap.appendChild(tooltip);

    var svg = svgEl("svg", {
      viewBox: "0 0 " + width + " " + height,
      class: "stats-chart-svg",
      role: "group",
      "aria-label": "Estimated AI spend per day in AUD, last " + daily.length + " days",
    });

    [0, 0.5, 1].forEach(function (fraction) {
      var y = top + plotHeight * (1 - fraction);
      svg.appendChild(svgEl("line", { x1: left, x2: width - right, y1: y, y2: y, class: "stats-grid" }));
      var label = svgEl("text", { x: left - 6, y: y + 4, "text-anchor": "end", class: "stats-axis-label" });
      label.textContent = formatAxisAud(ceiling * fraction);
      svg.appendChild(label);
    });

    [0, Math.floor((daily.length - 1) / 2), daily.length - 1].forEach(function (index) {
      var label = svgEl("text", {
        x: left + index * slot + slot / 2,
        y: height - 8,
        "text-anchor": index === 0 ? "start" : index === daily.length - 1 ? "end" : "middle",
        class: "stats-axis-label",
      });
      label.textContent = formatShortDate(daily[index].date);
      svg.appendChild(label);
    });

    function showTooltip(day, target, barTopY) {
      clearChildren(tooltip);
      tooltip.appendChild(el("strong", { text: formatAud(day.cost_aud) + " AUD" }));
      tooltip.appendChild(
        el("span", { text: formatShortDate(day.date) + " · " + articleCountText(day.articles) })
      );
      tooltip.hidden = false;
      var wrapBox = wrap.getBoundingClientRect();
      var targetBox = target.getBoundingClientRect();
      var half = tooltip.offsetWidth / 2;
      var center = targetBox.left + targetBox.width / 2 - wrapBox.left;
      tooltip.style.left = Math.min(Math.max(center, half), wrapBox.width - half) + "px";
      // Sit just above the hovered bar (SVG units -> rendered pixels) so the
      // tooltip never covers the mark it describes; clamp inside the chart.
      var scale = wrapBox.width / width;
      tooltip.style.top = Math.max(0, barTopY * scale - tooltip.offsetHeight - 6) + "px";
    }

    function hideTooltip() {
      tooltip.hidden = true;
    }

    daily.forEach(function (day, index) {
      var group = svgEl("g", { class: "stats-day" });
      var barHeight = (day.cost_aud / ceiling) * plotHeight;
      var barTopY = top + plotHeight - barHeight;
      if (barHeight > 0) {
        group.appendChild(
          svgEl("path", {
            d: columnPath(
              left + index * slot + (slot - barWidth) / 2,
              top + plotHeight - barHeight,
              barWidth,
              barHeight
            ),
            class: "stats-bar",
          })
        );
      }
      // Full-height hit target, wider than the mark itself (the 2px gap
      // between bars included), so hover/focus never needs pixel aim.
      var hit = svgEl("rect", {
        x: left + index * slot,
        y: top,
        width: slot,
        height: plotHeight,
        class: "stats-hit",
        tabindex: "0",
        "aria-label":
          formatShortDate(day.date) + ": " + formatAud(day.cost_aud) + " AUD, " + articleCountText(day.articles),
      });
      hit.addEventListener("pointerenter", function () {
        showTooltip(day, hit, barTopY);
      });
      hit.addEventListener("focus", function () {
        showTooltip(day, hit, barTopY);
      });
      hit.addEventListener("pointerleave", hideTooltip);
      hit.addEventListener("blur", hideTooltip);
      group.appendChild(hit);
      svg.appendChild(group);
    });

    wrap.appendChild(svg);
    return wrap;
  }

  function renderStats(stats) {
    clearChildren(contentEl);
    contentEl.appendChild(el("h1", { text: "Stats" }));
    contentEl.appendChild(el("p", { className: "stats-note", text: stats.cost_basis }));

    var totals = stats.totals;
    var spendSub = "AUD, all time";
    if (totals.unpriced_calls > 0) {
      spendSub +=
        " (lower bound: " + totals.unpriced_calls + " unpriced call" + (totals.unpriced_calls === 1 ? "" : "s") + ")";
    }
    var tiles = el("div", { className: "stats-tiles" });
    tiles.appendChild(statTile("Estimated AI spend", formatAud(totals.cost_aud), spendSub));
    tiles.appendChild(
      statTile("Articles drafted", formatCount(totals.articles), formatCount(totals.published) + " published")
    );
    tiles.appendChild(
      statTile(
        "Average cost per article",
        totals.avg_cost_aud === null ? "No data" : formatAud(totals.avg_cost_aud),
        "AUD, articles with cost data"
      )
    );
    tiles.appendChild(
      statTile(
        "Tokens",
        formatCount(totals.input_tokens + totals.output_tokens),
        formatCount(totals.input_tokens) + " in / " + formatCount(totals.output_tokens) + " out"
      )
    );
    // The part of the spend above that was the hourly research tick, bundled into
    // the article each finding fed. Older API responses have no `research` block.
    if (totals.research) {
      tiles.appendChild(
        statTile(
          "Research spend",
          formatAud(totals.research.cost_aud),
          formatCount(totals.research.input_tokens + totals.research.output_tokens) + " tokens over " +
            formatCount(totals.research.calls) + " summaries"
        )
      );
    }
    contentEl.appendChild(tiles);

    var daily = stats.daily || [];
    var activeDays = daily.filter(function (day) {
      return day.cost_aud > 0 || day.articles > 0;
    });
    contentEl.appendChild(el("h2", { text: "Estimated spend per day", className: "section-heading" }));
    if (activeDays.length === 0) {
      contentEl.appendChild(el("p", { text: "No spend recorded in the last " + daily.length + " days yet." }));
    } else {
      contentEl.appendChild(renderSpendChart(daily));
      var details = el("details", { className: "stats-details" });
      details.appendChild(el("summary", { text: "View as table" }));
      details.appendChild(
        statsTable(
          ["Date", "Articles", "Tokens in", "Tokens out", "Est. cost (AUD)"],
          activeDays.map(function (day) {
            return [
              formatShortDate(day.date),
              formatCount(day.articles),
              formatCount(day.input_tokens),
              formatCount(day.output_tokens),
              formatAud(day.cost_aud),
            ];
          })
        )
      );
      contentEl.appendChild(details);
    }

    contentEl.appendChild(el("h2", { text: "By model", className: "section-heading" }));
    if ((stats.by_model || []).length === 0) {
      contentEl.appendChild(el("p", { text: "No model usage recorded yet." }));
    } else {
      contentEl.appendChild(
        statsTable(
          ["Model", "Calls", "Tokens in", "Tokens out", "Est. cost (AUD)"],
          stats.by_model.map(function (row) {
            var cost = formatAud(row.cost_aud);
            if (row.cost_aud !== null && row.unpriced_calls > 0) {
              cost += " (+" + row.unpriced_calls + " unpriced)";
            }
            return [
              row.display_name,
              formatCount(row.calls),
              formatCount(row.input_tokens),
              formatCount(row.output_tokens),
              cost,
            ];
          })
        )
      );
    }

    contentEl.appendChild(el("h2", { text: "By topic", className: "section-heading" }));
    if ((stats.by_topic || []).length === 0) {
      contentEl.appendChild(el("p", { text: "No topic usage recorded yet." }));
    } else {
      contentEl.appendChild(
        statsTable(
          ["Topic", "Articles", "Tokens in", "Tokens out", "Est. cost (AUD)", "of which research"],
          stats.by_topic.map(function (row) {
            return [
              row.name,
              formatCount(row.articles),
              formatCount(row.input_tokens),
              formatCount(row.output_tokens),
              formatAud(row.cost_aud),
              row.research ? formatAud(row.research.cost_aud) : "No data",
            ];
          })
        )
      );
    }

    if (stats.generated_at) {
      contentEl.appendChild(
        el("p", { className: "stats-note", text: "Updated " + new Date(stats.generated_at).toLocaleString() })
      );
    }
  }

  function loadStats() {
    showMessage("Loading stats...");
    fetchJson(apiUrl("/stats"))
      .then(renderStats)
      .catch(function () {
        showMessage("Could not load stats right now.");
      });
  }

  // --- Article detail -----------------------------------------------------

  function renderArticle(article) {
    clearChildren(contentEl);

    contentEl.appendChild(el("h1", { text: article.title }));

    var meta = el("p", { className: "article-meta" });
    meta.appendChild(el("span", { text: "Published " + formatDate(article.published_at) }));
    meta.appendChild(document.createTextNode(" · "));
    meta.appendChild(el("span", { className: "view-count", text: article.view_count + " views" }));
    contentEl.appendChild(meta);
    contentEl.appendChild(el("p", { className: "lineage-summary", text: articleDetailSummaryText(article) }));

    var body = el("div", { className: "article-body" });
    // Render body as plain text paragraphs, split on blank lines, rather
    // than trusting/parsing it as HTML.
    var paragraphs = String(article.body || "").split(/\n\s*\n/);
    paragraphs.forEach(function (paragraph) {
      if (paragraph.trim() === "") {
        return;
      }
      body.appendChild(el("p", { text: paragraph }));
    });
    contentEl.appendChild(body);

    var sourceRefs = article.source_refs || [];
    if (sourceRefs.length > 0) {
      var sourcesSection = el("footer", { className: "sources-footer" });
      sourcesSection.appendChild(el("h2", { text: "Sources" }));
      var sourcesList = el("ul");
      sourcesSection.setAttribute("aria-label", "Sources");
      sourceRefs.forEach(function (ref) {
        var item = el("li");
        var refLabel = ref.title || ref.url;
        // These links leave the site to third-party domains (the
        // original source page a Finding was based on) -- calling that
        // out in the accessible name, not just visually, matches how a
        // sighted user infers "this isn't part of this site" from the
        // "Sources" heading above it.
        var link = el("a", {
          text: refLabel,
          href: ref.url,
          attrs: { "aria-label": refLabel + " (external source link)" },
        });
        item.appendChild(link);
        item.appendChild(
          document.createTextNode(" (accessed " + formatDate(ref.accessed_at) + ")")
        );
        sourcesList.appendChild(item);
      });
      sourcesSection.appendChild(sourcesList);
      contentEl.appendChild(sourcesSection);
    }

    contentEl.appendChild(renderLineageFooter(article.lineage, article.published_by));
    contentEl.appendChild(renderFeedback(article.article_id));
  }

  // --- Feedback -----------------------------------------------------------

  function renderFeedback(articleId) {
    var section = el("section", { className: "feedback" });
    section.appendChild(el("h2", { text: "Feedback" }));

    // aria-live="polite" + aria-atomic="true": screen readers announce
    // "Submitting...", then "Thanks for your feedback!" (or the error
    // message) as they appear, the same way a sighted user sees the
    // status line update -- without this, those changes are silent to
    // assistive tech, since nothing else on the page moves focus or
    // otherwise signals that anything happened.
    var status = el("p", {
      className: "feedback-status",
      attrs: { "aria-live": "polite", "aria-atomic": "true" },
    });

    var upButton = el("button", {
      text: "Upvote",
      attrs: { type: "button", "aria-label": "Upvote this article" },
    });
    var downButton = el("button", {
      text: "Downvote",
      attrs: { type: "button", "aria-label": "Downvote this article" },
    });

    var commentHintId = "feedback-comment-hint-" + encodeURIComponent(articleId);
    var commentHint = el("p", {
      className: "feedback-comment-hint",
      text: "Please don't include your name, contact details, or any other personal information.",
      attrs: { id: commentHintId },
    });

    var commentLabel = el("label", { text: "Comment (optional)" });
    var commentInput = document.createElement("textarea");
    commentInput.setAttribute("rows", "3");
    // Announces the same "don't share personal info" reminder from the
    // Privacy Policy to screen-reader users at the point they're about
    // to type a comment, not just on a separate page they may never
    // visit.
    commentInput.setAttribute("aria-describedby", commentHintId);
    commentLabel.appendChild(document.createElement("br"));
    commentLabel.appendChild(commentInput);

    var buttonRow = el("div", { className: "feedback-buttons" });
    buttonRow.appendChild(upButton);
    buttonRow.appendChild(downButton);

    function setDisabled(disabled) {
      upButton.disabled = disabled;
      downButton.disabled = disabled;
      commentInput.disabled = disabled;
    }

    function submitVote(vote) {
      setDisabled(true);
      status.textContent = "Submitting...";

      var commentValue = commentInput.value.trim();
      var payload = { vote: vote, comment: commentValue === "" ? null : commentValue };

      fetch(apiUrl("/articles/" + encodeURIComponent(articleId) + "/feedback"), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      })
        .then(function (response) {
          if (!response.ok) {
            throw new Error("request failed: " + response.status);
          }
          status.textContent = "Thanks for your feedback!";
        })
        .catch(function () {
          status.textContent = "Could not submit feedback right now. Please try again.";
          setDisabled(false);
        });
    }

    upButton.addEventListener("click", function () {
      submitVote("up");
    });
    downButton.addEventListener("click", function () {
      submitVote("down");
    });

    section.appendChild(buttonRow);
    section.appendChild(commentHint);
    section.appendChild(commentLabel);
    section.appendChild(status);
    return section;
  }

  // --- Legal pages (Terms of Service / Privacy Policy) --------------------
  //
  // Static content, not fetched from the API -- rendered with the same
  // el()/DOM-construction helpers as everything else on this page, for
  // consistency (and so this content, like everything else here, never
  // goes through innerHTML). Grounded in what this codebase actually
  // does, not boilerplate: no cookies (verified against both the
  // frontend source and the CloudFront config, which explicitly forwards
  // none), an anonymous per-article view counter, anonymous feedback
  // that goes through a two-pass PII redaction before being stored (see
  // lambdas/common/compliance.py), and infrastructure-level WAF logging
  // that's kept separate from application data (see
  // docs/project-plan.md §7).

  var GITHUB_REPO_URL = "https://github.com/AllainWoodsford/BloggerBear";

  var LEGAL_PAGES = {
    terms: {
      title: "Terms of Service",
      sections: [
        {
          heading: "1. About this site",
          paragraphs: [
            "BloggerBear is a personal, non-commercial portfolio and demonstration project — an experiment in autonomous, AI-assisted research and publishing. Software periodically checks public data sources (currently GitHub Trending, Hacker News, and public cryptocurrency market data), uses an AI model (Amazon Bedrock / Claude) to summarize findings and draft articles, and runs an automated compliance review before anything is published. It is not a commercial product, a news organization, or a registered business.",
          ],
        },
        {
          heading: "2. AI-generated content",
          paragraphs: [
            "Most article content on this site is drafted by an AI model from publicly available source data, then automatically reviewed for compliance before publishing; some drafts are additionally held for manual human review. Despite that review, AI-generated content can still be inaccurate, incomplete, or out of date. Nothing on this site should be treated as professional advice of any kind.",
          ],
        },
        {
          heading: "3. Not financial advice",
          paragraphs: [
            "Any article touching cryptocurrency or other financial/investment topics is generated under a stricter compliance rubric, is always held for manual human review before publishing regardless of how confident the automated review is, and carries a standing notice that it is not financial or investment advice. Nothing on this site is, or should be understood as, a recommendation to buy, sell, or hold any asset. Always do your own research and consult a qualified professional before making financial decisions.",
          ],
        },
        {
          heading: "4. No warranty, availability, or permanence",
          paragraphs: ["This is a hobby/portfolio project, run by a single operator — not a supported product."],
          list: [
            "No uptime, availability, or continuity is guaranteed.",
            "The site, every article on it, and the infrastructure behind it may be taken offline, modified, reset, or permanently deleted at any time, without notice.",
            "The site and its content are provided “as is” and “as available,” without warranties of any kind, express or implied — including accuracy, reliability, merchantability, or fitness for a particular purpose.",
            "The operator is not liable for any loss or damage arising from your use of, or inability to use, this site or its content.",
          ],
        },
        {
          heading: "5. Source material and attribution",
          paragraphs: [
            "Each article's “Sources” links point to the original public pages a piece of research was based on. That source material belongs to its respective owners — BloggerBear doesn't claim ownership of it, and links to it for attribution and further reading.",
          ],
        },
        {
          heading: "6. Anonymous feedback",
          paragraphs: [
            "You may leave anonymous feedback (a thumbs up/down and an optional comment) on published articles — see the Privacy Policy for what happens to that data. By submitting a comment, you agree not to include personal information about yourself or anyone else, and not to submit anything unlawful, abusive, or that infringes someone else's rights. A comment may be automatically redacted, or never published at all, if it can't be confirmed safe.",
          ],
        },
        {
          heading: "7. Acceptable use",
          paragraphs: [
            "Please don't attempt to abuse, aggressively scrape, disrupt, or gain unauthorized access to this site or the systems behind it. Automated/programmatic use of the public read API and RSS feed is welcome — that's exactly what they're for.",
          ],
        },
        {
          heading: "8. Changes to these terms",
          paragraphs: [
            "Since this is an evolving personal project, these terms may change at any time as the project changes. Continued use of the site after a change means you accept the updated terms.",
          ],
        },
        {
          heading: "9. Contact",
          paragraphs: ["This project is developed in the open. Questions, issues, or takedown requests can be raised via its GitHub repository."],
          link: { text: "github.com/AllainWoodsford/BloggerBear", href: GITHUB_REPO_URL },
        },
      ],
    },
    privacy: {
      title: "Privacy Policy",
      sections: [
        {
          heading: "1. Short version",
          paragraphs: ["This is a small personal project with a deliberately minimal data footprint:"],
          list: [
            "No accounts, no logins, no user profiles.",
            "No cookies.",
            "No advertising or analytics trackers.",
            "No personal information is intentionally collected. If any ends up in a comment, automated redaction attempts to strip it before anything is stored — and you're asked not to include it in the first place (see “Please don't share personal information” below).",
          ],
        },
        {
          heading: "2. What we don't do",
          list: [
            "We do not use cookies. This is verified directly against this site's own source code and infrastructure configuration, not just asserted — the CloudFront distribution in front of this site is explicitly configured to forward none, and the frontend code contains no cookie-setting logic anywhere.",
            "We do not run any third-party analytics, advertising, or tracking scripts.",
            "We do not build profiles of individual visitors, and have no way to identify you from your use of this site.",
          ],
        },
        {
          heading: "3. What we do track: anonymous view counts",
          paragraphs: [
            "Each article has a public, anonymous view counter. Opening an article increments one shared counter for that article by one. This counter is not tied to your browser, device, or identity in any way — it's a running total, the same as a hit counter.",
          ],
        },
        {
          heading: "4. Feedback (votes and comments)",
          paragraphs: [
            "If you leave feedback on an article (a thumbs up/down, with an optional written comment), we store the vote, the comment text (if any, after automated redaction — see below), and when it was submitted. We do not store, log, or associate any of the following with your feedback: your IP address, browser fingerprint, account, or any other identifier. There is no way to trace a piece of feedback back to a specific visitor.",
          ],
        },
        {
          heading: "Please don't share personal information",
          paragraphs: [
            "Any comment you submit goes through a real, if best-effort, attempt to remove obvious personal information automatically — a pattern-matching pass, then a second AI-based review pass — before anything is stored. If that review can't confirm a comment is safe, the comment is dropped and only the vote is kept. But this is an automated filter, not a guarantee. Please don't include your name, email address, phone number, physical address, or any other personal or identifying information — about yourself or anyone else — in a comment. Assume anything you type could end up published.",
          ],
        },
        {
          heading: "5. Infrastructure and security logs",
          paragraphs: [
            "Like effectively every website, the infrastructure this site runs on (a web application firewall in front of the site and its APIs) keeps its own short-term operational logs — the kind that record request metadata, such as source IP address, purely to detect and block abusive traffic. These logs:",
          ],
          list: [
            "live entirely at the infrastructure level, inside the cloud provider's (AWS) own logging systems",
            "are never joined, matched, or cross-referenced with anything you submit through the site (feedback, view counts, or anything else)",
            "are not used to identify or profile visitors",
            "exist only for security and reliability, not analytics",
          ],
        },
        {
          heading: "6. Local storage on your device",
          paragraphs: [
            "This site uses a very small amount of your browser's local storage (localStorage) for exactly one purpose: remembering that you've dismissed the site notice banner, so it doesn't reappear on every visit. That preference lives only in your own browser — it is never sent to us, and clearing your browser data resets it.",
          ],
        },
        {
          heading: "7. Third-party AI processing",
          paragraphs: [
            "Article summaries and drafts are generated using Amazon Bedrock, a cloud AI service. Publicly available source data (trending repositories, news headlines, market prices) is sent to that service to generate content — no visitor data is ever sent there. If you submit a comment, the same service is also used purely to check the comment text for personal information before deciding whether to store it.",
          ],
        },
        {
          heading: "8. Data retention and deletion",
          paragraphs: [
            "Because this is a disposable, single-operator portfolio project (see the Terms of Service), the infrastructure behind everything described above — including this policy's own hosting — may be reset, rebuilt, or permanently deleted at any time, without notice. There is no guarantee any particular piece of content, feedback, or data will persist.",
          ],
        },
        {
          heading: "9. Changes to this policy",
          paragraphs: ["This policy may change as the project changes. Check back here for the current version."],
        },
        {
          heading: "10. Contact",
          paragraphs: ["Questions about this policy can be raised via the project's GitHub repository."],
          link: { text: "github.com/AllainWoodsford/BloggerBear", href: GITHUB_REPO_URL },
        },
      ],
    },
  };

  function renderLegalPage(pageKey) {
    var page = LEGAL_PAGES[pageKey];
    clearChildren(contentEl);
    contentEl.appendChild(el("h1", { text: page.title }));

    page.sections.forEach(function (section) {
      contentEl.appendChild(el("h2", { text: section.heading }));
      (section.paragraphs || []).forEach(function (paragraph) {
        contentEl.appendChild(el("p", { text: paragraph }));
      });
      if (section.list) {
        var list = el("ul");
        section.list.forEach(function (itemText) {
          var item = el("li", { text: itemText });
          list.appendChild(item);
        });
        contentEl.appendChild(list);
      }
      if (section.link) {
        var linkPara = el("p");
        linkPara.appendChild(el("a", { text: section.link.text, href: section.link.href }));
        contentEl.appendChild(linkPara);
      }
    });
  }

  // --- Site notice ----------------------------------------------------
  //
  // Not a cookie-consent banner (there are no cookies to consent to) --
  // an honest, upfront notice about the anonymous view counting and
  // infrastructure security logging this site does do. Shown once per
  // browser; dismissal is remembered in localStorage, the one and only
  // thing this site stores client-side (see the Privacy Policy, §6).
  var SITE_NOTICE_DISMISSED_KEY = "bloggerbear-site-notice-dismissed";

  function initSiteNotice() {
    var notice = document.getElementById("site-notice");
    var dismissButton = document.getElementById("site-notice-dismiss");
    if (!notice || !dismissButton) {
      return;
    }

    var alreadyDismissed = false;
    try {
      alreadyDismissed = window.localStorage.getItem(SITE_NOTICE_DISMISSED_KEY) === "1";
    } catch (err) {
      // Private browsing / storage disabled -- fall back to showing the
      // notice every visit rather than breaking the page.
      alreadyDismissed = false;
    }

    if (!alreadyDismissed) {
      notice.hidden = false;
    }

    dismissButton.addEventListener("click", function () {
      notice.hidden = true;
      try {
        window.localStorage.setItem(SITE_NOTICE_DISMISSED_KEY, "1");
      } catch (err) {
        /* ignore -- worst case the notice reappears next visit */
      }
    });
  }

  function recordView(articleId) {
    // Best-effort, anonymous view counting -- never blocks rendering and
    // never surfaces an error to the user if it fails.
    fetch(apiUrl("/articles/" + encodeURIComponent(articleId) + "/view"), {
      method: "POST",
    }).catch(function () {
      /* ignore */
    });
  }

  function loadArticle(articleId) {
    showMessage("Loading article...");
    fetchJson(apiUrl("/articles/" + encodeURIComponent(articleId)))
      .then(function (article) {
        renderArticle(article);
        recordView(articleId);
      })
      .catch(function () {
        showMessage("Article not found.");
      });
  }

  // --- Routing --------------------------------------------------------

  function parseRoute(hash) {
    // hash looks like "#/topic/foo" or "#/article/bar" or "#/" or "".
    var path = hash.replace(/^#/, "");
    if (path === "" || path === "/") {
      return { name: "home" };
    }
    var topicMatch = path.match(/^\/topic\/([^/]+)$/);
    if (topicMatch) {
      return { name: "topic", topicId: decodeURIComponent(topicMatch[1]) };
    }
    var articleMatch = path.match(/^\/article\/([^/]+)$/);
    if (articleMatch) {
      return { name: "article", articleId: decodeURIComponent(articleMatch[1]) };
    }
    if (path === "/terms") {
      return { name: "legal", pageKey: "terms" };
    }
    if (path === "/privacy") {
      return { name: "legal", pageKey: "privacy" };
    }
    if (path === "/musings") {
      return { name: "musings" };
    }
    if (path === "/stats") {
      return { name: "stats" };
    }
    return { name: "not-found" };
  }

  function route() {
    var current = parseRoute(window.location.hash);
    if (current.name === "home") {
      loadHome();
    } else if (current.name === "topic") {
      loadTopicArticles(current.topicId);
    } else if (current.name === "article") {
      loadArticle(current.articleId);
    } else if (current.name === "legal") {
      renderLegalPage(current.pageKey);
    } else if (current.name === "musings") {
      loadMusings();
    } else if (current.name === "stats") {
      loadStats();
    } else {
      showMessage("Page not found.");
    }

    // Move focus to the main content landmark on every navigation --
    // standard SPA accessibility practice (WCAG 2.4.3) so keyboard/
    // screen-reader users land on the new content instead of wherever
    // focus happened to be before. #content has tabindex="-1" precisely
    // so it's programmatically focusable without joining the normal tab
    // order (see styles.css for the accompanying outline: none on this
    // specific, non-interactive focus target).
    contentEl.focus();
  }

  function fixRssLinks() {
    // The RSS feed lives on the public API's origin, not this static site's
    // -- config.js sets window.PUBLIC_API_URL before this file runs, so
    // rewrite the placeholder same-origin hrefs from index.html to the real
    // absolute URL rather than leaving them pointing at a 404.
    var rssUrl = apiUrl("/rss.xml");
    var rssLink = document.getElementById("rss-link");
    if (rssLink) {
      rssLink.href = rssUrl;
    }
    var rssAlternate = document.querySelector('link[rel="alternate"][type="application/rss+xml"]');
    if (rssAlternate) {
      rssAlternate.href = rssUrl;
    }
  }

  function initBackToTop() {
    // href="#top" is a no-JS fallback -- left uncaught, the click would set
    // location.hash = "top", firing the hashchange listener below and
    // routing to "Page not found." (parseRoute has no "top" route). Intercept
    // it and scroll instead, without touching the hash at all.
    var link = document.querySelector(".back-to-top");
    if (!link) {
      return;
    }
    link.addEventListener("click", function (event) {
      event.preventDefault();
      window.scrollTo({ top: 0, behavior: "smooth" });
    });
  }

  window.addEventListener("hashchange", route);
  window.addEventListener("DOMContentLoaded", function () {
    fixRssLinks();
    initSiteNotice();
    initBackToTop();
    loadNav();
    route();
  });
})();
