/**
 * BloggerBear public frontend -- plain static single-page app, no build step,
 * no framework, no npm. Hash-based client-side routing:
 *   #/                 -> home / topic list
 *   #/topic/{id}       -> published article list for a topic
 *   #/article/{id}     -> full article view
 *   #/terms            -> Terms of Service (static content, no API call)
 *   #/privacy          -> Privacy Policy (static content, no API call)
 *
 * Talks to the public API at window.PUBLIC_API_URL (e.g.
 * "https://xxxx.execute-api.ap-southeast-2.amazonaws.com"), set by
 * config.js (generated by Terraform at deploy time, not by this file).
 *
 * Rendering uses plain DOM APIs (createElement / textContent) rather than
 * innerHTML with interpolated content, so that article titles/bodies (data
 * from our own backend, but ultimately Bedrock-generated free text) can
 * never be interpreted as markup.
 */

(function () {
  "use strict";

  var navEl = document.getElementById("nav");
  var topicsNavEl = document.getElementById("nav-topics");
  var contentEl = document.getElementById("content");

  function apiUrl(path) {
    return window.PUBLIC_API_URL + path;
  }

  function clearChildren(el) {
    while (el.firstChild) {
      el.removeChild(el.firstChild);
    }
  }

  function el(tag, opts) {
    var node = document.createElement(tag);
    opts = opts || {};
    if (opts.text !== undefined) {
      node.textContent = opts.text;
    }
    if (opts.className) {
      node.className = opts.className;
    }
    if (opts.href !== undefined) {
      node.setAttribute("href", opts.href);
    }
    // Generic escape hatch for anything not worth its own named option
    // above -- primarily aria-*/role/tabindex/type, used throughout the
    // accessibility-focused elements below.
    if (opts.attrs) {
      for (var attrName in opts.attrs) {
        if (Object.prototype.hasOwnProperty.call(opts.attrs, attrName)) {
          node.setAttribute(attrName, opts.attrs[attrName]);
        }
      }
    }
    return node;
  }

  function showMessage(text) {
    clearChildren(contentEl);
    contentEl.appendChild(el("p", { text: text }));
  }

  function fetchJson(url) {
    return fetch(url).then(function (response) {
      if (!response.ok) {
        throw new Error("request failed: " + response.status);
      }
      return response.json();
    });
  }

  // --- Nav ------------------------------------------------------------

  // The site's own sections -- Trending Everywhere, Musings, Stats -- are not
  // topics (nothing to rank, no article_count/researching fields), so they are
  // fixed links in index.html (header #nav-site and the footer) and never come
  // from GET /topics. Trending Everywhere is the cross-topic digest (see
  // trending_digest_handler.py): it links to the same #/topic/{id} route every
  // topic uses, with topic_id "digest".
  var DIGEST_TOPIC_ID = "digest";

  // Keeps the compact header nav usable regardless of how many topics
  // exist: at most this many real topics ever show there, ranked by
  // actual publishing activity rather than declaration order, so a
  // 10-topic account doesn't turn the header into a wall of links. The
  // full, uncapped list still lives on the home page (renderHome).
  var NAV_TOPIC_LIMIT = 3;

  function selectNavTopics(topics) {
    var withArticles = topics
      .filter(function (t) {
        return t.article_count > 0;
      })
      .sort(function (a, b) {
        return (b.latest_published_at || "").localeCompare(a.latest_published_at || "");
      });

    var remaining = NAV_TOPIC_LIMIT - withArticles.length;
    var researchingOnly = [];
    if (remaining > 0) {
      researchingOnly = topics
        .filter(function (t) {
          return t.article_count === 0 && t.researching;
        })
        .sort(function (a, b) {
          return a.name.localeCompare(b.name);
        })
        .slice(0, remaining);
    }

    return withArticles.slice(0, NAV_TOPIC_LIMIT).concat(researchingOnly);
  }

  // Only the topics are built here. The site's own sections (Trending
  // Everywhere, Musings, Stats) are plain links in index.html's #nav-site and
  // footer, so they are there without any JS or API call.
  function renderNav(topics) {
    clearChildren(navEl);
    var navTopics = selectNavTopics(topics);
    navTopics.forEach(function (topic) {
      var link = el("a", { text: topic.name, href: "#/topic/" + encodeURIComponent(topic.topic_id) });
      navEl.appendChild(link);
    });
    // No topics (yet): no empty "Topics" label either. A class, not the `hidden` attribute --
    // this row's space is reserved from first paint (see styles.css), so revealing it here never
    // moves #content/the footer the way toggling `hidden` after the fact used to.
    topicsNavEl.classList.toggle("is-visible", navTopics.length > 0);
  }

  function loadNav() {
    fetchJson(apiUrl("/topics"))
      .then(function (data) {
        renderNav(data.topics || []);
      })
      .catch(function () {
        // Nav failing to load shouldn't block the rest of the page.
        clearChildren(navEl);
        topicsNavEl.classList.remove("is-visible");
      });
  }

  // --- Home -------------------------------------------------------------

  // One h1 per page is the rule this whole app follows (renderArticle,
  // renderArticleList, renderLegalPage each have exactly one) -- on the
  // home route specifically, the hero tagline below is that h1, so the
  // topic list heading right after it is an h2, not a second h1.
  var HOME_TAGLINE =
    "BloggerBear researches its own stories, drafts them, and publishes " +
    "them — with almost no human in the loop.";

  function renderHome(topics) {
    clearChildren(contentEl);

    var hero = el("section", { className: "hero" });
    hero.appendChild(el("h1", { text: "BloggerBear" }));
    hero.appendChild(el("p", { className: "tagline", text: HOME_TAGLINE }));
    hero.appendChild(
      el("a", {
        text: "Find out more",
        href: "about.html",
        className: "find-out-more",
        attrs: { "aria-label": "Find out more about how BloggerBear works" },
      })
    );
    contentEl.appendChild(hero);

    contentEl.appendChild(el("h2", { text: "Topics", className: "section-heading" }));

    if (topics.length === 0) {
      contentEl.appendChild(el("p", { text: "No topics yet." }));
      return;
    }

    var list = el("ul", { className: "topic-list" });
    topics.forEach(function (topic) {
      var item = el("li");
      var link = el("a", { text: topic.name, href: "#/topic/" + encodeURIComponent(topic.topic_id) });
      item.appendChild(link);
      item.appendChild(document.createTextNode(" "));
      item.appendChild(el("span", { className: "topic-article-count", text: topicCountLabel(topic) }));
      list.appendChild(item);
    });
    contentEl.appendChild(list);
  }

  function topicCountLabel(topic) {
    if (topic.article_count > 0) {
      return topic.article_count === 1 ? "(1 article)" : "(" + topic.article_count + " articles)";
    }
    return topic.researching ? "(researching)" : "(no articles yet)";
  }

  function loadHome() {
    showMessage("Loading topics...");
    fetchJson(apiUrl("/topics"))
      .then(function (data) {
        renderHome(data.topics || []);
      })
      .catch(function () {
        showMessage("Could not load topics right now.");
      });
  }

  // --- Topic article list -------------------------------------------------

  function formatDate(isoString) {
    if (!isoString) {
      return "";
    }
    var date = new Date(isoString);
    if (isNaN(date.getTime())) {
      return isoString;
    }
    return date.toLocaleDateString();
  }

  // --- AI lineage display (docs/project-plan.md §11) ------------------------
  //
  // Mirrors lambdas/common/static_pages.py's server-side rendering of the
  // same data (that one is baked into the static article pages at publish
  // time; this is the client-rendered equivalent for the SPA's own views) --
  // keep the wording/format of the two in sync. Any article published
  // before lineage tracking existed comes back with lineage/published_by
  // as explicit nulls, and every helper below renders that as a plainly
  // worded "No data" rather than a blank gap that would look like a bug.

  var PUBLISHED_BY_LABELS = {
    ai_only: "AI only",
    humans: "Humans",
    humans_and_ai: "Humans & AI",
  };

  function formatCount(value) {
    return Number(value || 0).toLocaleString("en-US");
  }

  function publishedByLabel(publishedBy) {
    if (publishedBy === null || publishedBy === undefined) {
      return "No data";
    }
    return PUBLISHED_BY_LABELS[publishedBy] || String(publishedBy);
  }

  // A model's readable name (recorded in the lineage when it was built), else its id.
  function modelName(labels, modelId) {
    return (labels && labels[modelId]) || modelId;
  }

  function modelNames(modelsUsed, labels) {
    return (modelsUsed || []).map(function (modelId) {
      return modelName(labels, modelId);
    });
  }

  // "12 finding(s): X in / Y out" -- the research the article's findings cost.
  function researchText(research) {
    var tracked = Number(research.tracked_findings || 0);
    var untracked = Number(research.untracked_findings || 0);
    if (!tracked) {
      return untracked ? "Not tracked (" + untracked + " finding(s) predate research tracking)" : "No research calls";
    }
    var text = tracked + " finding(s): " + formatCount(research.input_tokens) + " in / " + formatCount(research.output_tokens) + " out";
    if (untracked) {
      text += " (+" + untracked + " earlier finding(s) not tracked)";
    }
    return text;
  }

  function costLabel(costAud, costNote) {
    if (typeof costAud === "number") {
      return "~$" + costAud.toFixed(2) + " AUD";
    }
    return costNote || "No data";
  }

  // The cost figure for the compact one-line summary: the article's total cost (authoring +
  // research) when a research tally exists, since that -- not the authoring-only costAud -- is
  // what a reader means by "the cost" of the article. Mirrors common/static_pages.py's
  // _summary_cost_label exactly, including checking hasResearch itself rather than just whether
  // totalCostAud is a number: a research tally that couldn't be priced still means there IS a
  // real, larger cost than costAud alone, so this says "No data" rather than understating it.
  function summaryCostLabel(hasResearch, costAud, costNote, totalCostAud) {
    if (hasResearch) {
      return typeof totalCostAud === "number" ? "~$" + totalCostAud.toFixed(2) + " AUD" : "No data";
    }
    return costLabel(costAud, costNote);
  }

  // "model: X in / Y out" per model actually used, summed across every call
  // that used it (an article can span more than one model, e.g. a fallback
  // kicking in partway through).
  function perModelTokenText(lineage) {
    var totals = {};
    var order = [];
    ((lineage && lineage.calls) || []).forEach(function (call) {
      var modelId = call.model_id || "";
      if (!Object.prototype.hasOwnProperty.call(totals, modelId)) {
        totals[modelId] = { input: 0, output: 0 };
        order.push(modelId);
      }
      totals[modelId].input += Number(call.input_tokens || 0);
      totals[modelId].output += Number(call.output_tokens || 0);
    });
    if (order.length === 0) {
      return "No data";
    }
    return order
      .map(function (modelId) {
        return modelName(lineage.model_labels, modelId) + ": " + formatCount(totals[modelId].input) + " in / " + formatCount(totals[modelId].output) + " out";
      })
      .join(", ");
  }

  // Compact one-line summary. The article page has the full lineage.calls
  // detail (per-model tokens); the topic listing only gets a slim projection
  // (totals, not per-call -- see public_api_handler.py's _list_articles), so
  // `tokensText` is passed in by whichever caller has the right level of
  // detail rather than computed here.
  function lineageSummaryText(modelsUsed, tokensText, publishedBy, costArgs, hasLineage, modelLabels) {
    if (!hasLineage && (publishedBy === null || publishedBy === undefined)) {
      return "No data";
    }
    var models = modelsUsed && modelsUsed.length > 0 ? modelNames(modelsUsed, modelLabels).join(", ") : "no data";
    var costText = hasLineage
      ? summaryCostLabel(costArgs.hasResearch, costArgs.costAud, costArgs.costNote, costArgs.totalCostAud)
      : "No data";
    return (
      "models [" + models + "] · tokens [" + tokensText + "] · approved by " +
      publishedByLabel(publishedBy) + " · " + costText
    );
  }

  function articleDetailSummaryText(article) {
    var lineage = article.lineage;
    var hasLineage = lineage !== null && lineage !== undefined;
    return lineageSummaryText(
      hasLineage ? lineage.models_used : null,
      hasLineage ? perModelTokenText(lineage) : "no data",
      article.published_by,
      {
        hasResearch: hasLineage && lineage.research !== null && lineage.research !== undefined,
        costAud: hasLineage ? lineage.cost_aud : null,
        costNote: hasLineage ? lineage.cost_note : null,
        totalCostAud: hasLineage ? lineage.total_cost_aud : null,
      },
      hasLineage,
      hasLineage ? lineage.model_labels : null
    );
  }

  function articleListSummaryText(article) {
    var hasLineage = article.models_used !== null && article.models_used !== undefined;
    var tokensText = "no data";
    if (hasLineage && article.total_input_tokens !== null && article.total_input_tokens !== undefined) {
      tokensText = formatCount(article.total_input_tokens) + " in / " + formatCount(article.total_output_tokens) + " out";
    }
    return lineageSummaryText(
      article.models_used,
      tokensText,
      article.published_by,
      {
        hasResearch: !!article.has_research,
        costAud: article.cost_aud,
        costNote: article.cost_note,
        totalCostAud: article.total_cost_aud,
      },
      hasLineage,
      article.model_labels
    );
  }

  // The fuller footer block, same shape as the static page's
  // <footer class="lineage-footer"> -- always rendered, even when empty.
  function renderLineageFooter(lineage, publishedBy, factCheck) {
    var hasLineage = lineage !== null && lineage !== undefined;
    var models = hasLineage && lineage.models_used && lineage.models_used.length > 0
      ? modelNames(lineage.models_used, lineage.model_labels).join(", ")
      : "No data";

    var footer = el("footer", { className: "lineage-footer", attrs: { "aria-label": "Article lineage" } });
    footer.appendChild(el("h2", { text: "Lineage" }));

    var list = el("dl");
    [
      ["Models", models],
      ["Tokens", hasLineage ? perModelTokenText(lineage) : "No data"],
      ["Approved by", publishedByLabel(publishedBy)],
      ["Approx. cost", hasLineage ? costLabel(lineage.cost_aud, lineage.cost_note) : "No data"],
    ].concat(
      // Present only when the fresh-data review was enforced for this article.
      factCheck ? [["Fact check", factCheck]] : []
    ).concat(
      // The research the article's findings cost, tallied hourly and bundled in
      // when the article was written; absent on an article made before that.
      hasLineage && lineage.research
        ? [
            ["Research tokens", researchText(lineage.research)],
            ["Research cost", costLabel(lineage.research.cost_aud, lineage.research.cost_note)],
            ["Total cost", costLabel(lineage.total_cost_aud, null)],
          ]
        : []
    ).forEach(function (row) {
      list.appendChild(el("dt", { text: row[0] }));
      list.appendChild(el("dd", { text: row[1] }));
    });
    footer.appendChild(list);
    return footer;
  }

  // The noun shown for each slot -- mirrors common/static_pages.py's own
  // _EQUIPMENT_SLOT_LABELS, kept as a separate small copy rather than reusing
  // gear.js's SLOT_LABELS: that one only covers what can be *worn* (armor +
  // ring, for the Stats page's doll), not "legacy" (guidance not tied to a
  // worn slot), which equipment_used can carry too.
  var _EQUIPMENT_SLOT_LABELS = {
    helmet: "Helmet",
    chest: "Chest",
    gloves: "Gloves",
    boots: "Boots",
    sword: "Sword",
    shield: "Shield",
    ring: "Ring",
    legacy: "Guidance",
  };

  // Mirrors common/static_pages.py's server-rendered "Equipment used" record (same CSS classes,
  // same plain text -- no icons, no script, no live check). Returns null when the article used no
  // gear, unlike renderLineageFooter (always shown, even as "No data") -- most articles, and every
  // one from before this feature, simply have nothing here, and that's not a gap worth calling out
  // (see static_pages.py's own _render_equipment_footer_html comment).
  function renderEquipmentFooter(equipmentUsed) {
    if (!equipmentUsed || equipmentUsed.length === 0) {
      return null;
    }
    var footer = el("footer", { className: "equipment-footer", attrs: { "aria-label": "Equipment used" } });
    footer.appendChild(el("h2", { text: "Equipment used" }));
    var list = el("ul", { className: "equipment-list" });
    equipmentUsed.forEach(function (piece) {
      var rarity = (piece && piece.rarity) || "common";
      var rarityLabel = BloggerGear.RARITY_LABELS[rarity] || "Common";
      var slotLabel = _EQUIPMENT_SLOT_LABELS[piece && piece.slot] || "Gear";
      var appliesTo = (piece && piece.topic_name) || "Every topic";
      var item = el("li", { className: "equipment-item rarity-" + rarity });
      item.appendChild(
        el("p", { className: "equipment-name", text: (piece && piece.name) || "Unnamed gear" })
      );
      item.appendChild(
        el("p", {
          className: "equipment-meta",
          text: rarityLabel + " · " + slotLabel + " · " + appliesTo,
        })
      );
      if (piece && piece.description) {
        item.appendChild(el("p", { className: "equipment-desc", text: piece.description }));
      }
      list.appendChild(item);
    });
    footer.appendChild(list);
    return footer;
  }

  // --- Articles in the Pipeline --------------------------------------
  //
  var PENDING_REVIEW_LABEL = "Pending review";
  var RESEARCHING_LABEL = "Researching";

  function pipelineItemsFor(activity) {
    if (activity && Array.isArray(activity.pipeline_items) && activity.pipeline_items.length > 0) {
      return activity.pipeline_items.map(function (item) {
        return {
          label: item.label || (item.status === "pending_review" ? PENDING_REVIEW_LABEL : RESEARCHING_LABEL),
          title: item.title || "",
          // Only the researching item has one: when its source was last checked.
          checkedAt: item.checked_at || "",
        };
      });
    }

    var items = [];
    var pendingCount = Number(activity && activity.pending_review_count) || 0;
    for (var i = 0; i < pendingCount; i++) {
      items.push({ label: PENDING_REVIEW_LABEL, title: "" });
    }
    if (activity && activity.researching) {
      items.push({ label: RESEARCHING_LABEL, title: "" });
    }
    return items;
  }

  // "checked 38 min ago" for an ISO timestamp, "" if it can't be read. A time slightly in the
  // future (clock skew between the server and this browser) reads as "just now".
  function formatChecked(isoString) {
    var then = new Date(isoString).getTime();
    if (isNaN(then)) {
      return "";
    }
    var minutes = Math.floor((Date.now() - then) / 60000);
    if (minutes < 1) {
      return "checked just now";
    }
    if (minutes < 60) {
      return "checked " + minutes + " min ago";
    }
    var hours = Math.floor(minutes / 60);
    if (hours < 24) {
      return "checked " + hours + (hours === 1 ? " hour ago" : " hours ago");
    }
    var days = Math.floor(hours / 24);
    return "checked " + days + (days === 1 ? " day ago" : " days ago");
  }

  function renderPipelineSection(items) {
    var box = el("section", { className: "pipeline-box", attrs: { "aria-label": "Articles in the pipeline" } });

    var titleBar = el("div", { className: "pipeline-titlebar" });
    // Decorative spinner -- aria-hidden so a screen reader doesn't
    // announce it at all; the meaningful content is the title bar text
    // and the list items themselves, both left as plain accessible text.
    titleBar.appendChild(el("span", { className: "pipeline-spinner", attrs: { "aria-hidden": "true" } }));
    titleBar.appendChild(el("span", { className: "pipeline-bear", text: "🐻", attrs: { "aria-hidden": "true" } }));
    titleBar.appendChild(el("span", { className: "pipeline-title", text: "Articles in the Pipeline" }));
    box.appendChild(titleBar);

    var list = el("ul", { className: "pipeline-list" });
    items.forEach(function (item) {
      var row = el("li");
      row.appendChild(el("span", { className: "pipeline-status", text: item.label }));
      if (item.title) {
        row.appendChild(el("span", { className: "pipeline-item-title", text: item.title }));
      }
      var checked = item.checkedAt ? formatChecked(item.checkedAt) : "";
      if (checked) {
        // The exact time is in the tooltip; the row says how long ago, so a quiet hour
        // (a check that found nothing new) still reads as alive rather than stuck.
        row.appendChild(
          el("span", {
            className: "pipeline-item-meta",
            text: checked,
            attrs: { title: new Date(item.checkedAt).toLocaleString() },
          })
        );
      }
      list.appendChild(row);
    });
    box.appendChild(list);

    return box;
  }

  function renderArticleList(topicId, articles, activity) {
    clearChildren(contentEl);
    var heading = topicId === DIGEST_TOPIC_ID ? "Trending Everywhere" : topicId;
    contentEl.appendChild(el("h1", { text: heading }));

    var pipelineItems = pipelineItemsFor(activity);
    if (pipelineItems.length > 0) {
      contentEl.appendChild(renderPipelineSection(pipelineItems));
    }

    if (articles.length === 0) {
      // "researching" (docs/project-plan.md §11) distinguishes "nothing
      // published yet, but BloggerBear has started gathering findings for
      // this topic" from a topic with no activity at all -- see
      // GET /topics/{topic_id}/activity in public_api_handler.py. Skip
      // this text entirely when the pipeline box above already conveyed
      // "something's coming" -- showing both would just be redundant.
      if (pipelineItems.length === 0) {
        contentEl.appendChild(el("p", { text: "No published articles yet." }));
      }
      return;
    }

    var list = el("ul", { className: "article-list" });
    articles.forEach(function (article) {
      var item = el("li");
      var link = el("a", {
        text: article.title,
        href: "#/article/" + encodeURIComponent(article.article_id),
      });
      item.appendChild(link);
      item.appendChild(el("span", { className: "article-date", text: " " + formatDate(article.published_at) }));
      item.appendChild(el("div", { className: "lineage-summary", text: articleListSummaryText(article) }));
      list.appendChild(item);
    });
    contentEl.appendChild(list);
  }

  function loadTopicArticles(topicId) {
    showMessage("Loading articles...");
    fetchJson(apiUrl("/articles?topic_id=" + encodeURIComponent(topicId)))
      .then(function (data) {
        var articles = data.articles || [];
        // Always fetch activity now, not just when articles is empty --
        // "Articles in the Pipeline" can appear alongside already-
        // published articles too (e.g. 3 published + 1 pending review is
        // a perfectly normal state), unlike the old researching-only
        // placeholder which only ever mattered on an empty list.
        fetchJson(apiUrl("/topics/" + encodeURIComponent(topicId) + "/activity"))
          .then(function (activity) {
            renderArticleList(topicId, articles, activity);
          })
          .catch(function () {
            renderArticleList(topicId, articles, null);
          });
      })
      .catch(function () {
        showMessage("Could not load articles right now.");
      });
  }

  // --- Musings --------------------------------------------------------

  // A loot drop's card: the gear the musing announces, shown as the musing itself recorded it (a snapshot,
  // so it still reads right if the gear is deleted later). Colour by rarity, like the Stats page; the
  // rarity and slot are always written out too. Text only ever goes in with textContent.
  function lootCard(snapshot) {
    var info = BloggerGear.describe(snapshot, snapshot && snapshot.slot);
    var card = el("div", { className: "loot-card rarity-" + info.rarity });
    var icon = el("div", { className: "loot-icon" });
    icon.appendChild(gearIcon(info.slot, info.rarity));
    card.appendChild(icon);
    var details = el("div", { className: "loot-details" });
    details.appendChild(el("p", { className: "loot-label", text: "Loot drop" }));
    details.appendChild(el("p", { className: "loot-name", text: info.name }));
    details.appendChild(
      el("p", {
        className: "loot-meta",
        text: info.rarityLabel + " \u00b7 " + info.slotLabel + (info.topic ? " \u00b7 " + info.topic : ""),
      })
    );
    details.appendChild(el("p", { className: "loot-desc", text: info.description }));
    card.appendChild(details);
    return card;
  }

  function renderMusings(musings) {
    clearChildren(contentEl);
    contentEl.appendChild(el("h1", { text: "Musings" }));

    if (musings.length === 0) {
      contentEl.appendChild(el("p", { text: "No musings yet -- check back after the next article." }));
      return;
    }

    var list = el("ul", { className: "musings-list" });
    musings.forEach(function (musing) {
      var item = el("li", { className: "musing-item" });

      // A bear feeling the musing's mood, where a bullet point would be. It is decorative (the
      // words below say the same), so it has no alt text. A picture that fails to load, or a mood
      // with none, falls back to the plain bear.
      var mood = window.BloggerMoods.describe(musing.mood);
      var bear = el("img", {
        className: "musing-bear",
        attrs: { src: mood.image, alt: "", width: "56", height: "56" },
      });
      bear.addEventListener("error", function () {
        if (bear.getAttribute("src") !== window.BloggerMoods.FALLBACK_IMAGE) {
          bear.setAttribute("src", window.BloggerMoods.FALLBACK_IMAGE);
        }
      });
      item.appendChild(bear);

      var body = el("div", { className: "musing-body" });
      body.appendChild(el("p", { className: "musing-text", text: musing.text }));
      if (musing.kind === "loot" && musing.gear) {
        body.appendChild(lootCard(musing.gear));
      }
      if (mood.label) {
        body.appendChild(
          el("p", { className: "musing-mood", text: "BloggerBear was feeling " + mood.label })
        );
      }

      var meta = el("p", { className: "musing-meta" });
      meta.appendChild(el("span", { text: formatDate(musing.created_at) }));
      if (musing.article_id) {
        meta.appendChild(document.createTextNode(" · "));
        meta.appendChild(
          el("a", { text: "read the article", href: "#/article/" + encodeURIComponent(musing.article_id) })
        );
      } else if (musing.kind === "loot") {
        meta.appendChild(document.createTextNode(" · "));
        meta.appendChild(el("a", { text: "see what I am wearing", href: "#/stats" }));
      }
      body.appendChild(meta);
      item.appendChild(body);

      list.appendChild(item);
    });
    contentEl.appendChild(list);
  }

  function loadMusings() {
    showMessage("Loading musings...");
    fetchJson(apiUrl("/musings"))
      .then(function (data) {
        renderMusings(data.musings || []);
      })
      .catch(function () {
        showMessage("Could not load musings right now.");
      });
  }

  // --- Stats ------------------------------------------------------------------
  //
  // Public cost/token statistics (docs/project-plan.md §11, PR 5 of 5), from
  // GET /stats -- aggregates only, never article content. One chart: spend
  // per day, the one thing here whose job is "change over time". Everything
  // else is a stat tile or a table -- a table IS the right form for the
  // by-model / by-topic breakdowns (comparison of exact values), and it is
  // also the accessible alternative to the chart, so the chart has a "View
  // as table" twin rather than being the only way to reach its numbers.
  //
  // The chart is built with SVG *presentation attributes* (x/y/width plus
  // classes), never `style` attributes -- the CloudFront CSP is
  // `style-src 'self'` with no 'unsafe-inline' (see infra/modules/static-
  // site), which blocks inline style attributes. Colors come from
  // styles.css classes using the site's own custom properties, so light/
  // dark mode is inherited rather than re-implemented here.

  var SVG_NS = "http://www.w3.org/2000/svg";

  function svgEl(tag, attrs) {
    var node = document.createElementNS(SVG_NS, tag);
    for (var name in attrs || {}) {
      if (Object.prototype.hasOwnProperty.call(attrs, name)) {
        node.setAttribute(name, attrs[name]);
      }
    }
    return node;
  }

  function formatAud(value) {
    if (value === null || value === undefined) {
      return "unpriced";
    }
    if (value === 0) {
      return "$0";
    }
    return "$" + Number(value).toFixed(Math.abs(value) >= 1 ? 2 : 3);
  }

  // Y-axis ticks: like formatAud but without the noisy trailing zero on
  // the 3-decimal small-value form ($0.200 -> $0.20).
  function formatAxisAud(value) {
    if (value === 0) {
      return "$0";
    }
    return "$" + Number(value).toFixed(3).replace(/0$/, "");
  }

  function formatShortDate(isoDate) {
    var date = new Date(isoDate + "T00:00:00Z");
    if (isNaN(date.getTime())) {
      return isoDate;
    }
    return date.toLocaleDateString(undefined, { month: "short", day: "numeric", timeZone: "UTC" });
  }

  // Round a value up to a clean 1/2/5 x 10^n ceiling, for a readable y-axis.
  function niceCeil(value) {
    if (!(value > 0)) {
      return 1;
    }
    var exponent = Math.pow(10, Math.floor(Math.log(value) / Math.LN10));
    var fraction = value / exponent;
    var nice = fraction <= 1 ? 1 : fraction <= 2 ? 2 : fraction <= 5 ? 5 : 10;
    return nice * exponent;
  }

  // A column with a 4px rounded data-end (top) and a square baseline.
  function columnPath(x, y, width, height) {
    var radius = Math.min(4, width / 2, height);
    return (
      "M" + x + "," + (y + height) +
      " V" + (y + radius) +
      " Q" + x + "," + y + " " + (x + radius) + "," + y +
      " H" + (x + width - radius) +
      " Q" + (x + width) + "," + y + " " + (x + width) + "," + (y + radius) +
      " V" + (y + height) + " Z"
    );
  }

  function statTile(label, value, sub) {
    var tile = el("div", { className: "stat-tile" });
    tile.appendChild(el("span", { className: "stat-label", text: label }));
    tile.appendChild(el("span", { className: "stat-value", text: value }));
    if (sub) {
      tile.appendChild(el("span", { className: "stat-sub", text: sub }));
    }
    return tile;
  }

  // rows: arrays of strings, first column left-aligned, the rest numeric.
  function statsTable(headers, rows) {
    var wrap = el("div", { className: "stats-table-wrap" });
    var table = el("table", { className: "stats-table" });
    var headRow = el("tr");
    headers.forEach(function (header, index) {
      headRow.appendChild(
        el("th", { text: header, className: index === 0 ? "" : "num", attrs: { scope: "col" } })
      );
    });
    table.appendChild(el("thead")).appendChild(headRow);
    var body = el("tbody");
    rows.forEach(function (row) {
      var tr = el("tr");
      row.forEach(function (cell, index) {
        tr.appendChild(el("td", { text: cell, className: index === 0 ? "" : "num" }));
      });
      body.appendChild(tr);
    });
    table.appendChild(body);
    wrap.appendChild(table);
    return wrap;
  }

  function articleCountText(count) {
    return count === 1 ? "1 article" : count + " articles";
  }

  // --- Weekly/Total Stats: everything from GET /stats's `weekly` and `historic` --------------
  //
  // Observability enhancement, PR 4. Both are the same shape (common/stats_tracking.py's
  // public_view): a fixed set of categories the app doesn't need to discover, so a table with
  // a label per category is enough -- no "no data yet" branch like By Model/By Topic need,
  // since every category is always present, calls or not.

  var OBSERVABILITY_CATEGORY_LABELS = {
    articles: "Articles (all stages)",
    musings: "Musings",
    weekly_reflection: "Weekly reflection",
    gear_identity: "Gear naming",
    comment_screening: "Comment screening",
  };

  function formatHours(value) {
    var hours = Number(value || 0);
    var rounded = Math.round(hours * 10) / 10;
    return rounded + (rounded === 1 ? " hr" : " hrs");
  }

  function categoryRow(category) {
    var cost = formatAud(category.cost_aud);
    if (category.cost_aud !== null && category.unpriced > 0) {
      cost += " (+" + category.unpriced + " unpriced)";
    }
    return [
      OBSERVABILITY_CATEGORY_LABELS[category.category] || category.category,
      formatCount(category.calls),
      formatCount(category.input_tokens),
      formatCount(category.output_tokens),
      cost,
    ];
  }

  // `apiGatewayNote` distinguishes Weekly Stats' rolling-30-day reading from Total Stats'
  // reuse of that same reading (a snapshot, never summed across weeks -- see this section's
  // own note in renderStats).
  function renderObservabilitySection(data, apiGatewayNote) {
    var wrap = el("div", {});
    var tiles = el("div", { className: "stats-tiles" });
    tiles.appendChild(statTile("Feedback given", formatCount(data.feedback_given)));
    tiles.appendChild(
      statTile(
        "Feedback rejected",
        formatCount(data.feedback_rejected_comment),
        "comment failed the content screen"
      )
    );
    tiles.appendChild(statTile("Loot drops", formatCount(data.loot_drops)));
    tiles.appendChild(
      statTile("Pipeline run time", formatHours(data.pipeline_hours), "self-timed, scheduled jobs only")
    );
    if (data.api_gateway_cost_aud_30d !== null && data.api_gateway_cost_aud_30d !== undefined) {
      tiles.appendChild(statTile("API Gateway spend", formatAud(data.api_gateway_cost_aud_30d), apiGatewayNote));
    }
    wrap.appendChild(tiles);
    wrap.appendChild(
      statsTable(
        ["Category", "Calls", "Tokens in", "Tokens out", "Est. cost (AUD)"],
        (data.categories || []).map(categoryRow)
      )
    );
    return wrap;
  }

  // Quick Links: jumps to the page's three top-level sections. A no-JS fallback the same way
  // .back-to-top (index.html) is -- plain in-page anchors, nothing here depends on script.
  function renderQuickLinks() {
    // Same fix as .back-to-top's own initBackToTop, for the same reason: this app hash-routes
    // (parseRoute reads the whole hash as a route, e.g. "#/stats"), so an uncaught click on
    // href="#total-stats-heading" would set location.hash to that, fire the hashchange listener,
    // and route to "Page not found" instead of scrolling. Intercepted here and scrolled instead,
    // without touching the hash at all -- these links only ever exist once this SPA has already
    // rendered with JS, unlike .back-to-top's static, always-present href in index.html, so
    // there's no no-JS case of this href to preserve as a fallback.
    var nav = el("nav", { className: "stats-quicklinks", attrs: { "aria-label": "Jump to a section" } });
    var list = el("ul");
    [
      ["total-stats-heading", "Total Stats"],
      ["weekly-stats-heading", "Weekly Stats"],
      ["gear-heading", "Gear"],
    ].forEach(function (pair) {
      var targetId = pair[0];
      var li = el("li");
      var link = el("a", { text: pair[1], href: "#" + targetId });
      link.addEventListener("click", function (event) {
        event.preventDefault();
        var target = document.getElementById(targetId);
        if (target) {
          target.scrollIntoView({ behavior: "smooth" });
        }
      });
      li.appendChild(link);
      list.appendChild(li);
    });
    nav.appendChild(list);
    return nav;
  }

  function renderSpendChart(daily) {
    // viewBox width follows the container (1 SVG unit = 1 CSS px), so axis
    // text stays a readable 11px instead of scaling down with the chart on
    // a phone; columns get thinner instead. Sized once per render.
    var width = Math.max(320, Math.min(720, contentEl.clientWidth || 640));
    var height = 220;
    var left = 52;
    var right = 8;
    var top = 10;
    var bottom = 26;
    var plotWidth = width - left - right;
    var plotHeight = height - top - bottom;

    var maxCost = 0;
    daily.forEach(function (day) {
      maxCost = Math.max(maxCost, day.cost_aud);
    });
    var ceiling = niceCeil(maxCost);
    var slot = plotWidth / daily.length;
    var barWidth = Math.min(24, slot - 2);

    var wrap = el("div", { className: "stats-chart" });
    var tooltip = el("div", { className: "chart-tooltip", attrs: { role: "status" } });
    tooltip.hidden = true;
    wrap.appendChild(tooltip);

    var svg = svgEl("svg", {
      viewBox: "0 0 " + width + " " + height,
      class: "stats-chart-svg",
      role: "group",
      "aria-label": "Estimated AI spend per day in AUD, last " + daily.length + " days",
    });

    [0, 0.5, 1].forEach(function (fraction) {
      var y = top + plotHeight * (1 - fraction);
      svg.appendChild(svgEl("line", { x1: left, x2: width - right, y1: y, y2: y, class: "stats-grid" }));
      var label = svgEl("text", { x: left - 6, y: y + 4, "text-anchor": "end", class: "stats-axis-label" });
      label.textContent = formatAxisAud(ceiling * fraction);
      svg.appendChild(label);
    });

    [0, Math.floor((daily.length - 1) / 2), daily.length - 1].forEach(function (index) {
      var label = svgEl("text", {
        x: left + index * slot + slot / 2,
        y: height - 8,
        "text-anchor": index === 0 ? "start" : index === daily.length - 1 ? "end" : "middle",
        class: "stats-axis-label",
      });
      label.textContent = formatShortDate(daily[index].date);
      svg.appendChild(label);
    });

    function showTooltip(day, target, barTopY) {
      clearChildren(tooltip);
      tooltip.appendChild(el("strong", { text: formatAud(day.cost_aud) + " AUD" }));
      tooltip.appendChild(
        el("span", { text: formatShortDate(day.date) + " · " + articleCountText(day.articles) })
      );
      tooltip.hidden = false;
      var wrapBox = wrap.getBoundingClientRect();
      var targetBox = target.getBoundingClientRect();
      var half = tooltip.offsetWidth / 2;
      var center = targetBox.left + targetBox.width / 2 - wrapBox.left;
      tooltip.style.left = Math.min(Math.max(center, half), wrapBox.width - half) + "px";
      // Sit just above the hovered bar (SVG units -> rendered pixels) so the
      // tooltip never covers the mark it describes; clamp inside the chart.
      var scale = wrapBox.width / width;
      tooltip.style.top = Math.max(0, barTopY * scale - tooltip.offsetHeight - 6) + "px";
    }

    function hideTooltip() {
      tooltip.hidden = true;
    }

    daily.forEach(function (day, index) {
      var group = svgEl("g", { class: "stats-day" });
      var barHeight = (day.cost_aud / ceiling) * plotHeight;
      var barTopY = top + plotHeight - barHeight;
      if (barHeight > 0) {
        group.appendChild(
          svgEl("path", {
            d: columnPath(
              left + index * slot + (slot - barWidth) / 2,
              top + plotHeight - barHeight,
              barWidth,
              barHeight
            ),
            class: "stats-bar",
          })
        );
      }
      // Full-height hit target, wider than the mark itself (the 2px gap
      // between bars included), so hover/focus never needs pixel aim.
      var hit = svgEl("rect", {
        x: left + index * slot,
        y: top,
        width: slot,
        height: plotHeight,
        class: "stats-hit",
        tabindex: "0",
        "aria-label":
          formatShortDate(day.date) + ": " + formatAud(day.cost_aud) + " AUD, " + articleCountText(day.articles),
      });
      hit.addEventListener("pointerenter", function () {
        showTooltip(day, hit, barTopY);
      });
      hit.addEventListener("focus", function () {
        showTooltip(day, hit, barTopY);
      });
      hit.addEventListener("pointerleave", hideTooltip);
      hit.addEventListener("blur", hideTooltip);
      group.appendChild(hit);
      svg.appendChild(group);
    });

    wrap.appendChild(svg);
    return wrap;
  }

  function renderStats(stats) {
    clearChildren(contentEl);
    contentEl.appendChild(el("h1", { text: "Stats" }));
    contentEl.appendChild(renderQuickLinks());

    // --- Total Stats: the article-level detail (always fully live, scanned off Articles) -----
    // plus everything else Bedrock/reader-activity spends, all time (StatsHistory's running
    // total -- Observability enhancement, PR 4).
    contentEl.appendChild(
      el("h2", { text: "Total Stats", className: "section-heading", attrs: { id: "total-stats-heading" } })
    );
    contentEl.appendChild(el("p", { className: "stats-note", text: stats.cost_basis }));

    var totals = stats.totals;
    var spendSub = "AUD, all time";
    if (totals.unpriced_calls > 0) {
      spendSub +=
        " (lower bound: " + totals.unpriced_calls + " unpriced call" + (totals.unpriced_calls === 1 ? "" : "s") + ")";
    }
    var tiles = el("div", { className: "stats-tiles" });
    tiles.appendChild(statTile("Estimated AI spend", formatAud(totals.cost_aud), spendSub));
    tiles.appendChild(
      statTile("Articles drafted", formatCount(totals.articles), formatCount(totals.published) + " published")
    );
    tiles.appendChild(
      statTile(
        "Average cost per article",
        totals.avg_cost_aud === null ? "No data" : formatAud(totals.avg_cost_aud),
        "AUD, articles with cost data"
      )
    );
    tiles.appendChild(
      statTile(
        "Tokens",
        formatCount(totals.input_tokens + totals.output_tokens),
        formatCount(totals.input_tokens) + " in / " + formatCount(totals.output_tokens) + " out"
      )
    );
    // The part of the spend above that was the hourly research tick, bundled into
    // the article each finding fed. Older API responses have no `research` block.
    if (totals.research) {
      tiles.appendChild(
        statTile(
          "Research spend",
          formatAud(totals.research.cost_aud),
          formatCount(totals.research.input_tokens + totals.research.output_tokens) + " tokens over " +
            formatCount(totals.research.calls) + " summaries"
        )
      );
    }
    contentEl.appendChild(tiles);

    var daily = stats.daily || [];
    var activeDays = daily.filter(function (day) {
      return day.cost_aud > 0 || day.articles > 0;
    });
    contentEl.appendChild(
      el("h3", { text: "Estimated spend per day (last " + daily.length + " days)", className: "section-heading" })
    );
    if (activeDays.length === 0) {
      contentEl.appendChild(el("p", { text: "No spend recorded in the last " + daily.length + " days yet." }));
    } else {
      contentEl.appendChild(renderSpendChart(daily));
      var details = el("details", { className: "stats-details" });
      details.appendChild(el("summary", { text: "View as table" }));
      details.appendChild(
        statsTable(
          ["Date", "Articles", "Tokens in", "Tokens out", "Est. cost (AUD)"],
          activeDays.map(function (day) {
            return [
              formatShortDate(day.date),
              formatCount(day.articles),
              formatCount(day.input_tokens),
              formatCount(day.output_tokens),
              formatAud(day.cost_aud),
            ];
          })
        )
      );
      contentEl.appendChild(details);
    }

    contentEl.appendChild(el("h3", { text: "By model", className: "section-heading" }));
    if ((stats.by_model || []).length === 0) {
      contentEl.appendChild(el("p", { text: "No model usage recorded yet." }));
    } else {
      contentEl.appendChild(
        statsTable(
          ["Model", "Calls", "Tokens in", "Tokens out", "Est. cost (AUD)"],
          stats.by_model.map(function (row) {
            var cost = formatAud(row.cost_aud);
            if (row.cost_aud !== null && row.unpriced_calls > 0) {
              cost += " (+" + row.unpriced_calls + " unpriced)";
            }
            return [
              row.display_name,
              formatCount(row.calls),
              formatCount(row.input_tokens),
              formatCount(row.output_tokens),
              cost,
            ];
          })
        )
      );
    }

    contentEl.appendChild(el("h3", { text: "By topic", className: "section-heading" }));
    if ((stats.by_topic || []).length === 0) {
      contentEl.appendChild(el("p", { text: "No topic usage recorded yet." }));
    } else {
      contentEl.appendChild(
        statsTable(
          ["Topic", "Articles", "Tokens in", "Tokens out", "Est. cost (AUD)", "of which research"],
          stats.by_topic.map(function (row) {
            return [
              row.name,
              formatCount(row.articles),
              formatCount(row.input_tokens),
              formatCount(row.output_tokens),
              formatAud(row.cost_aud),
              row.research ? formatAud(row.research.cost_aud) : "No data",
            ];
          })
        )
      );
    }

    var historic = stats.historic || {};
    contentEl.appendChild(
      el("h3", { text: "Other AI spend and activity, all time", className: "section-heading" })
    );
    contentEl.appendChild(el("p", { className: "stats-note", text: historic.note || "" }));
    contentEl.appendChild(renderObservabilitySection(historic, "latest reading, not summed across weeks"));

    // --- Weekly Stats: this week so far (StatsCurrent), resets every Monday -------------------
    contentEl.appendChild(
      el("h2", { text: "Weekly Stats", className: "section-heading", attrs: { id: "weekly-stats-heading" } })
    );
    contentEl.appendChild(
      el("p", { className: "stats-note", text: "This week so far -- resets every Monday." })
    );
    contentEl.appendChild(renderObservabilitySection(stats.weekly || {}, "rolling 30 days"));

    // --- Gear: moved to the bottom now that there's real financial data above it to lead with -
    var gearSection = el("section", { className: "gear", attrs: { "aria-labelledby": "gear-heading" } });
    gearHeading(gearSection);
    gearSection.appendChild(el("p", { text: "Loading..." }));
    contentEl.appendChild(gearSection);
    loadGear(gearSection);

    if (stats.generated_at) {
      contentEl.appendChild(
        el("p", { className: "stats-note", text: "Updated " + new Date(stats.generated_at).toLocaleString() })
      );
    }
  }

  function loadStats() {
    showMessage("Loading stats...");
    fetchJson(apiUrl("/stats"))
      .then(renderStats)
      .catch(function () {
        showMessage("Could not load stats right now.");
      });
  }

  // --- What BloggerBear is wearing (a section of the Stats page) ----------------------------
  //
  // GET /equipment: the six armor slots (or null), the rings, and a backpack COUNT. Approved reader
  // feedback becomes gear; hovering, focusing or tapping a piece shows what it is and the guidance it
  // carries. The backpack is only a number: nothing in it can be looked at.
  //
  // The tooltip follows the WCAG 1.4.13 rules: it appears on hover AND keyboard focus AND tap, stays
  // while the pointer is over it (it sits inside the slot's own wrapper, so there is no gap to cross),
  // and Escape dismisses it. The slot is a real <button>; its tooltip is also its aria-describedby, so a
  // screen reader hears the same thing without having to open anything. The same facts are in a list
  // below ("View the gear as a list"), so nothing depends on hovering.
  //
  // Colours (rarity, condition) come from CSS classes. The bar is an SVG rect with a width attribute --
  // never a style attribute, which the CSP blocks. Text is always set with textContent.

  var gearOpen = null; // { wrap, tip, pinned } for the one tooltip that is showing

  function closeGearTip() {
    if (gearOpen) {
      gearOpen.tip.hidden = true;
      gearOpen.wrap.classList.remove("is-open");
      gearOpen = null;
    }
  }

  function openGearTip(wrap, tip, pinned) {
    var keepPinned = !!(gearOpen && gearOpen.wrap === wrap && gearOpen.pinned);
    if (gearOpen && gearOpen.wrap !== wrap) {
      closeGearTip();
    }
    tip.hidden = false;
    wrap.classList.add("is-open");
    gearOpen = { wrap: wrap, tip: tip, pinned: !!pinned || keepPinned };
  }

  var gearListenersBound = false;

  function bindGearDismissers() {
    if (gearListenersBound) {
      return;
    }
    gearListenersBound = true;
    document.addEventListener("keydown", function (event) {
      // Escape puts it away without moving focus (moving it would just open it again).
      if (event.key === "Escape" && gearOpen) {
        closeGearTip();
      }
    });
    // A tap or click anywhere else puts it away (on a phone this is how you close one).
    document.addEventListener("click", function (event) {
      if (gearOpen && !gearOpen.wrap.contains(event.target)) {
        closeGearTip();
      }
    });
  }

  function drawIcon(spec, className) {
    var svg = svgEl("svg", {
      viewBox: spec.viewBox,
      class: className,
      "aria-hidden": "true",
      focusable: "false",
    });
    spec.nodes.forEach(function (node) {
      svg.appendChild(svgEl(node.tag, node.attrs));
    });
    return svg;
  }

  function gearIcon(slot, rarity, extraClass) {
    return drawIcon(BloggerGear.iconSpec(slot, rarity), "gear-icon" + (extraClass ? " " + extraClass : ""));
  }

  // The condition bar: a track and a fill, the fill's width the percentage. Decoration only (the
  // percentage is always written beside it).
  function gearBar(condition) {
    var svg = svgEl("svg", { viewBox: "0 0 100 6", class: "gear-bar", "aria-hidden": "true", focusable: "false" });
    svg.appendChild(svgEl("rect", { class: "gear-bar-track", x: 0, y: 0, width: 100, height: 6, rx: 3 }));
    if (condition.percent !== null && condition.percent > 0) {
      svg.appendChild(
        svgEl("rect", { class: "gear-bar-fill dur-" + condition.tier, x: 0, y: 0, width: condition.percent, height: 6, rx: 3 })
      );
    }
    return svg;
  }

  function gearTipRow(term, valueNode) {
    var row = el("div", { className: "gear-tip-row" });
    row.appendChild(el("dt", { text: term }));
    var definition = el("dd");
    definition.appendChild(valueNode);
    row.appendChild(definition);
    return row;
  }

  function gearTooltip(info, tipId) {
    var tip = el("div", { className: "gear-tip rarity-" + info.rarity, attrs: { role: "tooltip", id: tipId } });
    tip.hidden = true;
    tip.appendChild(el("p", { className: "gear-tip-name", text: info.name }));
    tip.appendChild(el("p", { className: "gear-tip-rarity", text: info.rarityLabel }));
    tip.appendChild(el("p", { className: "gear-tip-desc", text: info.description }));
    var facts = el("dl", { className: "gear-tip-facts" });
    facts.appendChild(gearTipRow("Slot", document.createTextNode(info.slotLabel)));
    facts.appendChild(
      gearTipRow(info.topic ? "Topic" : "Applies to", document.createTextNode(info.topic || "Every topic"))
    );
    var condition = el("span", { className: "gear-tip-condition dur-" + info.durability.tier });
    condition.appendChild(el("strong", { text: info.durability.text }));
    condition.appendChild(document.createTextNode(" · " + info.durability.label));
    var conditionCell = el("span");
    conditionCell.appendChild(condition);
    conditionCell.appendChild(gearBar(info.durability));
    facts.appendChild(gearTipRow("Durability", conditionCell));
    tip.appendChild(facts);
    return tip;
  }

  function emptyGearSlot(slot) {
    var wrap = el("div", { className: "gear-slot gear-slot-" + slot + " gear-empty" });
    var box = el("div", { className: "gear-slot-box" });
    box.appendChild(gearIcon(slot, null, "gear-icon-empty"));
    wrap.appendChild(box);
    wrap.appendChild(el("span", { className: "gear-slot-label", text: BloggerGear.SLOT_LABELS[slot] }));
    wrap.appendChild(el("span", { className: "gear-slot-sub", text: "Empty" }));
    return wrap;
  }

  function wornGearSlot(item, slot, tipId, align) {
    var info = BloggerGear.describe(item, slot);
    var wrap = el("div", { className: "gear-slot gear-slot-" + slot + " gear-worn gear-align-" + align });
    var button = el("button", {
      className: "gear-slot-box rarity-" + info.rarity,
      attrs: { type: "button", "aria-describedby": tipId, "aria-label": info.accessibleName },
    });
    button.appendChild(gearIcon(slot, info.rarity));
    button.appendChild(gearBar(info.durability));
    wrap.appendChild(button);
    wrap.appendChild(el("span", { className: "gear-slot-label", text: info.slotLabel }));
    if (info.topic) {
      wrap.appendChild(el("span", { className: "gear-slot-sub", text: info.topic }));
    }
    var tip = gearTooltip(info, tipId);
    wrap.appendChild(tip);

    // Hover (a mouse only: a touch "hover" is just the start of a tap, which click handles).
    wrap.addEventListener("pointerenter", function (event) {
      if (event.pointerType === "mouse") {
        openGearTip(wrap, tip, false);
      }
    });
    wrap.addEventListener("pointerleave", function (event) {
      if (event.pointerType === "mouse" && gearOpen && gearOpen.wrap === wrap && !gearOpen.pinned) {
        closeGearTip();
      }
    });
    // Keyboard focus.
    wrap.addEventListener("focusin", function () {
      openGearTip(wrap, tip, false);
    });
    wrap.addEventListener("focusout", function (event) {
      if (!wrap.contains(event.relatedTarget) && gearOpen && gearOpen.wrap === wrap && !gearOpen.pinned) {
        closeGearTip();
      }
    });
    // A click, a tap, or Enter / Space: hold it open, or put it away if it is already held.
    button.addEventListener("click", function () {
      if (gearOpen && gearOpen.wrap === wrap && gearOpen.pinned) {
        closeGearTip();
      } else {
        openGearTip(wrap, tip, true);
      }
    });
    return { node: wrap, info: info };
  }

  function gearLegend() {
    var list = el("ul", { className: "gear-legend", attrs: { "aria-label": "Rarity colours" } });
    BloggerGear.RARITIES.forEach(function (rarity) {
      list.appendChild(
        el("li", { className: "gear-legend-item rarity-" + rarity, text: BloggerGear.RARITY_LABELS[rarity] })
      );
    });
    return list;
  }

  function gearList(entries) {
    var details = el("details", { className: "stats-details" });
    details.appendChild(el("summary", { text: "View the gear as a list" }));
    var list = el("ul", { className: "gear-list" });
    entries.forEach(function (info) {
      var item = el("li");
      item.appendChild(el("strong", { className: "rarity-" + info.rarity, text: info.name }));
      item.appendChild(
        document.createTextNode(
          " — " + info.rarityLabel + ", " + info.slotLabel + ", " + info.scope.toLowerCase() +
            ", durability " + info.durability.text + " (" + info.durability.label.toLowerCase() + ")."
        )
      );
      item.appendChild(el("span", { className: "gear-list-desc", text: info.description }));
      list.appendChild(item);
    });
    details.appendChild(list);
    return details;
  }

  function gearHeading(section) {
    section.appendChild(
      el("h2", { text: "What BloggerBear is wearing", className: "section-heading", attrs: { id: "gear-heading" } })
    );
  }

  function renderGear(section, gear) {
    clearChildren(section);
    gearHeading(section);
    section.appendChild(
      el("p", {
        className: "stats-note",
        text:
          "Approved reader feedback becomes gear, and the gear is the guidance BloggerBear follows when it writes. " +
          "Hover over, focus on or tap a piece to see what it says. A thumbs-down on an article wears its gear down and " +
          "a thumbs-up repairs it; gear that wears out is taken off.",
      })
    );

    var armor = (gear && gear.armor) || {};
    var rings = (gear && gear.rings) || [];
    var entries = [];
    var doll = el("div", { className: "gear-doll" });
    // Which side of the slot the tooltip lines up with, so it never runs off the page.
    var aligns = { helmet: "left", chest: "left", gloves: "left", sword: "right", shield: "right", boots: "right" };
    BloggerGear.ARMOR_SLOTS.forEach(function (slot) {
      if (armor[slot]) {
        var worn = wornGearSlot(armor[slot], slot, "gear-tip-" + slot, aligns[slot]);
        entries.push(worn.info);
        doll.appendChild(worn.node);
      } else {
        doll.appendChild(emptyGearSlot(slot));
      }
    });
    var bear = el("div", { className: "gear-bear" });
    bear.appendChild(el("img", { attrs: { src: "bears/default.svg", alt: "", width: 160, height: 160 } }));
    doll.appendChild(bear);
    section.appendChild(doll);

    var ringRow = el("div", { className: "gear-rings" });
    rings.forEach(function (ring, index) {
      var align = index === 0 ? "left" : index === rings.length - 1 && rings.length > 2 ? "right" : "center";
      var worn = wornGearSlot(ring, "ring", "gear-tip-ring-" + index, align);
      entries.push(worn.info);
      ringRow.appendChild(worn.node);
    });
    if (rings.length === 0) {
      ringRow.appendChild(
        el("p", { className: "stats-note", text: "No rings are worn: no topic has guidance of its own right now." })
      );
    }
    section.appendChild(ringRow);

    var bag = el("p", { className: "gear-bag" });
    bag.appendChild(drawIcon(BloggerGear.BAG, "gear-icon gear-icon-bag"));
    bag.appendChild(el("span", { text: BloggerGear.backpackText(gear && gear.backpack_count) }));
    section.appendChild(bag);

    section.appendChild(gearLegend());
    if (entries.length > 0) {
      section.appendChild(gearList(entries));
    }
    bindGearDismissers();
  }

  function loadGear(section) {
    fetchJson(apiUrl("/equipment"))
      .then(function (gear) {
        renderGear(section, gear);
      })
      .catch(function () {
        clearChildren(section);
        gearHeading(section);
        section.appendChild(el("p", { text: "Could not load the gear right now." }));
      });
  }

  // --- Article body (markdown) ---------------------------------------------

  // The article title is the page's one <h1>, so a "#" in the body is an <h2>
  // (markdown.js shifts every heading down by this much): screen-reader users
  // navigate by heading level, and a second <h1> would break that outline.
  var BODY_HEADING_OFFSET = 1;

  function renderInline(parent, nodes) {
    nodes.forEach(function (node) {
      if (node.type === "text") {
        parent.appendChild(document.createTextNode(node.text));
      } else if (node.type === "code") {
        parent.appendChild(el("code", { text: node.text }));
      } else if (node.type === "strong" || node.type === "em") {
        var emphasis = el(node.type);
        renderInline(emphasis, node.children);
        parent.appendChild(emphasis);
      } else if (node.type === "link") {
        // markdown.js only emits http(s) links. Off-site, so the same
        // treatment as the Sources list: new context stays out of this tab's
        // opener, and the accessible name says it leaves the site.
        var link = el("a", {
          href: node.href,
          attrs: { rel: "noopener noreferrer", target: "_blank" },
        });
        renderInline(link, node.children);
        parent.appendChild(link);
      }
    });
  }

  function renderBlocks(parent, blocks) {
    blocks.forEach(function (block) {
      if (block.type === "heading") {
        var heading = el("h" + block.level);
        renderInline(heading, block.children);
        parent.appendChild(heading);
      } else if (block.type === "paragraph") {
        var paragraph = el("p");
        renderInline(paragraph, block.children);
        parent.appendChild(paragraph);
      } else if (block.type === "list") {
        var list = el(block.ordered ? "ol" : "ul");
        if (block.ordered && block.start !== null && block.start !== 1) {
          list.setAttribute("start", String(block.start));
        }
        block.items.forEach(function (item) {
          var li = el("li");
          renderInline(li, item.inline);
          renderBlocks(li, item.blocks);
          list.appendChild(li);
        });
        parent.appendChild(list);
      } else if (block.type === "blockquote") {
        var quote = el("blockquote");
        renderBlocks(quote, block.children);
        parent.appendChild(quote);
      } else if (block.type === "code") {
        var pre = el("pre");
        pre.appendChild(el("code", { text: block.text }));
        parent.appendChild(pre);
      } else if (block.type === "hr") {
        parent.appendChild(el("hr"));
      } else if (block.type === "table") {
        parent.appendChild(renderTable(block));
      }
    });
  }

  function renderTable(block) {
    // A wrapper that scrolls sideways: a wide table on a phone must not
    // stretch the whole page (there is a "no horizontal page scroll" rule).
    var wrap = el("div", { className: "table-scroll" });
    var table = el("table");
    var headRow = el("tr");
    block.head.forEach(function (cell, index) {
      var th = el("th", {
        className: block.aligns[index] ? "align-" + block.aligns[index] : "",
        attrs: { scope: "col" },
      });
      renderInline(th, cell);
      headRow.appendChild(th);
    });
    var thead = el("thead");
    thead.appendChild(headRow);
    table.appendChild(thead);
    var tbody = el("tbody");
    block.rows.forEach(function (row) {
      var tr = el("tr");
      row.forEach(function (cell, index) {
        var td = el("td", { className: block.aligns[index] ? "align-" + block.aligns[index] : "" });
        renderInline(td, cell);
        tr.appendChild(td);
      });
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    wrap.appendChild(table);
    return wrap;
  }

  function renderMarkdownInto(parent, markdown) {
    var blocks = window.BloggerMarkdown.parse(markdown, { headingOffset: BODY_HEADING_OFFSET });
    renderBlocks(parent, blocks);
  }

  // --- Article detail -----------------------------------------------------

  function renderArticle(article) {
    clearChildren(contentEl);

    contentEl.appendChild(el("h1", { text: article.title }));

    var meta = el("p", { className: "article-meta" });
    meta.appendChild(el("span", { text: "Published " + formatDate(article.published_at) }));
    meta.appendChild(document.createTextNode(" · "));
    meta.appendChild(el("span", { className: "view-count", text: article.view_count + " views" }));
    contentEl.appendChild(meta);
    contentEl.appendChild(el("p", { className: "lineage-summary", text: articleDetailSummaryText(article) }));

    var body = el("div", { className: "article-body" });
    renderMarkdownInto(body, article.body);
    contentEl.appendChild(body);

    var sourceRefs = article.source_refs || [];
    if (sourceRefs.length > 0) {
      var sourcesSection = el("footer", { className: "sources-footer" });
      sourcesSection.appendChild(el("h2", { text: "Sources" }));
      var sourcesList = el("ul");
      sourcesSection.setAttribute("aria-label", "Sources");
      sourceRefs.forEach(function (ref) {
        var item = el("li");
        var refLabel = ref.title || ref.url;
        // These links leave the site to third-party domains (the
        // original source page a Finding was based on) -- calling that
        // out in the accessible name, not just visually, matches how a
        // sighted user infers "this isn't part of this site" from the
        // "Sources" heading above it.
        var link = el("a", {
          text: refLabel,
          href: ref.url,
          attrs: { "aria-label": refLabel + " (external source link)" },
        });
        item.appendChild(link);
        item.appendChild(
          document.createTextNode(" (accessed " + formatDate(ref.accessed_at) + ")")
        );
        sourcesList.appendChild(item);
      });
      sourcesSection.appendChild(sourcesList);
      contentEl.appendChild(sourcesSection);
    }

    // Side by side on a wide screen, the equipment record flexing below lineage on a narrow one
    // (see styles.css's own comment on .article-footers) -- same wrapper common/static_pages.py's
    // static article page already uses for the two footers, just built as DOM nodes here.
    var footers = el("div", { className: "article-footers" });
    footers.appendChild(renderLineageFooter(article.lineage, article.published_by, article.fact_check));
    var equipmentFooter = renderEquipmentFooter(article.equipment_used);
    if (equipmentFooter) {
      footers.appendChild(equipmentFooter);
    }
    contentEl.appendChild(footers);
    contentEl.appendChild(renderFeedback(article.article_id));
  }

  // --- Feedback -----------------------------------------------------------

  // Matches MAX_COMMENT_CHARS in lambdas/common/comment_screening.py.
  var MAX_COMMENT_LENGTH = 1000;

  // When BloggerBear isn't taking feedback (an article that is locked or full, a pause, the daily
  // limit, the rate limit) the form is replaced by this, with the reason. The API decides; this
  // only shows it (common/feedback_limits.py).
  function formatRetry(isoString) {
    var then = new Date(isoString).getTime();
    if (!isoString || isNaN(then)) {
      return "";
    }
    var minutes = Math.ceil((then - Date.now()) / 60000);
    if (minutes <= 1) {
      return "Try again in a moment.";
    }
    if (minutes < 60) {
      return "Try again in about " + minutes + " minutes.";
    }
    var hours = Math.round(minutes / 60);
    return "Try again in about " + hours + (hours === 1 ? " hour." : " hours.");
  }

  function renderFeedbackClosed(status) {
    var box = el("div", { className: "feedback-closed", attrs: { role: "status" } });
    var headline = el("p", { className: "feedback-closed-headline" });
    headline.appendChild(document.createTextNode("Hold your Paws! "));
    headline.appendChild(el("span", { text: "\uD83D\uDC3E", attrs: { "aria-hidden": "true" } }));
    box.appendChild(headline);
    box.appendChild(el("p", { text: "BloggerBear is not taking feedback right now." }));
    box.appendChild(
      el("p", {
        className: "feedback-closed-reason",
        text: "Reason: " + ((status && status.label) || "Feedback is unavailable right now"),
      })
    );
    var retry = status ? formatRetry(status.retry_at) : "";
    if (retry) {
      box.appendChild(el("p", { className: "feedback-closed-retry", text: retry }));
    }
    // Something to do while feedback is closed (see tummy.js). Not when the site is simply broken
    // ("unavailable"): a toy would be flippant. It is decoration, so it can never get in the way.
    if (window.BloggerTummy && (!status || status.reason !== "unavailable")) {
      try {
        window.BloggerTummy.mount(box);
      } catch (ignore) {
        // decoration only
      }
    }
    return box;
  }

  function renderFeedback(articleId) {
    var section = el("section", { className: "feedback" });
    section.appendChild(el("h2", { text: "Feedback" }));
    // Holds the form or, when feedback is closed, the reason instead. Empty until the API has
    // said which, so a closed article never flashes a form.
    var holder = el("div", { className: "feedback-holder" });
    section.appendChild(holder);

    // aria-live="polite" + aria-atomic="true": screen readers announce
    // "Submitting...", then "Thanks for your feedback!" (or the error
    // message) as they appear, the same way a sighted user sees the
    // status line update -- without this, those changes are silent to
    // assistive tech, since nothing else on the page moves focus or
    // otherwise signals that anything happened.
    var status = el("p", {
      className: "feedback-status",
      attrs: { "aria-live": "polite", "aria-atomic": "true" },
    });

    var upButton = el("button", {
      text: "Upvote",
      attrs: { type: "button", "aria-label": "Upvote this article" },
    });
    var downButton = el("button", {
      text: "Downvote",
      attrs: { type: "button", "aria-label": "Downvote this article" },
    });

    var commentHintId = "feedback-comment-hint-" + encodeURIComponent(articleId);
    var commentHint = el("p", {
      className: "feedback-comment-hint",
      text:
        "Keep it civil and about the article, and please don't include your name, contact " +
        "details, or any other personal information. A comment that doesn't fit isn't accepted, and nothing is submitted with it.",
      attrs: { id: commentHintId },
    });

    var commentLabel = el("label", { text: "Comment (optional)" });
    var commentInput = document.createElement("textarea");
    commentInput.setAttribute("rows", "3");
    // The API drops a longer comment (MAX_COMMENT_CHARS in common/comment_screening.py).
    commentInput.setAttribute("maxlength", String(MAX_COMMENT_LENGTH));
    // Announces the same "don't share personal info" reminder from the
    // Privacy Policy to screen-reader users at the point they're about
    // to type a comment, not just on a separate page they may never
    // visit.
    commentInput.setAttribute("aria-describedby", commentHintId);
    commentLabel.appendChild(document.createElement("br"));
    commentLabel.appendChild(commentInput);

    // A decoy field no person sees or reaches. It looks like any other optional field: no class,
    // no telling name, and a label that says nothing about what it is for. The wrapper is hidden by
    // the standard `hidden` attribute (normalize.css hides it, so there is no rule of ours that
    // points at it, and it stays hidden if our stylesheet fails), and aria-hidden takes the whole
    // subtree out of the accessibility tree for screen readers. tabindex -1 keeps it out of the tab
    // order. A script that fills in every input fills it in, and its submission is discarded.
    var honeypotId = "feedback-referral-" + encodeURIComponent(articleId);
    var honeypotWrap = el("div", { attrs: { hidden: "", "aria-hidden": "true" } });
    honeypotWrap.appendChild(
      el("label", { text: "Referral code (optional)", attrs: { for: honeypotId } })
    );
    var honeypot = el("input", {
      attrs: {
        type: "text",
        id: honeypotId,
        name: "referral_code",
        tabindex: "-1",
        autocomplete: "off",
      },
    });
    honeypotWrap.appendChild(honeypot);

    // The one-use token from the feedback-status call, and when it becomes valid (see verify.js).
    var held = null;

    var buttonRow = el("div", { className: "feedback-buttons" });
    buttonRow.appendChild(upButton);
    buttonRow.appendChild(downButton);

    function setDisabled(disabled) {
      upButton.disabled = disabled;
      downButton.disabled = disabled;
      commentInput.disabled = disabled;
    }

    function submitVote(vote) {
      setDisabled(true);
      status.textContent = "Submitting...";

      var commentValue = commentInput.value.trim();
      var payload = {
        vote: vote,
        comment: commentValue === "" ? null : commentValue,
        referral_code: honeypot.value,
      };

      // The token is good for one submission, so a retry (a comment that wasn't accepted) fetches
      // a new one. It waits out the token's not-before moment, and does the proof of work if the
      // site is busy, then sends. Nothing for the person to do.
      var verification = held;
      held = null;
      window.BloggerVerify.submit({
        apiUrl: apiUrl("").replace(/\/$/, ""),
        articleId: articleId,
        payload: payload,
        verification: verification,
      })
        .then(function (outcome) {
          if (outcome.closed) {
            showClosed(outcome.closed);
            return null;
          }
          return outcome.response;
        })
        .then(function (response) {
          if (response === null) {
            return null; // closed while we were sending: the reason is showing
          }
          if (response.status === 422) {
            // The comment wasn't accepted, so nothing was submitted or counted: the vote wasn't
            // recorded either. Nothing about why. Keep what they typed so they can change it.
            status.textContent =
              "Your comment wasn't accepted, so nothing was submitted. " +
              "Take it out or reword it, then try again.";
            setDisabled(false);
            return null;
          }
          if (!response.ok) {
            // 423 (locked / paused), 429 (a limit) and 503 (the limiter is unavailable) come
            // with the reason: swap the form for it rather than inviting a retry.
            return response
              .json()
              .catch(function () {
                return {};
              })
              .then(function (body) {
                if (body && body.feedback && body.feedback.open === false) {
                  showClosed(body.feedback);
                  return null;
                }
                throw new Error("request failed: " + response.status);
              });
          }
          return response.json().catch(function () {
            return {};
          });
        })
        .then(function (result) {
          if (result === null) {
            return; // closed: the reason is already showing
          }
          status.textContent = "Thanks for your feedback!";
          // Now and then, a treat: a bear to scratch (tummy.js). Decoration, so a problem with it
          // must never look like a problem with the feedback.
          try {
            if (window.BloggerTummy && window.BloggerTummy.shouldOffer(Math.random())) {
              window.BloggerTummy.mount(holder);
            }
          } catch (ignore) {
            // decoration only
          }
        })
        .catch(function () {
          status.textContent = "Could not submit feedback right now. Please try again.";
          setDisabled(false);
        });
    }

    upButton.addEventListener("click", function () {
      submitVote("up");
    });
    downButton.addEventListener("click", function () {
      submitVote("down");
    });

    function showForm() {
      clearChildren(holder);
      holder.appendChild(buttonRow);
      holder.appendChild(commentHint);
      holder.appendChild(commentLabel);
      holder.appendChild(honeypotWrap);
      holder.appendChild(status);
    }

    function showClosed(closedStatus) {
      clearChildren(holder);
      holder.appendChild(renderFeedbackClosed(closedStatus));
    }

    fetchJson(apiUrl("/articles/" + encodeURIComponent(articleId) + "/feedback-status"))
      .then(function (result) {
        if (result && result.open === false) {
          showClosed(result);
        } else {
          held = window.BloggerVerify.hold(result && result.verification);
          showForm();
        }
      })
      .catch(function () {
        // Can't tell: show the form. The API refuses a submission that isn't allowed anyway.
        showForm();
      });
    return section;
  }

  // --- Legal pages (Terms of Service / Privacy Policy) --------------------
  //
  // Static content, not fetched from the API -- rendered with the same
  // el()/DOM-construction helpers as everything else on this page, for
  // consistency (and so this content, like everything else here, never
  // goes through innerHTML). Grounded in what this codebase actually
  // does, not boilerplate: no cookies (verified against both the
  // frontend source and the CloudFront config, which explicitly forwards
  // none), an anonymous per-article view counter, anonymous feedback
  // that is screened (PII, abuse, spam, injection) and dropped, not stored, if it fails (see
  // lambdas/common/comment_screening.py), and infrastructure-level WAF logging
  // that's kept separate from application data (see
  // docs/project-plan.md §7).

  var GITHUB_REPO_URL = "https://github.com/AllainWoodsford/BloggerBear";

  var LEGAL_PAGES = {
    terms: {
      title: "Terms of Service",
      sections: [
        {
          heading: "1. About this site",
          paragraphs: [
            "BloggerBear is a personal, non-commercial portfolio and demonstration project — an experiment in autonomous, AI-assisted research and publishing. Software periodically checks public data sources (currently GitHub Trending, Hacker News, and public cryptocurrency market data), uses an AI model (Amazon Bedrock / Claude) to summarize findings and draft articles, and runs an automated compliance review before anything is published. It is not a commercial product, a news organization, or a registered business.",
          ],
        },
        {
          heading: "2. AI-generated content",
          paragraphs: [
            "Most article content on this site is drafted by an AI model from publicly available source data, then automatically reviewed for compliance before publishing; some drafts are additionally held for manual human review. Despite that review, AI-generated content can still be inaccurate, incomplete, or out of date. Nothing on this site should be treated as professional advice of any kind.",
          ],
        },
        {
          heading: "3. Not financial advice",
          paragraphs: [
            "Any article touching cryptocurrency or other financial/investment topics is generated under a stricter compliance rubric, is always held for manual human review before publishing regardless of how confident the automated review is, and carries a standing notice that it is not financial or investment advice. Nothing on this site is, or should be understood as, a recommendation to buy, sell, or hold any asset. Always do your own research and consult a qualified professional before making financial decisions.",
          ],
        },
        {
          heading: "4. No warranty, availability, or permanence",
          paragraphs: ["This is a hobby/portfolio project, run by a single operator — not a supported product."],
          list: [
            "No uptime, availability, or continuity is guaranteed.",
            "The site, every article on it, and the infrastructure behind it may be taken offline, modified, reset, or permanently deleted at any time, without notice.",
            "The site and its content are provided “as is” and “as available,” without warranties of any kind, express or implied — including accuracy, reliability, merchantability, or fitness for a particular purpose.",
            "The operator is not liable for any loss or damage arising from your use of, or inability to use, this site or its content.",
          ],
        },
        {
          heading: "5. Source material and attribution",
          paragraphs: [
            "Each article's “Sources” links point to the original public pages a piece of research was based on. That source material belongs to its respective owners — BloggerBear doesn't claim ownership of it, and links to it for attribution and further reading.",
          ],
        },
        {
          heading: "6. Anonymous feedback",
          paragraphs: [
            "You may leave anonymous feedback (a thumbs up/down and an optional comment) on published articles — see the Privacy Policy for what happens to that data. By submitting a comment, you agree not to include personal information about yourself or anyone else, and not to submit anything unlawful, abusive, or that infringes someone else's rights. Every comment is screened automatically before it is saved, and is rejected (not saved, not published) if it contains personal information, is abusive, off-topic, spam or unlawful, breaks these terms, tries to instruct or attack the site or the software behind it, or can't be confirmed safe. When a comment is rejected, nothing is submitted: your vote isn't recorded with it, so you can try again without the comment.",
          ],
        },
        {
          heading: "7. Acceptable use",
          paragraphs: [
            "Please don't attempt to abuse, aggressively scrape, disrupt, or gain unauthorized access to this site or the systems behind it. Automated/programmatic use of the public read API and RSS feed is welcome — that's exactly what they're for.",
          ],
        },
        {
          heading: "8. Changes to these terms",
          paragraphs: [
            "Since this is an evolving personal project, these terms may change at any time as the project changes. Continued use of the site after a change means you accept the updated terms.",
          ],
        },
        {
          heading: "9. Contact",
          paragraphs: ["This project is developed in the open. Questions, issues, or takedown requests can be raised via its GitHub repository."],
          link: { text: "github.com/AllainWoodsford/BloggerBear", href: GITHUB_REPO_URL },
        },
      ],
    },
    privacy: {
      title: "Privacy Policy",
      sections: [
        {
          heading: "1. Short version",
          paragraphs: ["This is a small personal project with a deliberately minimal data footprint:"],
          list: [
            "No accounts, no logins, no user profiles.",
            "No cookies.",
            "No advertising or analytics trackers.",
            "No personal information is intentionally collected. If a comment appears to contain any, the whole comment is discarded rather than stored — and you're asked not to include it in the first place (see “Please don't share personal information” below).",
          ],
        },
        {
          heading: "2. What we don't do",
          list: [
            "We do not use cookies. This is verified directly against this site's own source code and infrastructure configuration, not just asserted — the CloudFront distribution in front of this site is explicitly configured to forward none, and the frontend code contains no cookie-setting logic anywhere.",
            "We do not run any third-party analytics, advertising, or tracking scripts.",
            "We do not build profiles of individual visitors, and have no way to identify you from your use of this site.",
          ],
        },
        {
          heading: "3. What we do track: anonymous view counts",
          paragraphs: [
            "Each article has a public, anonymous view counter. Opening an article increments one shared counter for that article by one. This counter is not tied to your browser, device, or identity in any way — it's a running total, the same as a hit counter.",
          ],
        },
        {
          heading: "4. Feedback (votes and comments)",
          paragraphs: [
            "If you leave feedback on an article (a thumbs up/down, with an optional written comment), we store the vote, the comment text (if any, and only if it passed automated screening — see below), and when it was submitted. A comment that fails screening is not stored anywhere, and neither is the vote sent with it. We do not store, log, or associate any of the following with your feedback: your IP address, browser fingerprint, account, or any other identifier. There is no way to trace a piece of feedback back to a specific visitor.",
          ],
        },
        {
          heading: "Please don't share personal information",
          paragraphs: [
            "Any comment you submit goes through a real, if best-effort, attempt to remove obvious personal information automatically — a pattern-matching pass, then a second AI-based review pass — before anything is stored. If that review can't confirm a comment is safe, the comment is dropped and only the vote is kept. But this is an automated filter, not a guarantee. Please don't include your name, email address, phone number, physical address, or any other personal or identifying information — about yourself or anyone else — in a comment. Assume anything you type could end up published.",
          ],
        },
        {
          heading: "5. Infrastructure and security logs",
          paragraphs: [
            "Like effectively every website, the infrastructure this site runs on (a web application firewall in front of the site and its APIs) keeps its own short-term operational logs — the kind that record request metadata, such as source IP address, purely to detect and block abusive traffic. These logs:",
          ],
          list: [
            "live entirely at the infrastructure level, inside the cloud provider's (AWS) own logging systems",
            "are never joined, matched, or cross-referenced with anything you submit through the site (feedback, view counts, or anything else)",
            "are not used to identify or profile visitors",
            "exist only for security and reliability, not analytics",
          ],
        },
        {
          heading: "6. Local storage on your device",
          paragraphs: [
            "This site uses a very small amount of your browser's local storage (localStorage) for exactly one purpose: remembering that you've dismissed the site notice banner, so it doesn't reappear on every visit. That preference lives only in your own browser — it is never sent to us, and clearing your browser data resets it.",
          ],
        },
        {
          heading: "7. Third-party AI processing",
          paragraphs: [
            "Article summaries and drafts are generated using Amazon Bedrock, a cloud AI service. Publicly available source data (trending repositories, news headlines, market prices) is sent to that service to generate content — no visitor data is ever sent there. If you submit a comment, the same service is also used purely to check the comment text (for personal information, abuse, spam and attempts to instruct the software) before deciding whether to store it.",
          ],
        },
        {
          heading: "8. Data retention and deletion",
          paragraphs: [
            "Because this is a disposable, single-operator portfolio project (see the Terms of Service), the infrastructure behind everything described above — including this policy's own hosting — may be reset, rebuilt, or permanently deleted at any time, without notice. There is no guarantee any particular piece of content, feedback, or data will persist.",
          ],
        },
        {
          heading: "9. Changes to this policy",
          paragraphs: ["This policy may change as the project changes. Check back here for the current version."],
        },
        {
          heading: "10. Contact",
          paragraphs: ["Questions about this policy can be raised via the project's GitHub repository."],
          link: { text: "github.com/AllainWoodsford/BloggerBear", href: GITHUB_REPO_URL },
        },
      ],
    },
  };

  function renderLegalPage(pageKey) {
    var page = LEGAL_PAGES[pageKey];
    clearChildren(contentEl);
    contentEl.appendChild(el("h1", { text: page.title }));

    page.sections.forEach(function (section) {
      contentEl.appendChild(el("h2", { text: section.heading }));
      (section.paragraphs || []).forEach(function (paragraph) {
        contentEl.appendChild(el("p", { text: paragraph }));
      });
      if (section.list) {
        var list = el("ul");
        section.list.forEach(function (itemText) {
          var item = el("li", { text: itemText });
          list.appendChild(item);
        });
        contentEl.appendChild(list);
      }
      if (section.link) {
        var linkPara = el("p");
        linkPara.appendChild(el("a", { text: section.link.text, href: section.link.href }));
        contentEl.appendChild(linkPara);
      }
    });
  }

  // --- Site notice ----------------------------------------------------
  //
  // Not a cookie-consent banner (there are no cookies to consent to) --
  // an honest, upfront notice about the anonymous view counting and
  // infrastructure security logging this site does do. Shown once per
  // browser; dismissal is remembered in localStorage, the one and only
  // thing this site stores client-side (see the Privacy Policy, §6).
  //
  // Initial visibility is notice.js's job now, not this one's -- it runs
  // the instant the element exists in the DOM, before first paint, which
  // is what actually fixed the layout shift this used to cause by
  // toggling `hidden` this late (DOMContentLoaded, after the whole script
  // chain). This only wires the dismiss button, which is fine to leave
  // until here: nothing shifts in response to a user's own click.
  var SITE_NOTICE_DISMISSED_KEY = "bloggerbear-site-notice-dismissed";

  function initSiteNotice() {
    var notice = document.getElementById("site-notice");
    var dismissButton = document.getElementById("site-notice-dismiss");
    if (!notice || !dismissButton) {
      return;
    }

    dismissButton.addEventListener("click", function () {
      notice.hidden = true;
      try {
        window.localStorage.setItem(SITE_NOTICE_DISMISSED_KEY, "1");
      } catch (err) {
        /* ignore -- worst case the notice reappears next visit */
      }
    });
  }

  function recordView(articleId) {
    // Best-effort, anonymous view counting -- never blocks rendering and
    // never surfaces an error to the user if it fails.
    fetch(apiUrl("/articles/" + encodeURIComponent(articleId) + "/view"), {
      method: "POST",
    }).catch(function () {
      /* ignore */
    });
  }

  function loadArticle(articleId) {
    showMessage("Loading article...");
    fetchJson(apiUrl("/articles/" + encodeURIComponent(articleId)))
      .then(function (article) {
        renderArticle(article);
        recordView(articleId);
      })
      .catch(function () {
        showMessage("Article not found.");
      });
  }

  // --- Routing --------------------------------------------------------

  function parseRoute(hash) {
    // hash looks like "#/topic/foo" or "#/article/bar" or "#/" or "".
    var path = hash.replace(/^#/, "");
    if (path === "" || path === "/") {
      return { name: "home" };
    }
    var topicMatch = path.match(/^\/topic\/([^/]+)$/);
    if (topicMatch) {
      return { name: "topic", topicId: decodeURIComponent(topicMatch[1]) };
    }
    var articleMatch = path.match(/^\/article\/([^/]+)$/);
    if (articleMatch) {
      return { name: "article", articleId: decodeURIComponent(articleMatch[1]) };
    }
    if (path === "/terms") {
      return { name: "legal", pageKey: "terms" };
    }
    if (path === "/privacy") {
      return { name: "legal", pageKey: "privacy" };
    }
    if (path === "/musings") {
      return { name: "musings" };
    }
    if (path === "/stats") {
      return { name: "stats" };
    }
    return { name: "not-found" };
  }

  function route() {
    var current = parseRoute(window.location.hash);
    if (current.name === "home") {
      loadHome();
    } else if (current.name === "topic") {
      loadTopicArticles(current.topicId);
    } else if (current.name === "article") {
      loadArticle(current.articleId);
    } else if (current.name === "legal") {
      renderLegalPage(current.pageKey);
    } else if (current.name === "musings") {
      loadMusings();
    } else if (current.name === "stats") {
      loadStats();
    } else {
      showMessage("Page not found.");
    }

    // Move focus to the main content landmark on every navigation --
    // standard SPA accessibility practice (WCAG 2.4.3) so keyboard/
    // screen-reader users land on the new content instead of wherever
    // focus happened to be before. #content has tabindex="-1" precisely
    // so it's programmatically focusable without joining the normal tab
    // order (see styles.css for the accompanying outline: none on this
    // specific, non-interactive focus target).
    contentEl.focus();
  }

  function fixRssLinks() {
    // The RSS feed lives on the public API's origin, not this static site's
    // -- config.js sets window.PUBLIC_API_URL before this file runs, so
    // rewrite the placeholder same-origin hrefs from index.html to the real
    // absolute URL rather than leaving them pointing at a 404.
    var rssUrl = apiUrl("/rss.xml");
    var rssLink = document.getElementById("rss-link");
    if (rssLink) {
      rssLink.href = rssUrl;
    }
    var rssAlternate = document.querySelector('link[rel="alternate"][type="application/rss+xml"]');
    if (rssAlternate) {
      rssAlternate.href = rssUrl;
    }
  }

  function initBackToTop() {
    // href="#top" is a no-JS fallback -- left uncaught, the click would set
    // location.hash = "top", firing the hashchange listener below and
    // routing to "Page not found." (parseRoute has no "top" route). Intercept
    // it and scroll instead, without touching the hash at all.
    var link = document.querySelector(".back-to-top");
    if (!link) {
      return;
    }
    link.addEventListener("click", function (event) {
      event.preventDefault();
      window.scrollTo({ top: 0, behavior: "smooth" });
    });
  }

  window.addEventListener("hashchange", route);
  window.addEventListener("DOMContentLoaded", function () {
    fixRssLinks();
    initSiteNotice();
    initBackToTop();
    loadNav();
    route();
  });
})();
