/* The operator's assistant page (ask.html): sign in, ask, hear the answer, see what to do.
   Design: docs/enhancements/alexa-plus-operator-assistant-enhancement.md, sections 3, 5 and 7.

   Sign-in is Cognito's hosted page, authorization code with PKCE (S256). The page makes a random
   verifier and state, keeps them in sessionStorage only for the trip to the hosted page and back,
   and swaps the returned code for an access token at the hosted domain's /oauth2/token.

   THE ACCESS TOKEN LIVES IN A VARIABLE AND NOWHERE ELSE: never in sessionStorage, localStorage or
   a cookie, so closing or reloading the tab signs you out. The conversation is the same: an array
   in this file, sent back as `history` with each question, gone with the tab.

   EVERYTHING THE API RETURNS IS TREATED AS TEXT FROM A STRANGER. It reaches the page through
   createElement and textContent only; nothing in this file parses a string as HTML or code. A
   suggested command is shown for the operator to copy and run in their own terminal: this page
   never runs one, and never reads one aloud. The same holds for the answers to "how do I ...?":
   a command's help in a scrolling block, a command the server built, a template (marked, with its
   <placeholders>) for one that deletes, and the topics as a table.

   Settings come from config.js (generated by Terraform) as window.OPS_ASSISTANT. Where it is
   missing, the page leaves "not available here" showing and does nothing.

   The pure parts are exported for the Node test (lambdas/tests/test_frontend_ask.py). */
(function (root) {
  "use strict";

  // The limits POST /ask enforces (lambdas/ops_agent_handler.py); checked here before sending.
  var QUESTION_MAX_CHARS = 500;
  var HISTORY_MAX_TURNS = 6;
  var TURN_MAX_CHARS = 1000;

  // The only two things this page ever puts in browser storage, and only during sign-in.
  var VERIFIER_KEY = "bloggerbear-ask-pkce-verifier";
  var STATE_KEY = "bloggerbear-ask-pkce-state";

  var BRIEFING_QUESTION = "What needs my attention?";
  var ASK_TIMEOUT_MS = 40000; // API Gateway gives up at 29 s; this is only a backstop
  var HOLD_MS = 400; // a press shorter than this is a tap: start now, stop on the next press
  var CLICK_AFTER_PRESS_MS = 700; // a click this soon after a press belongs to that press
  var SPEECH_CHUNK_CHARS = 180; // Chrome's online voices stop partway through a long utterance
  var SPEECH_DELAY_MS = 80;
  var SPEECH_DONE_FALLBACK_MS = 15000; // the longest say() waits for a browser to report the end // Chrome drops an utterance spoken in the same tick as cancel()
  var TABLE_MAX_ROWS = 50; // what POST /ask sends at most (lambdas/ops_agent/policy.py)
  var TABLE_MAX_COLUMNS = 16;

  var MESSAGES = {
    expired: "Your sign-in has expired. Sign in again to carry on.",
    forbidden: "The assistant is switched off or not available from here.",
    failed: "The assistant could not answer just now. Try again in a moment.",
    network:
      "Could not reach the assistant. Check your connection; it may also be switched off or not available from here.",
    signInFailed: "Sign-in did not complete. Try again.",
    busy: "Asking. An answer can take up to half a minute.",
  };

  // ---------------------------------------------------------------------------------------------
  // Pure functions (no DOM, no globals): what the Node test covers.
  // ---------------------------------------------------------------------------------------------

  function base64Url(bytes) {
    var binary = "";
    for (var i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  }

  function randomString(byteCount, cryptoImpl) {
    var bytes = new Uint8Array(byteCount);
    cryptoImpl.getRandomValues(bytes);
    return base64Url(bytes);
  }

  // RFC 7636 section 4.2: BASE64URL(SHA256(ASCII(verifier))).
  function pkceChallenge(verifier, subtle) {
    var ascii = new Uint8Array(verifier.length);
    for (var i = 0; i < verifier.length; i++) {
      ascii[i] = verifier.charCodeAt(i);
    }
    return subtle.digest("SHA-256", ascii).then(function (digest) {
      return base64Url(new Uint8Array(digest));
    });
  }

  function isText(value) {
    return typeof value === "string" && value.trim() !== "";
  }

  // The settings as config.js gave them, or null unless every one is there and looks right.
  function readConfig(raw) {
    if (!raw || typeof raw !== "object") {
      return null;
    }
    var names = ["askUrl", "hostedUiDomain", "clientId", "scope", "redirectUri"];
    for (var i = 0; i < names.length; i++) {
      if (!isText(raw[names[i]])) {
        return null;
      }
    }
    if (raw.askUrl.indexOf("https://") !== 0 || raw.redirectUri.indexOf("https://") !== 0) {
      return null;
    }
    if (!/^[a-z0-9.-]+$/.test(raw.hostedUiDomain)) {
      return null;
    }
    return {
      askUrl: raw.askUrl,
      hostedUiDomain: raw.hostedUiDomain,
      clientId: raw.clientId,
      scope: raw.scope,
      redirectUri: raw.redirectUri,
      // Optional: which environment's pipeline this page asks about, shown so a command copied
      // from a dev card is not run against production. Anything but a short word is left out.
      environment:
        typeof raw.environment === "string" && /^[a-z][a-z0-9-]{0,15}$/.test(raw.environment) ? raw.environment : "",
    };
  }

  function query(params) {
    return Object.keys(params)
      .map(function (name) {
        return encodeURIComponent(name) + "=" + encodeURIComponent(params[name]);
      })
      .join("&");
  }

  function authorizeUrl(config, state, challenge) {
    return (
      "https://" +
      config.hostedUiDomain +
      "/oauth2/authorize?" +
      query({
        response_type: "code",
        client_id: config.clientId,
        redirect_uri: config.redirectUri,
        scope: config.scope,
        state: state,
        code_challenge: challenge,
        code_challenge_method: "S256",
      })
    );
  }

  function tokenRequestBody(config, code, verifier) {
    return query({
      grant_type: "authorization_code",
      client_id: config.clientId,
      code: code,
      redirect_uri: config.redirectUri,
      code_verifier: verifier,
    });
  }

  function logoutUrl(config) {
    return (
      "https://" +
      config.hostedUiDomain +
      "/logout?" +
      query({ client_id: config.clientId, logout_uri: config.redirectUri })
    );
  }

  // { question } trimmed and within the limit, or { error } to show instead of sending.
  function checkQuestion(text) {
    var question = typeof text === "string" ? text.trim() : "";
    if (!question) {
      return { error: "Say or type a question first." };
    }
    if (question.length > QUESTION_MAX_CHARS) {
      return { error: "That question is too long: " + QUESTION_MAX_CHARS + " characters at most." };
    }
    return { question: question };
  }

  // What goes back as `history`: the last few turns, each cut to the length the API takes. A turn
  // with no text is left out (the API refuses one).
  function buildHistory(turns) {
    var history = [];
    for (var i = 0; i < turns.length; i++) {
      var turn = turns[i];
      if (!turn || (turn.role !== "user" && turn.role !== "assistant") || !isText(turn.text)) {
        continue;
      }
      history.push({ role: turn.role, text: turn.text.trim().slice(0, TURN_MAX_CHARS) });
    }
    return history.slice(-HISTORY_MAX_TURNS);
  }

  // A finding's `where` (and anything else nested) as flat rows to show:
  // [{ label, text, untrusted }]. Everything under a key named "untrusted" is marked, however
  // deep it sits.
  function flattenRows(value, label, untrusted, rows, depth) {
    rows = rows || [];
    depth = depth || 0;
    if (value === null || value === undefined || value === "") {
      return rows;
    }
    if (typeof value !== "object" || Array.isArray(value) || depth >= 4) {
      rows.push({
        label: label || "",
        text: typeof value === "object" ? JSON.stringify(value) : String(value),
        untrusted: !!untrusted,
      });
      return rows;
    }
    Object.keys(value).forEach(function (key) {
      if (key === "untrusted") {
        flattenRows(value[key], label, true, rows, depth + 1);
      } else {
        flattenRows(value[key], label ? label + " " + key : key, untrusted, rows, depth + 1);
      }
    });
    return rows;
  }

  // What kind of card a finding gets: "fix" (a command to copy), "look" (something to look at,
  // no command) or "noticed" (no suggestion at all).
  function cardKind(finding) {
    var suggestion = finding && finding.suggestion;
    if (!suggestion || typeof suggestion !== "object") {
      return "noticed";
    }
    return isText(suggestion.command) ? "fix" : "look";
  }

  // The answer as it is spoken. The agent is told never to say a command; if one turns up in the
  // answer anyway, it is not read out.
  function spokenText(answer, findings) {
    var text = typeof answer === "string" ? answer : "";
    (Array.isArray(findings) ? findings : []).forEach(function (finding) {
      if (cardKind(finding) === "fix") {
        text = text.split(finding.suggestion.command).join("the command on screen");
      }
    });
    return text;
  }

  // A how-to card is the CLI guide's (lambdas/ops_mcp/cli_guide.py): a command's own help, or a
  // command the server built because the operator asked how. It is guidance, not something wrong.
  function isHowTo(finding) {
    return !!finding && finding.kind === "how_to";
  }

  // A template for a command that deletes or takes something down. The server never fills one in:
  // it carries <placeholders>, and the page says so before the operator copies it.
  function isDestructive(finding) {
    return !!finding && finding.destructive === true;
  }

  // The label of a card's first row: what was noticed, or what the operator asked how to do.
  function cardHeading(finding) {
    return isHowTo(finding) ? "How to" : "Noticed";
  }

  // A table from the API as the page will show it: { title, columns, rows } with every cell text
  // and every row as wide as the columns, or null if it is not a table. The API cuts tables to
  // size (lambdas/ops_agent/policy.py); the same limits are held here, for a response that did not
  // come from it.
  function tableModel(table) {
    if (!table || typeof table !== "object" || !Array.isArray(table.columns) || !Array.isArray(table.rows)) {
      return null;
    }
    var columns = table.columns.slice(0, TABLE_MAX_COLUMNS).map(cellText);
    if (!columns.length) {
      return null;
    }
    var rows = [];
    table.rows.slice(0, TABLE_MAX_ROWS).forEach(function (row) {
      if (!Array.isArray(row)) {
        return;
      }
      var cells = [];
      for (var i = 0; i < columns.length; i++) {
        cells.push(cellText(row[i]));
      }
      rows.push(cells);
    });
    return { title: isText(table.title) ? table.title.trim() : "Table", columns: columns, rows: rows };
  }

  function cellText(value) {
    if (typeof value === "number" && isFinite(value)) {
      return String(value);
    }
    return typeof value === "string" ? value : "";
  }

  // ---------------------------------------------------------------------------------------------
  // Building the page's nodes. Each takes the document, so the Node test can hand it a stand-in
  // and see what would be shown. createElement and textContent only: whatever the API sent is
  // text here, never markup.
  // ---------------------------------------------------------------------------------------------

  function makeNode(doc, tag, className, text) {
    var node = doc.createElement(tag);
    if (className) {
      node.className = className;
    }
    if (text !== undefined && text !== null) {
      node.textContent = String(text);
    }
    return node;
  }

  function appendRow(doc, list, label, text, untrusted) {
    list.appendChild(makeNode(doc, "dt", "", label));
    var dd = makeNode(doc, "dd", untrusted ? "ask-untrusted" : "");
    if (untrusted) {
      dd.appendChild(makeNode(doc, "span", "ask-untrusted-mark", "Unverified"));
    }
    dd.appendChild(doc.createTextNode(text));
    list.appendChild(dd);
  }

  // One finding as a card. `onCopy(code, button)` is called when Copy is pressed, with the node
  // that holds the command: what is copied is that node's text, so a template is copied with its
  // placeholders as they are.
  function renderCard(doc, finding, onCopy) {
    var howTo = isHowTo(finding);
    var destructive = isDestructive(finding);
    var card = makeNode(doc, "div", "ask-card" + (howTo ? " ask-card-how-to" : "") + (destructive ? " ask-card-destructive" : ""));
    var kind = cardKind(finding);
    var suggestion = kind === "noticed" ? null : finding.suggestion;

    var top = makeNode(doc, "dl");
    appendRow(doc, top, cardHeading(finding), isText(finding.noticed) ? finding.noticed : "(no description)", false);
    var where = flattenRows(finding.where, "", false);
    flattenRows(finding.untrusted, "", true, where);
    where.forEach(function (row, index) {
      var text = row.label ? row.label + ": " + row.text : row.text;
      appendRow(doc, top, index === 0 ? (howTo ? "About" : "Where") : "", text, row.untrusted);
    });
    if (suggestion && isText(suggestion.action)) {
      appendRow(doc, top, kind === "fix" ? (howTo ? "Next" : "Suggested") : "Look at", suggestion.action, false);
    }
    card.appendChild(top);

    if (destructive) {
      var warning = makeNode(doc, "p", "ask-warning");
      warning.setAttribute("role", "note");
      warning.appendChild(makeNode(doc, "strong", "", "Template, not filled in. "));
      warning.appendChild(
        doc.createTextNode(
          isText(finding.warning)
            ? finding.warning
            : "This command deletes something or takes it down. Replace each <placeholder> yourself before you run it."
        )
      );
      card.appendChild(warning);
    }

    if (kind === "fix") {
      var block = makeNode(doc, "div", "ask-command");
      var pre = makeNode(doc, "pre");
      var code = makeNode(doc, "code", "", suggestion.command);
      pre.appendChild(code);
      var copy = makeNode(doc, "button", "ask-copy", destructive ? "Copy template" : "Copy");
      copy.type = "button";
      copy.setAttribute(
        "aria-label",
        destructive ? "Copy the template, with its placeholders" : howTo ? "Copy the command" : "Copy the suggested command"
      );
      copy.addEventListener("click", function () {
        onCopy(code, copy);
      });
      block.appendChild(pre);
      block.appendChild(copy);
      card.appendChild(block);
    }
    if (suggestion && isText(suggestion.what_it_does)) {
      var bottom = makeNode(doc, "dl");
      appendRow(doc, bottom, "What it does", suggestion.what_it_does, false);
      card.appendChild(bottom);
    }
    if (isText(finding.help)) {
      // The command's own --help, as the CLI prints it: fixed-width, and scrollable (by keyboard
      // too) where it is wider or longer than the card.
      var help = makeNode(doc, "pre", "ask-help", finding.help);
      help.setAttribute("tabindex", "0");
      help.setAttribute("role", "region");
      help.setAttribute("aria-label", "Help text" + (isText(finding.noticed) ? " for " + finding.noticed : ""));
      card.appendChild(help);
    }
    return card;
  }

  // One table as a real <table>, inside a region that scrolls sideways on a narrow screen. Null
  // for something that is not a table.
  function renderTable(doc, table) {
    var model = tableModel(table);
    if (!model) {
      return null;
    }
    var wrap = makeNode(doc, "div", "ask-table-wrap");
    wrap.setAttribute("tabindex", "0");
    wrap.setAttribute("role", "region");
    wrap.setAttribute("aria-label", model.title);
    var node = makeNode(doc, "table", "ask-table");
    node.appendChild(makeNode(doc, "caption", "", model.title));
    var head = makeNode(doc, "thead");
    var headRow = makeNode(doc, "tr");
    model.columns.forEach(function (column) {
      var th = makeNode(doc, "th", "", column);
      th.setAttribute("scope", "col");
      headRow.appendChild(th);
    });
    head.appendChild(headRow);
    node.appendChild(head);
    var body = makeNode(doc, "tbody");
    model.rows.forEach(function (row) {
      var tr = makeNode(doc, "tr");
      row.forEach(function (cell, index) {
        var td = makeNode(doc, index === 0 ? "th" : "td", "", cell);
        if (index === 0) {
          td.setAttribute("scope", "row");
        }
        tr.appendChild(td);
      });
      body.appendChild(tr);
    });
    node.appendChild(body);
    wrap.appendChild(node);
    return wrap;
  }

  // ---------------------------------------------------------------------------------------------
  // The voice: the pure parts. (Recognition and speech themselves are the browser's, below.)
  // ---------------------------------------------------------------------------------------------

  // The language tag for recognition and speech: the browser's own English tag ("en-AU"), else
  // "en-US". Never <html lang>'s bare "en": Safari's recognition wants a full tag.
  function speechLang(navigatorLanguage) {
    var tag = typeof navigatorLanguage === "string" ? navigatorLanguage.trim() : "";
    return /^en-[A-Za-z]{2,3}$/.test(tag) ? tag : "en-US";
  }

  // An answer as the pieces it is spoken in: whole sentences, joined while they fit in maxChars,
  // and a sentence longer than that cut at its last space that fits. Chrome's online voices stop
  // about 15 seconds into one utterance, so a briefing spoken as one would be cut off.
  function speechChunks(text, maxChars) {
    var limit = maxChars > 20 ? maxChars : 20;
    var words = typeof text === "string" ? text.replace(/\s+/g, " ").trim() : "";
    if (!words) {
      return [];
    }
    // A sentence ends at a stop followed by a space or the end, never at one inside a word or a
    // number: "US$12.40" split at its point is spoken "twelve dollars. forty".
    var sentences = words.match(/\S.*?(?:[.!?]+(?=\s|$)|$)/g) || [words];
    var chunks = [];
    var current = "";
    sentences.forEach(function (sentence) {
      var piece = sentence.trim();
      while (piece.length > limit) {
        var cut = piece.lastIndexOf(" ", limit);
        if (cut <= 0) {
          cut = limit;
        }
        if (current) {
          chunks.push(current);
          current = "";
        }
        chunks.push(piece.slice(0, cut).trim());
        piece = piece.slice(cut).trim();
      }
      if (!piece) {
        return;
      }
      if (current && current.length + 1 + piece.length > limit) {
        chunks.push(current);
        current = piece;
      } else {
        current = current ? current + " " + piece : piece;
      }
    });
    if (current) {
      chunks.push(current);
    }
    return chunks;
  }

  // What to tell the operator for each error the browser's recognition reports
  // (SpeechRecognitionErrorEvent.error). "aborted" is the page stopping it: nothing to say.
  var RECOGNITION_MESSAGES = {
    "not-allowed":
      "The microphone is blocked for this page. Allow it in the browser's site settings (the icon beside the address), or type your question.",
    "service-not-allowed":
      "This browser will not let the page use speech recognition. Try Chrome or Edge, or type your question.",
    "audio-capture": "No microphone was found. Plug one in or check it is switched on, or type your question.",
    network:
      "Speech recognition needs the browser's online speech service, which could not be reached. Some browsers (Brave, and many Chromium builds) do not include one: try Chrome or Edge, or type your question.",
    "language-not-supported": "Speech recognition does not support this language here. Type your question instead.",
    "no-speech": "Heard nothing. Try again, or type your question.",
    aborted: "",
  };

  function recognitionMessage(code) {
    if (Object.prototype.hasOwnProperty.call(RECOGNITION_MESSAGES, code)) {
      return RECOGNITION_MESSAGES[code];
    }
    return "Speech recognition failed. Type your question instead.";
  }

  // The voice to speak with: one for the exact tag, then the browser's default English voice,
  // then any English one. Null leaves the choice to the browser.
  function pickVoice(voices, lang) {
    var list = Array.isArray(voices) ? voices : [];
    function find(test) {
      for (var i = 0; i < list.length; i++) {
        var voice = list[i];
        if (voice && typeof voice.lang === "string" && test(voice, voice.lang.replace("_", "-").toLowerCase())) {
          return voice;
        }
      }
      return null;
    }
    var wanted = String(lang || "").toLowerCase();
    return (
      find(function (voice, tag) {
        return tag === wanted;
      }) ||
      find(function (voice, tag) {
        return voice["default"] === true && tag.indexOf("en") === 0;
      }) ||
      find(function (voice, tag) {
        return tag.indexOf("en") === 0;
      })
    );
  }

  var api = {
    speechLang: speechLang,
    speechChunks: speechChunks,
    recognitionMessage: recognitionMessage,
    pickVoice: pickVoice,
    isHowTo: isHowTo,
    isDestructive: isDestructive,
    cardHeading: cardHeading,
    tableModel: tableModel,
    renderCard: renderCard,
    renderTable: renderTable,
    QUESTION_MAX_CHARS: QUESTION_MAX_CHARS,
    HISTORY_MAX_TURNS: HISTORY_MAX_TURNS,
    TURN_MAX_CHARS: TURN_MAX_CHARS,
    base64Url: base64Url,
    randomString: randomString,
    pkceChallenge: pkceChallenge,
    readConfig: readConfig,
    authorizeUrl: authorizeUrl,
    tokenRequestBody: tokenRequestBody,
    logoutUrl: logoutUrl,
    checkQuestion: checkQuestion,
    buildHistory: buildHistory,
    flattenRows: flattenRows,
    cardKind: cardKind,
    spokenText: spokenText,
  };
  root.BloggerAsk = api;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  }

  // ---------------------------------------------------------------------------------------------
  // The page itself. Nothing below runs under Node.
  // ---------------------------------------------------------------------------------------------

  var doc = root.document;
  if (!doc || !doc.getElementById("ask-app")) {
    return;
  }

  var config = readConfig(root.OPS_ASSISTANT);
  if (!config || !root.crypto || !root.crypto.subtle || !root.fetch) {
    // No settings (or a browser too old to sign in safely): "not available here" stays up.
    return;
  }

  // -- state: all of it, and all of it gone when the tab closes or reloads ---------------------
  var accessToken = null;
  var tokenExpiresAt = 0;
  var turns = []; // [{ role, text }], oldest first
  var muted = false;
  var busy = false;

  function el(id) {
    return doc.getElementById(id);
  }

  var unavailable = el("ask-unavailable");
  var gate = el("ask-gate");
  var gateMessage = el("ask-gate-message");
  var app = el("ask-app");
  var status = el("ask-status");
  var conversation = el("ask-conversation");
  var questionInput = el("ask-question");
  var talkButton = el("ask-talk");
  var muteButton = el("ask-mute");

  function make(tag, className, text) {
    return makeNode(doc, tag, className, text);
  }

  function clear(node) {
    while (node.firstChild) {
      node.removeChild(node.firstChild);
    }
  }

  // -- speaking --------------------------------------------------------------------------------
  // An answer is spoken a sentence or two at a time (speechChunks). Every utterance is held in
  // `speechQueue` until it ends: Chrome can collect one nobody refers to and stop mid-word.

  var LANG = speechLang(root.navigator && root.navigator.language);
  var synth = root.speechSynthesis && root.SpeechSynthesisUtterance ? root.speechSynthesis : null;
  var speechQueue = [];
  var speechTimer = 0;
  var speechUnlocked = false;
  var blockedSpeech = ""; // an answer the browser refused to speak until the next tap
  var voice = null;

  function chooseVoice() {
    if (synth) {
      voice = pickVoice(synth.getVoices(), LANG);
    }
  }

  function stopSpeaking() {
    root.clearTimeout(speechTimer);
    speechQueue = [];
    // Cancel only what is there: Chrome can drop the next utterance after a needless cancel().
    if (synth && (synth.speaking || synth.pending)) {
      synth.cancel();
    }
  }

  // Speaks whatever it is given, muted or not (the voice test uses it directly).
  // `onDone` (optional) is called once, when the last piece has been spoken (or failed), so the
  // voice test can start listening after its sample and not over it: listening cancels speech.
  function say(text, onDone) {
    if (!synth) {
      return false;
    }
    stopSpeaking();
    var chunks = speechChunks(text, SPEECH_CHUNK_CHARS);
    if (!chunks.length) {
      return false;
    }
    var done = false;
    function finish() {
      if (!done) {
        done = true;
        if (onDone) {
          onDone();
        }
      }
    }
    if (!voice) {
      chooseVoice();
    }
    // On the next tick, never in the same one as cancel(): Chrome drops that utterance.
    speechTimer = root.setTimeout(function () {
      chunks.forEach(function (chunk, position) {
        var utterance = new root.SpeechSynthesisUtterance(chunk);
        utterance.lang = LANG;
        if (voice) {
          utterance.voice = voice;
        }
        utterance.onend = utterance.onerror = function (event) {
          var index = speechQueue.indexOf(utterance);
          if (index >= 0) {
            speechQueue.splice(index, 1);
          }
          if (event && event.type === "error" && event.error === "not-allowed") {
            // The browser wants a tap before it will speak (iOS): keep the answer, and say it
            // when the operator next taps or clicks anything (unlockSpeech).
            blockedSpeech = text;
            speechUnlocked = false;
            status.textContent = "Tap anywhere on the page to hear the answer.";
          }
          if (position === chunks.length - 1) {
            finish();
          }
        };
        speechQueue.push(utterance);
        synth.speak(utterance);
      });
    }, SPEECH_DELAY_MS);
    // A browser that never reports the end must not leave the caller waiting for ever.
    root.setTimeout(finish, SPEECH_DONE_FALLBACK_MS);
    return true;
  }

  function speak(text) {
    if (muted || !text) {
      return;
    }
    say(text);
  }

  // iOS speaks only if speech was first started from a tap; an answer arrives seconds after one.
  // The first tap on a control (not the talk button, whose tap starts the microphone) speaks one
  // silent space, and later answers are then allowed.
  //
  // On click (and Enter or Space), not pointerdown: a touch's pointerdown is not a user activation,
  // so iOS would refuse the very utterance meant to unlock it. Not on the talk button, whose tap
  // starts the microphone. Marked done only when the silent utterance actually starts; an answer
  // that was refused in the meantime (blockedSpeech) is spoken now, from this tap.
  function unlockSpeech(event) {
    if (!synth || (event && event.target && event.target.closest && event.target.closest("#ask-talk"))) {
      return;
    }
    if (blockedSpeech) {
      var text = blockedSpeech;
      blockedSpeech = "";
      speechUnlocked = true;
      speak(text);
      return;
    }
    if (speechUnlocked) {
      return;
    }
    var silent = new root.SpeechSynthesisUtterance(" ");
    silent.volume = 0;
    silent.onstart = function () {
      speechUnlocked = true;
    };
    synth.speak(silent);
  }

  // Back to the gate: forgets the token and the conversation.
  function showGate(message) {
    accessToken = null;
    tokenExpiresAt = 0;
    turns = [];
    stopSpeaking();
    stopListening();
    clear(conversation);
    status.textContent = "";
    unavailable.hidden = true;
    app.hidden = true;
    gate.hidden = false;
    gateMessage.textContent = message || "";
  }

  function showApp() {
    unavailable.hidden = true;
    gate.hidden = true;
    app.hidden = false;
    status.textContent = "";
    questionInput.focus();
  }

  // -- sign-in ---------------------------------------------------------------------------------

  function signIn() {
    var verifier = randomString(32, root.crypto);
    var state = randomString(16, root.crypto);
    pkceChallenge(verifier, root.crypto.subtle).then(
      function (challenge) {
        try {
          root.sessionStorage.setItem(VERIFIER_KEY, verifier);
          root.sessionStorage.setItem(STATE_KEY, state);
        } catch (err) {
          gateMessage.textContent = "This browser will not let the page remember the sign-in step. " + MESSAGES.signInFailed;
          return;
        }
        root.location.assign(authorizeUrl(config, state, challenge));
      },
      function () {
        gateMessage.textContent = MESSAGES.signInFailed;
      }
    );
  }

  // Runs once on load. If Cognito has just sent the browser back (?code=...&state=...), finishes
  // the sign-in; otherwise shows the gate.
  function start() {
    var params = new root.URLSearchParams(root.location.search);
    var code = params.get("code");
    var returnedState = params.get("state");
    var failed = params.get("error");

    // Whatever happens next, the verifier and state are used up: read them and remove them.
    var verifier = null;
    var expectedState = null;
    try {
      verifier = root.sessionStorage.getItem(VERIFIER_KEY);
      expectedState = root.sessionStorage.getItem(STATE_KEY);
      root.sessionStorage.removeItem(VERIFIER_KEY);
      root.sessionStorage.removeItem(STATE_KEY);
    } catch (err) {
      // Storage is blocked: there was no sign-in to finish.
    }

    if (!code && !failed) {
      showGate("");
      return;
    }

    // The code is single-use and now in hand: take it (and the state) out of the address bar and
    // the history entry before doing anything else.
    root.history.replaceState(null, "", root.location.pathname);

    if (failed || !code || !verifier || !expectedState || returnedState !== expectedState) {
      showGate(MESSAGES.signInFailed);
      return;
    }

    showGate("Signing in.");
    root
      .fetch("https://" + config.hostedUiDomain + "/oauth2/token", {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: tokenRequestBody(config, code, verifier),
      })
      .then(function (response) {
        if (!response.ok) {
          throw new Error("token exchange refused");
        }
        return response.json();
      })
      .then(function (tokens) {
        if (!tokens || !isText(tokens.access_token)) {
          throw new Error("no access token");
        }
        // Only the access token is kept, and only here. The id and refresh tokens, if Cognito
        // sent any, are dropped with `tokens`.
        accessToken = tokens.access_token;
        var seconds = Number(tokens.expires_in) > 0 ? Number(tokens.expires_in) : 3600;
        tokenExpiresAt = Date.now() + seconds * 1000;
        showApp();
      })
      .catch(function () {
        showGate(MESSAGES.signInFailed);
      });
  }

  function signOut() {
    showGate("");
    root.location.assign(logoutUrl(config));
  }

  // -- showing an answer -----------------------------------------------------------------------

  function copyCommand(code, button) {
    var label = button.textContent;
    function selectIt() {
      // No clipboard (an old browser, or permission refused): select the command so Ctrl+C works.
      var range = doc.createRange();
      range.selectNodeContents(code);
      var selection = root.getSelection();
      selection.removeAllRanges();
      selection.addRange(range);
      status.textContent = "Command selected. Press Ctrl+C (or Cmd+C) to copy it.";
    }
    if (root.navigator.clipboard && root.navigator.clipboard.writeText) {
      root.navigator.clipboard.writeText(code.textContent).then(function () {
        status.textContent =
          "Command copied. Run it in your own terminal" +
          (config.environment ? ", against the " + config.environment + " admin API." : ".");
        button.textContent = "Copied";
        root.setTimeout(function () {
          button.textContent = label;
        }, 2000);
      }, selectIt);
    } else {
      selectIt();
    }
  }

  function renderTurn(question, result) {
    var turn = make("article", "ask-turn");
    turn.appendChild(make("p", "ask-turn-question", "You asked: " + question));
    turn.appendChild(make("p", "ask-turn-answer", result.answer));

    // Tables first: when one was asked for ("list my topics"), it is the answer.
    result.tables.forEach(function (table) {
      var shown = renderTable(doc, table);
      if (shown) {
        turn.appendChild(shown);
      }
    });

    if (result.toolCalls.length) {
      turn.appendChild(make("h2", "", "What the assistant called"));
      var list = make("ol", "ask-tool-calls");
      result.toolCalls.forEach(function (call) {
        var item = make("li");
        var args = call && call.arguments !== undefined ? JSON.stringify(call.arguments) : "{}";
        item.appendChild(make("code", "", String(call && call.name) + " " + args));
        list.appendChild(item);
      });
      turn.appendChild(list);
    }

    if (result.findings.length) {
      // An answer to "how do I ...?" has only how-to cards: nothing was found wrong.
      var guidance = result.findings.every(isHowTo);
      turn.appendChild(make("h2", "", guidance ? "How to do it" : "Findings and suggestions"));
      result.findings.forEach(function (finding) {
        if (finding && typeof finding === "object") {
          turn.appendChild(renderCard(doc, finding, copyCommand));
        }
      });
    }
    // Newest first, so the answer just given is next to the controls.
    conversation.insertBefore(turn, conversation.firstChild);
  }

  // -- asking ----------------------------------------------------------------------------------

  function setBusy(value) {
    busy = value;
    ["ask-send", "ask-briefing", "ask-new", "ask-talk"].forEach(function (id) {
      el(id).disabled = value;
    });
    conversation.setAttribute("aria-busy", value ? "true" : "false");
  }

  function errorFrom(response) {
    return response.json().then(
      function (body) {
        return body && isText(body.error) ? body.error : "";
      },
      function () {
        return "";
      }
    );
  }

  function ask(text) {
    if (busy) {
      return;
    }
    stopSpeaking(); // a new question interrupts the last answer
    var checked = checkQuestion(text);
    if (checked.error) {
      status.textContent = checked.error;
      return;
    }
    if (!accessToken || Date.now() >= tokenExpiresAt) {
      showGate(MESSAGES.expired);
      return;
    }

    var question = checked.question;
    var controller = root.AbortController ? new root.AbortController() : null;
    var timer = root.setTimeout(function () {
      if (controller) {
        controller.abort();
      }
    }, ASK_TIMEOUT_MS);
    setBusy(true);
    status.textContent = MESSAGES.busy;

    root
      .fetch(config.askUrl, {
        method: "POST",
        headers: { Authorization: "Bearer " + accessToken, "Content-Type": "application/json" },
        body: JSON.stringify({ question: question, history: buildHistory(turns) }),
        signal: controller ? controller.signal : undefined,
      })
      .then(function (response) {
        if (response.status === 401) {
          showGate(MESSAGES.expired);
          return null;
        }
        if (response.status === 403) {
          status.textContent = MESSAGES.forbidden;
          return null;
        }
        if (response.status === 429) {
          // The daily cap (the API's own words), or API Gateway's throttle (no words of its own).
          return errorFrom(response).then(function (reason) {
            status.textContent = reason || "Too many questions just now. Try again in a moment.";
            return null;
          });
        }
        if (response.status === 400) {
          return errorFrom(response).then(function (reason) {
            status.textContent = "The assistant did not take that question" + (reason ? ": " + reason : ".");
            return null;
          });
        }
        if (!response.ok) {
          status.textContent = MESSAGES.failed; // 502, and anything else that is not an answer
          return null;
        }
        return response.json().then(function (body) {
          if (!body || typeof body.answer !== "string") {
            status.textContent = MESSAGES.failed;
            return null;
          }
          var result = {
            answer: body.answer,
            toolCalls: Array.isArray(body.tool_calls) ? body.tool_calls : [],
            findings: Array.isArray(body.findings) ? body.findings : [],
            tables: Array.isArray(body.tables) ? body.tables : [],
          };
          turns.push({ role: "user", text: question });
          turns.push({ role: "assistant", text: result.answer });
          status.textContent = "";
          questionInput.value = "";
          renderTurn(question, result);
          speak(spokenText(result.answer, result.findings));
          return null;
        });
      })
      .catch(function () {
        status.textContent = MESSAGES.network;
      })
      .then(function () {
        root.clearTimeout(timer);
        setBusy(false);
      });
  }

  function newBriefing() {
    turns = [];
    stopSpeaking();
    clear(conversation);
    status.textContent = "Cleared. The next question starts a new briefing.";
    questionInput.value = "";
    questionInput.focus();
  }

  function toggleMute() {
    muted = !muted;
    if (muted) {
      stopSpeaking();
    }
    muteButton.setAttribute("aria-pressed", muted ? "true" : "false");
    muteButton.textContent = muted ? "Unmute voice" : "Mute voice";
  }

  // -- talking -------------------------------------------------------------------------------
  // Tap to start and tap again to stop, or let the browser stop when you stop speaking; or hold
  // (pointer, Space or Enter) and let go to finish. The words are shown as they are heard, and
  // the question is asked once recognition ends with something heard.

  var Recognition = root.SpeechRecognition || root.webkitSpeechRecognition;
  var recognition = null;
  var listening = false;
  var pressedAt = 0; // when the current press began; 0 when nothing is held
  var pressStarted = false; // whether that press was the one that started listening
  var lastPressAt = 0; // when a pointer or key press was last dealt with, to ignore its own click

  function setListening(value) {
    listening = value;
    talkButton.setAttribute("aria-pressed", value ? "true" : "false");
    talkButton.textContent = value ? "Listening. Press to stop" : "Push to talk";
  }

  // Starts the microphone. `onHeard(text)` gets what was said once recognition ends: by default
  // the question is asked; the voice test only reports it.
  function startListening(onHeard) {
    if (listening || busy || !Recognition) {
      return;
    }
    stopSpeaking();
    var heard = "";
    var failed = false;
    var current = new Recognition();
    recognition = current;
    current.lang = LANG;
    current.interimResults = true; // shown as they come, so it is clear the microphone is working
    current.continuous = false;
    current.maxAlternatives = 1;
    current.onresult = function (event) {
      var finalText = "";
      var interim = "";
      var results = event.results || [];
      for (var i = 0; i < results.length; i++) {
        var best = results[i] && results[i][0];
        var text = best && typeof best.transcript === "string" ? best.transcript : "";
        if (results[i].isFinal === false) {
          interim += text;
        } else {
          finalText += text;
        }
      }
      heard = finalText.trim();
      questionInput.value = (finalText + interim).trim();
      status.textContent = "Heard: " + questionInput.value;
    };
    current.onerror = function (event) {
      failed = true;
      var message = recognitionMessage(event && event.error);
      if (message) {
        status.textContent = message;
      }
    };
    current.onend = function () {
      if (recognition === current) {
        recognition = null;
      }
      setListening(false);
      if (heard) {
        (onHeard || ask)(heard);
      } else if (!failed) {
        status.textContent = recognitionMessage("no-speech");
      }
    };
    try {
      current.start();
      setListening(true);
      status.textContent = "Listening.";
    } catch (err) {
      recognition = null;
      setListening(false);
      status.textContent = recognitionMessage("");
    }
  }

  function stopListening() {
    if (listening && recognition) {
      recognition.stop(); // delivers what was heard so far, then onend
    }
  }

  function pressDown() {
    if (pressedAt) {
      return; // a held key repeats
    }
    pressedAt = Date.now();
    lastPressAt = pressedAt;
    pressStarted = !listening;
    if (listening) {
      stopListening();
    } else {
      startListening();
    }
  }

  function pressUp() {
    if (!pressedAt) {
      return;
    }
    var held = Date.now() - pressedAt;
    pressedAt = 0;
    lastPressAt = Date.now();
    // A real hold ends the question on release. A tap leaves it listening until the next press.
    if (pressStarted && held >= HOLD_MS) {
      stopListening();
    }
  }

  // The browser took the pointer (a scroll, or a long press on a phone): that is not the
  // operator letting go, so the microphone stays on until they tap again or stop speaking.
  function pressCancelled() {
    pressedAt = 0;
    lastPressAt = Date.now();
  }

  function isTalkKey(event) {
    return event.key === " " || event.key === "Spacebar" || event.key === "Enter";
  }

  function wireTalkButton() {
    if (!Recognition) {
      el("ask-no-speech").hidden = false;
      return;
    }
    talkButton.hidden = false;
    el("ask-talk-hint").hidden = false;

    talkButton.addEventListener("pointerdown", function (event) {
      if (event.button === 0) {
        pressDown();
      }
    });
    talkButton.addEventListener("pointerup", pressUp);
    talkButton.addEventListener("pointercancel", pressCancelled);
    talkButton.addEventListener("pointerleave", function (event) {
      // A mouse dragged off the button lets go of it; a finger lifting off a screen also
      // "leaves", after its pointerup, and is already dealt with.
      if (event.pointerType === "mouse") {
        pressUp();
      }
    });
    talkButton.addEventListener("contextmenu", function (event) {
      event.preventDefault(); // a long press must not open a menu
    });
    talkButton.addEventListener("keydown", function (event) {
      if (isTalkKey(event)) {
        event.preventDefault(); // Space must not scroll the page
        pressDown();
      }
    });
    talkButton.addEventListener("keyup", function (event) {
      if (isTalkKey(event)) {
        event.preventDefault();
        pressUp();
      }
    });
    // A click with no pointer or key press just before it comes from assistive technology (a
    // screen reader's "activate"): treat it as a tap. One that follows a press is that press.
    talkButton.addEventListener("click", function () {
      if (Date.now() - lastPressAt < CLICK_AFTER_PRESS_MS) {
        return;
      }
      if (listening) {
        stopListening();
      } else {
        startListening();
      }
    });
  }

  // -- the voice test --------------------------------------------------------------------------
  // Says which part of the voice works here: speaking, the microphone's permission, and
  // recognition. Each line is the page's own text, or what the browser heard.

  function report(lines) {
    var list = el("ask-voice-report");
    clear(list);
    lines.forEach(function (line) {
      list.appendChild(make("li", "", line));
    });
    list.hidden = false;
  }

  function testVoice() {
    if (busy || listening) {
      return;
    }
    var lines = [];
    lines.push(
      synth
        ? "Speaking: the browser can speak answers" + (muted ? " (the voice is muted for answers)." : ".") + " You should hear a short sentence now."
        : "Speaking: this browser cannot speak answers. They are shown as text."
    );
    // The test button's own click: the browser lets the page speak from it.
    var sampleDone = false;
    var afterSample = null;
    function whenSampleDone(next) {
      if (sampleDone) {
        next();
      } else {
        afterSample = next;
      }
    }
    var speaking = say("This is how the assistant's answers will sound.", function () {
      sampleDone = true;
      if (afterSample) {
        var next = afterSample;
        afterSample = null;
        next();
      }
    });
    if (!speaking) {
      sampleDone = true;
    }
    if (!Recognition) {
      lines.push("Listening: this browser has no speech recognition. Type your questions; Chrome or Edge can listen.");
      report(lines);
      return;
    }
    var permissions = root.navigator && root.navigator.permissions;
    var checked = permissions && permissions.query ? permissions.query({ name: "microphone" }) : null;
    var listen = function (state) {
      if (state === "denied") {
        lines.push("Microphone: blocked for this page. Allow it in the site settings (the icon beside the address).");
        report(lines);
        return;
      }
      lines.push(
        "Microphone: " +
          (state === "granted" ? "allowed." : "the browser will ask; allow it.") +
          " Say something short after the sentence ends; the words heard will appear here."
      );
      report(lines);
      // After the sample has been spoken: listening cancels speech, so a fixed wait could cut it off.
      whenSampleDone(function () {
        startListening(function (heard) {
          lines.push("Listening works. Heard: " + heard);
          report(lines);
          status.textContent = "Voice test finished.";
        });
      });
    };
    if (checked && checked.then) {
      checked.then(
        function (result) {
          listen(result && result.state);
        },
        function () {
          listen("");
        }
      );
    } else {
      listen("");
    }
  }

  // -- wiring ----------------------------------------------------------------------------------

  el("ask-sign-in").addEventListener("click", signIn);
  el("ask-sign-out").addEventListener("click", signOut);
  el("ask-new").addEventListener("click", newBriefing);
  muteButton.addEventListener("click", toggleMute);
  el("ask-voice-test").addEventListener("click", testVoice);
  // The whole document, not just the app: "tap anywhere" must mean anywhere.
  doc.addEventListener("click", unlockSpeech, true);
  doc.addEventListener("keydown", function (event) {
    if (event.key === "Enter" || event.key === " ") {
      unlockSpeech(event);
    }
  }, true);
  if (synth) {
    chooseVoice();
    if (synth.addEventListener) {
      synth.addEventListener("voiceschanged", chooseVoice); // voices load after the page in Chrome
    }
  }
  if (config.environment) {
    var envLabel = el("ask-environment");
    envLabel.textContent = "Environment: " + config.environment;
    envLabel.hidden = false;
  }
  // The API treats a question with no history as a briefing, so the shortcut starts afresh.
  el("ask-briefing").addEventListener("click", function () {
    if (busy) {
      return;
    }
    turns = [];
    clear(conversation);
    ask(BRIEFING_QUESTION);
  });
  el("ask-form").addEventListener("submit", function (event) {
    event.preventDefault();
    ask(questionInput.value);
  });
  // Leaving the page must not leave a voice talking.
  root.addEventListener("pagehide", stopSpeaking);
  wireTalkButton();
  start();
})(typeof window !== "undefined" ? window : globalThis);
