/* The operator's assistant page (ask.html): sign in, ask, hear the answer, see what to do.
   Design: docs/enhancements/alexa-plus-operator-assistant-enhancement.md, sections 3, 5 and 7.

   Sign-in is Cognito's hosted page, authorization code with PKCE (S256). The page makes a random
   verifier and state, keeps them in sessionStorage only for the trip to the hosted page and back,
   and swaps the returned code for an access token at the hosted domain's /oauth2/token.

   THE ACCESS TOKEN LIVES IN A VARIABLE AND NOWHERE ELSE: never in sessionStorage, localStorage or
   a cookie, so closing or reloading the tab signs you out. The conversation is the same: an array
   in this file, sent back as `history` with each question, gone with the tab.

   EVERYTHING THE API RETURNS IS TREATED AS TEXT FROM A STRANGER. It reaches the page through
   createElement and textContent only; nothing in this file parses a string as HTML or code. A
   suggested command is shown for the operator to copy and run in their own terminal: this page
   never runs one, and never reads one aloud.

   Settings come from config.js (generated by Terraform) as window.OPS_ASSISTANT. Where it is
   missing, the page leaves "not available here" showing and does nothing.

   The pure parts are exported for the Node test (lambdas/tests/test_frontend_ask.py). */
(function (root) {
  "use strict";

  // The limits POST /ask enforces (lambdas/ops_agent_handler.py); checked here before sending.
  var QUESTION_MAX_CHARS = 500;
  var HISTORY_MAX_TURNS = 6;
  var TURN_MAX_CHARS = 1000;

  // The only two things this page ever puts in browser storage, and only during sign-in.
  var VERIFIER_KEY = "bloggerbear-ask-pkce-verifier";
  var STATE_KEY = "bloggerbear-ask-pkce-state";

  var BRIEFING_QUESTION = "What needs my attention?";
  var ASK_TIMEOUT_MS = 40000; // API Gateway gives up at 29 s; this is only a backstop
  var HOLD_MS = 400; // a press shorter than this is a tap: start now, stop on the next press
  var CLICK_AFTER_PRESS_MS = 700; // a click this soon after a press belongs to that press

  var MESSAGES = {
    expired: "Your sign-in has expired. Sign in again to carry on.",
    forbidden: "The assistant is switched off or not available from here.",
    failed: "The assistant could not answer just now. Try again in a moment.",
    network:
      "Could not reach the assistant. Check your connection; it may also be switched off or not available from here.",
    signInFailed: "Sign-in did not complete. Try again.",
    busy: "Asking. An answer can take up to half a minute.",
  };

  // ---------------------------------------------------------------------------------------------
  // Pure functions (no DOM, no globals): what the Node test covers.
  // ---------------------------------------------------------------------------------------------

  function base64Url(bytes) {
    var binary = "";
    for (var i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  }

  function randomString(byteCount, cryptoImpl) {
    var bytes = new Uint8Array(byteCount);
    cryptoImpl.getRandomValues(bytes);
    return base64Url(bytes);
  }

  // RFC 7636 section 4.2: BASE64URL(SHA256(ASCII(verifier))).
  function pkceChallenge(verifier, subtle) {
    var ascii = new Uint8Array(verifier.length);
    for (var i = 0; i < verifier.length; i++) {
      ascii[i] = verifier.charCodeAt(i);
    }
    return subtle.digest("SHA-256", ascii).then(function (digest) {
      return base64Url(new Uint8Array(digest));
    });
  }

  function isText(value) {
    return typeof value === "string" && value.trim() !== "";
  }

  // The settings as config.js gave them, or null unless every one is there and looks right.
  function readConfig(raw) {
    if (!raw || typeof raw !== "object") {
      return null;
    }
    var names = ["askUrl", "hostedUiDomain", "clientId", "scope", "redirectUri"];
    for (var i = 0; i < names.length; i++) {
      if (!isText(raw[names[i]])) {
        return null;
      }
    }
    if (raw.askUrl.indexOf("https://") !== 0 || raw.redirectUri.indexOf("https://") !== 0) {
      return null;
    }
    if (!/^[a-z0-9.-]+$/.test(raw.hostedUiDomain)) {
      return null;
    }
    return {
      askUrl: raw.askUrl,
      hostedUiDomain: raw.hostedUiDomain,
      clientId: raw.clientId,
      scope: raw.scope,
      redirectUri: raw.redirectUri,
    };
  }

  function query(params) {
    return Object.keys(params)
      .map(function (name) {
        return encodeURIComponent(name) + "=" + encodeURIComponent(params[name]);
      })
      .join("&");
  }

  function authorizeUrl(config, state, challenge) {
    return (
      "https://" +
      config.hostedUiDomain +
      "/oauth2/authorize?" +
      query({
        response_type: "code",
        client_id: config.clientId,
        redirect_uri: config.redirectUri,
        scope: config.scope,
        state: state,
        code_challenge: challenge,
        code_challenge_method: "S256",
      })
    );
  }

  function tokenRequestBody(config, code, verifier) {
    return query({
      grant_type: "authorization_code",
      client_id: config.clientId,
      code: code,
      redirect_uri: config.redirectUri,
      code_verifier: verifier,
    });
  }

  function logoutUrl(config) {
    return (
      "https://" +
      config.hostedUiDomain +
      "/logout?" +
      query({ client_id: config.clientId, logout_uri: config.redirectUri })
    );
  }

  // { question } trimmed and within the limit, or { error } to show instead of sending.
  function checkQuestion(text) {
    var question = typeof text === "string" ? text.trim() : "";
    if (!question) {
      return { error: "Say or type a question first." };
    }
    if (question.length > QUESTION_MAX_CHARS) {
      return { error: "That question is too long: " + QUESTION_MAX_CHARS + " characters at most." };
    }
    return { question: question };
  }

  // What goes back as `history`: the last few turns, each cut to the length the API takes. A turn
  // with no text is left out (the API refuses one).
  function buildHistory(turns) {
    var history = [];
    for (var i = 0; i < turns.length; i++) {
      var turn = turns[i];
      if (!turn || (turn.role !== "user" && turn.role !== "assistant") || !isText(turn.text)) {
        continue;
      }
      history.push({ role: turn.role, text: turn.text.trim().slice(0, TURN_MAX_CHARS) });
    }
    return history.slice(-HISTORY_MAX_TURNS);
  }

  // A finding's `where` (and anything else nested) as flat rows to show:
  // [{ label, text, untrusted }]. Everything under a key named "untrusted" is marked, however
  // deep it sits.
  function flattenRows(value, label, untrusted, rows, depth) {
    rows = rows || [];
    depth = depth || 0;
    if (value === null || value === undefined || value === "") {
      return rows;
    }
    if (typeof value !== "object" || Array.isArray(value) || depth >= 4) {
      rows.push({
        label: label || "",
        text: typeof value === "object" ? JSON.stringify(value) : String(value),
        untrusted: !!untrusted,
      });
      return rows;
    }
    Object.keys(value).forEach(function (key) {
      if (key === "untrusted") {
        flattenRows(value[key], label, true, rows, depth + 1);
      } else {
        flattenRows(value[key], label ? label + " " + key : key, untrusted, rows, depth + 1);
      }
    });
    return rows;
  }

  // What kind of card a finding gets: "fix" (a command to copy), "look" (something to look at,
  // no command) or "noticed" (no suggestion at all).
  function cardKind(finding) {
    var suggestion = finding && finding.suggestion;
    if (!suggestion || typeof suggestion !== "object") {
      return "noticed";
    }
    return isText(suggestion.command) ? "fix" : "look";
  }

  // The answer as it is spoken. The agent is told never to say a command; if one turns up in the
  // answer anyway, it is not read out.
  function spokenText(answer, findings) {
    var text = typeof answer === "string" ? answer : "";
    (Array.isArray(findings) ? findings : []).forEach(function (finding) {
      if (cardKind(finding) === "fix") {
        text = text.split(finding.suggestion.command).join("the command on screen");
      }
    });
    return text;
  }

  var api = {
    QUESTION_MAX_CHARS: QUESTION_MAX_CHARS,
    HISTORY_MAX_TURNS: HISTORY_MAX_TURNS,
    TURN_MAX_CHARS: TURN_MAX_CHARS,
    base64Url: base64Url,
    randomString: randomString,
    pkceChallenge: pkceChallenge,
    readConfig: readConfig,
    authorizeUrl: authorizeUrl,
    tokenRequestBody: tokenRequestBody,
    logoutUrl: logoutUrl,
    checkQuestion: checkQuestion,
    buildHistory: buildHistory,
    flattenRows: flattenRows,
    cardKind: cardKind,
    spokenText: spokenText,
  };
  root.BloggerAsk = api;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  }

  // ---------------------------------------------------------------------------------------------
  // The page itself. Nothing below runs under Node.
  // ---------------------------------------------------------------------------------------------

  var doc = root.document;
  if (!doc || !doc.getElementById("ask-app")) {
    return;
  }

  var config = readConfig(root.OPS_ASSISTANT);
  if (!config || !root.crypto || !root.crypto.subtle || !root.fetch) {
    // No settings (or a browser too old to sign in safely): "not available here" stays up.
    return;
  }

  // -- state: all of it, and all of it gone when the tab closes or reloads ---------------------
  var accessToken = null;
  var tokenExpiresAt = 0;
  var turns = []; // [{ role, text }], oldest first
  var muted = false;
  var busy = false;

  function el(id) {
    return doc.getElementById(id);
  }

  var unavailable = el("ask-unavailable");
  var gate = el("ask-gate");
  var gateMessage = el("ask-gate-message");
  var app = el("ask-app");
  var status = el("ask-status");
  var conversation = el("ask-conversation");
  var questionInput = el("ask-question");
  var talkButton = el("ask-talk");
  var muteButton = el("ask-mute");

  function make(tag, className, text) {
    var node = doc.createElement(tag);
    if (className) {
      node.className = className;
    }
    if (text !== undefined && text !== null) {
      node.textContent = String(text);
    }
    return node;
  }

  function clear(node) {
    while (node.firstChild) {
      node.removeChild(node.firstChild);
    }
  }

  function stopSpeaking() {
    if (root.speechSynthesis) {
      root.speechSynthesis.cancel();
    }
  }

  function speak(text) {
    if (muted || !text || !root.speechSynthesis || !root.SpeechSynthesisUtterance) {
      return;
    }
    stopSpeaking();
    var utterance = new root.SpeechSynthesisUtterance(text);
    utterance.lang = doc.documentElement.lang || "en";
    root.speechSynthesis.speak(utterance);
  }

  // Back to the gate: forgets the token and the conversation.
  function showGate(message) {
    accessToken = null;
    tokenExpiresAt = 0;
    turns = [];
    stopSpeaking();
    stopListening();
    clear(conversation);
    status.textContent = "";
    unavailable.hidden = true;
    app.hidden = true;
    gate.hidden = false;
    gateMessage.textContent = message || "";
  }

  function showApp() {
    unavailable.hidden = true;
    gate.hidden = true;
    app.hidden = false;
    status.textContent = "";
    questionInput.focus();
  }

  // -- sign-in ---------------------------------------------------------------------------------

  function signIn() {
    var verifier = randomString(32, root.crypto);
    var state = randomString(16, root.crypto);
    pkceChallenge(verifier, root.crypto.subtle).then(
      function (challenge) {
        try {
          root.sessionStorage.setItem(VERIFIER_KEY, verifier);
          root.sessionStorage.setItem(STATE_KEY, state);
        } catch (err) {
          gateMessage.textContent = "This browser will not let the page remember the sign-in step. " + MESSAGES.signInFailed;
          return;
        }
        root.location.assign(authorizeUrl(config, state, challenge));
      },
      function () {
        gateMessage.textContent = MESSAGES.signInFailed;
      }
    );
  }

  // Runs once on load. If Cognito has just sent the browser back (?code=...&state=...), finishes
  // the sign-in; otherwise shows the gate.
  function start() {
    var params = new root.URLSearchParams(root.location.search);
    var code = params.get("code");
    var returnedState = params.get("state");
    var failed = params.get("error");

    // Whatever happens next, the verifier and state are used up: read them and remove them.
    var verifier = null;
    var expectedState = null;
    try {
      verifier = root.sessionStorage.getItem(VERIFIER_KEY);
      expectedState = root.sessionStorage.getItem(STATE_KEY);
      root.sessionStorage.removeItem(VERIFIER_KEY);
      root.sessionStorage.removeItem(STATE_KEY);
    } catch (err) {
      // Storage is blocked: there was no sign-in to finish.
    }

    if (!code && !failed) {
      showGate("");
      return;
    }

    // The code is single-use and now in hand: take it (and the state) out of the address bar and
    // the history entry before doing anything else.
    root.history.replaceState(null, "", root.location.pathname);

    if (failed || !code || !verifier || !expectedState || returnedState !== expectedState) {
      showGate(MESSAGES.signInFailed);
      return;
    }

    showGate("Signing in.");
    root
      .fetch("https://" + config.hostedUiDomain + "/oauth2/token", {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: tokenRequestBody(config, code, verifier),
      })
      .then(function (response) {
        if (!response.ok) {
          throw new Error("token exchange refused");
        }
        return response.json();
      })
      .then(function (tokens) {
        if (!tokens || !isText(tokens.access_token)) {
          throw new Error("no access token");
        }
        // Only the access token is kept, and only here. The id and refresh tokens, if Cognito
        // sent any, are dropped with `tokens`.
        accessToken = tokens.access_token;
        var seconds = Number(tokens.expires_in) > 0 ? Number(tokens.expires_in) : 3600;
        tokenExpiresAt = Date.now() + seconds * 1000;
        showApp();
      })
      .catch(function () {
        showGate(MESSAGES.signInFailed);
      });
  }

  function signOut() {
    showGate("");
    root.location.assign(logoutUrl(config));
  }

  // -- showing an answer -----------------------------------------------------------------------

  function appendRow(list, label, text, untrusted) {
    list.appendChild(make("dt", "", label));
    var dd = make("dd", untrusted ? "ask-untrusted" : "");
    if (untrusted) {
      dd.appendChild(make("span", "ask-untrusted-mark", "Unverified"));
    }
    dd.appendChild(doc.createTextNode(text));
    list.appendChild(dd);
  }

  function copyCommand(code, button) {
    function selectIt() {
      // No clipboard (an old browser, or permission refused): select the command so Ctrl+C works.
      var range = doc.createRange();
      range.selectNodeContents(code);
      var selection = root.getSelection();
      selection.removeAllRanges();
      selection.addRange(range);
      status.textContent = "Command selected. Press Ctrl+C (or Cmd+C) to copy it.";
    }
    if (root.navigator.clipboard && root.navigator.clipboard.writeText) {
      root.navigator.clipboard.writeText(code.textContent).then(function () {
        status.textContent = "Command copied. Run it in your own terminal.";
        button.textContent = "Copied";
        root.setTimeout(function () {
          button.textContent = "Copy";
        }, 2000);
      }, selectIt);
    } else {
      selectIt();
    }
  }

  function renderCard(finding) {
    var card = make("div", "ask-card");
    var kind = cardKind(finding);
    var suggestion = kind === "noticed" ? null : finding.suggestion;

    var top = make("dl");
    appendRow(top, "Noticed", isText(finding.noticed) ? finding.noticed : "(no description)", false);
    var where = flattenRows(finding.where, "", false);
    flattenRows(finding.untrusted, "", true, where);
    where.forEach(function (row, index) {
      var text = row.label ? row.label + ": " + row.text : row.text;
      appendRow(top, index === 0 ? "Where" : "", text, row.untrusted);
    });
    if (suggestion && isText(suggestion.action)) {
      appendRow(top, kind === "fix" ? "Suggested" : "Look at", suggestion.action, false);
    }
    card.appendChild(top);

    if (kind === "fix") {
      var block = make("div", "ask-command");
      var pre = make("pre");
      var code = make("code", "", suggestion.command);
      pre.appendChild(code);
      var copy = make("button", "ask-copy", "Copy");
      copy.type = "button";
      copy.setAttribute("aria-label", "Copy the suggested command");
      copy.addEventListener("click", function () {
        copyCommand(code, copy);
      });
      block.appendChild(pre);
      block.appendChild(copy);
      card.appendChild(block);
    }
    if (suggestion && isText(suggestion.what_it_does)) {
      var bottom = make("dl");
      appendRow(bottom, "What it does", suggestion.what_it_does, false);
      card.appendChild(bottom);
    }
    return card;
  }

  function renderTurn(question, result) {
    var turn = make("article", "ask-turn");
    turn.appendChild(make("p", "ask-turn-question", "You asked: " + question));
    turn.appendChild(make("p", "ask-turn-answer", result.answer));

    if (result.toolCalls.length) {
      turn.appendChild(make("h2", "", "What the assistant called"));
      var list = make("ol", "ask-tool-calls");
      result.toolCalls.forEach(function (call) {
        var item = make("li");
        var args = call && call.arguments !== undefined ? JSON.stringify(call.arguments) : "{}";
        item.appendChild(make("code", "", String(call && call.name) + " " + args));
        list.appendChild(item);
      });
      turn.appendChild(list);
    }

    if (result.findings.length) {
      turn.appendChild(make("h2", "", "Findings and suggestions"));
      result.findings.forEach(function (finding) {
        if (finding && typeof finding === "object") {
          turn.appendChild(renderCard(finding));
        }
      });
    }
    // Newest first, so the answer just given is next to the controls.
    conversation.insertBefore(turn, conversation.firstChild);
  }

  // -- asking ----------------------------------------------------------------------------------

  function setBusy(value) {
    busy = value;
    ["ask-send", "ask-briefing", "ask-new", "ask-talk"].forEach(function (id) {
      el(id).disabled = value;
    });
    conversation.setAttribute("aria-busy", value ? "true" : "false");
  }

  function errorFrom(response) {
    return response.json().then(
      function (body) {
        return body && isText(body.error) ? body.error : "";
      },
      function () {
        return "";
      }
    );
  }

  function ask(text) {
    if (busy) {
      return;
    }
    stopSpeaking(); // a new question interrupts the last answer
    var checked = checkQuestion(text);
    if (checked.error) {
      status.textContent = checked.error;
      return;
    }
    if (!accessToken || Date.now() >= tokenExpiresAt) {
      showGate(MESSAGES.expired);
      return;
    }

    var question = checked.question;
    var controller = root.AbortController ? new root.AbortController() : null;
    var timer = root.setTimeout(function () {
      if (controller) {
        controller.abort();
      }
    }, ASK_TIMEOUT_MS);
    setBusy(true);
    status.textContent = MESSAGES.busy;

    root
      .fetch(config.askUrl, {
        method: "POST",
        headers: { Authorization: "Bearer " + accessToken, "Content-Type": "application/json" },
        body: JSON.stringify({ question: question, history: buildHistory(turns) }),
        signal: controller ? controller.signal : undefined,
      })
      .then(function (response) {
        if (response.status === 401) {
          showGate(MESSAGES.expired);
          return null;
        }
        if (response.status === 403) {
          status.textContent = MESSAGES.forbidden;
          return null;
        }
        if (response.status === 400) {
          return errorFrom(response).then(function (reason) {
            status.textContent = "The assistant did not take that question" + (reason ? ": " + reason : ".");
            return null;
          });
        }
        if (!response.ok) {
          status.textContent = MESSAGES.failed; // 502, and anything else that is not an answer
          return null;
        }
        return response.json().then(function (body) {
          if (!body || typeof body.answer !== "string") {
            status.textContent = MESSAGES.failed;
            return null;
          }
          var result = {
            answer: body.answer,
            toolCalls: Array.isArray(body.tool_calls) ? body.tool_calls : [],
            findings: Array.isArray(body.findings) ? body.findings : [],
          };
          turns.push({ role: "user", text: question });
          turns.push({ role: "assistant", text: result.answer });
          status.textContent = "";
          questionInput.value = "";
          renderTurn(question, result);
          speak(spokenText(result.answer, result.findings));
          return null;
        });
      })
      .catch(function () {
        status.textContent = MESSAGES.network;
      })
      .then(function () {
        root.clearTimeout(timer);
        setBusy(false);
      });
  }

  function newBriefing() {
    turns = [];
    stopSpeaking();
    clear(conversation);
    status.textContent = "Cleared. The next question starts a new briefing.";
    questionInput.value = "";
    questionInput.focus();
  }

  function toggleMute() {
    muted = !muted;
    if (muted) {
      stopSpeaking();
    }
    muteButton.setAttribute("aria-pressed", muted ? "true" : "false");
    muteButton.textContent = muted ? "Unmute voice" : "Mute voice";
  }

  // -- push to talk ----------------------------------------------------------------------------
  // Hold the button (pointer, Space or Enter) and let go to finish; or press briefly to start and
  // again to stop. The browser also stops by itself when you stop speaking.

  var Recognition = root.SpeechRecognition || root.webkitSpeechRecognition;
  var recognition = null;
  var listening = false;
  var pressedAt = 0; // when the current press began; 0 when nothing is held
  var pressStarted = false; // whether that press was the one that started listening
  var lastPressAt = 0; // when a pointer or key press was last dealt with, to ignore its own click

  function setListening(value) {
    listening = value;
    talkButton.setAttribute("aria-pressed", value ? "true" : "false");
    talkButton.textContent = value ? "Listening. Press to stop" : "Push to talk";
  }

  function startListening() {
    if (listening || busy || !Recognition) {
      return;
    }
    stopSpeaking();
    recognition = new Recognition();
    recognition.lang = doc.documentElement.lang || "en";
    recognition.interimResults = false;
    recognition.maxAlternatives = 1;
    recognition.onresult = function (event) {
      var heard = event.results && event.results[0] && event.results[0][0];
      if (heard && isText(heard.transcript)) {
        questionInput.value = heard.transcript;
        ask(heard.transcript);
      }
    };
    recognition.onerror = function (event) {
      if (event.error === "not-allowed" || event.error === "service-not-allowed") {
        status.textContent = "The microphone is not allowed here. Type your question instead.";
      } else if (event.error === "no-speech") {
        status.textContent = "Heard nothing. Try again, or type your question.";
      } else if (event.error !== "aborted") {
        status.textContent = "Speech recognition failed. Type your question instead.";
      }
    };
    recognition.onend = function () {
      setListening(false);
    };
    try {
      recognition.start();
      setListening(true);
      status.textContent = "Listening.";
    } catch (err) {
      setListening(false);
    }
  }

  function stopListening() {
    if (listening && recognition) {
      recognition.stop(); // delivers what was heard so far, then onend
    }
  }

  function pressDown() {
    if (pressedAt) {
      return; // a held key repeats
    }
    pressedAt = Date.now();
    lastPressAt = pressedAt;
    pressStarted = !listening;
    if (listening) {
      stopListening();
    } else {
      startListening();
    }
  }

  function pressUp() {
    if (!pressedAt) {
      return;
    }
    var held = Date.now() - pressedAt;
    pressedAt = 0;
    lastPressAt = Date.now();
    // A real hold ends the question on release. A tap leaves it listening until the next press.
    if (pressStarted && held >= HOLD_MS) {
      stopListening();
    }
  }

  function isTalkKey(event) {
    return event.key === " " || event.key === "Spacebar" || event.key === "Enter";
  }

  function wireTalkButton() {
    if (!Recognition) {
      el("ask-no-speech").hidden = false;
      return;
    }
    talkButton.hidden = false;
    el("ask-talk-hint").hidden = false;

    talkButton.addEventListener("pointerdown", function (event) {
      if (event.button === 0) {
        pressDown();
      }
    });
    talkButton.addEventListener("pointerup", pressUp);
    talkButton.addEventListener("pointercancel", pressUp);
    talkButton.addEventListener("pointerleave", pressUp);
    talkButton.addEventListener("keydown", function (event) {
      if (isTalkKey(event)) {
        event.preventDefault(); // Space must not scroll the page
        pressDown();
      }
    });
    talkButton.addEventListener("keyup", function (event) {
      if (isTalkKey(event)) {
        event.preventDefault();
        pressUp();
      }
    });
    // A click with no pointer or key press just before it comes from assistive technology (a
    // screen reader's "activate"): treat it as a tap. One that follows a press is that press.
    talkButton.addEventListener("click", function () {
      if (Date.now() - lastPressAt < CLICK_AFTER_PRESS_MS) {
        return;
      }
      if (listening) {
        stopListening();
      } else {
        startListening();
      }
    });
  }

  // -- wiring ----------------------------------------------------------------------------------

  el("ask-sign-in").addEventListener("click", signIn);
  el("ask-sign-out").addEventListener("click", signOut);
  el("ask-new").addEventListener("click", newBriefing);
  muteButton.addEventListener("click", toggleMute);
  // The API treats a question with no history as a briefing, so the shortcut starts afresh.
  el("ask-briefing").addEventListener("click", function () {
    if (busy) {
      return;
    }
    turns = [];
    clear(conversation);
    ask(BRIEFING_QUESTION);
  });
  el("ask-form").addEventListener("submit", function (event) {
    event.preventDefault();
    ask(questionInput.value);
  });
  // Leaving the page must not leave a voice talking.
  root.addEventListener("pagehide", stopSpeaking);
  wireTalkButton();
  start();
})(typeof window !== "undefined" ? window : globalThis);
